### ISSUE TITLE
使用gradio链接无法正常加载

### ISSUE THREAD

**Issue by Yanstory** [zanllp/sd-webui-infinite-image-browsing#101]
Log显示css和js被拦截，但本地版运行正常
```
GET https://XXXXXX.gradio.live/infinite_image_browsing/fe-static/assets/index-19e73083.css net::ERR_ABORTED 404
GET https://XXXXXX.gradio.live/infinite_image_browsing/fe-static/assets/index-8b7c8e1e.js net::ERR_ABORTED 404
```
![image](https://user-images.githubusercontent.com/5153875/236645624-f86bf98f-c5cc-48bf-9815-326ec39f3b14.png)

**Comment by zanllp** [comment]
试了下好像没什么问题，具体是什么环境？
这玩意还挺难debug的，如果端口转发可以用，可以先尝试使用端口转发 
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/25872019/236646992-3c90c930-042e-4b3d-8f9d-afdfa1a5f1d2.png">

**Comment by Yanstory** [comment]
我是在Kaggle上实现的

作为参考的话，原来的那个Image Browser似乎也无法读取文件内含信息（Prompt、参数等），但不知道与这个CSS/JS 404有没有关系

~~我电脑太差了跑不动只好流浪Kaggle了~~

**Comment by zanllp** [comment]
还是第一次知道这个Kaggle， ngork试过吗

**Comment by Yanstory** [comment]
哦抱歉，Kaggle是类似Colab的云运行平台，我还没试过ngork转发（因为webui内置gradio）

**Comment by zanllp** [comment]
有其他问题或者需求，请重新开一个issue
