### ISSUE TITLE
大佬你好，想问下关于图片顺序的问题

### ISSUE THREAD

**Issue by zietenL** [zanllp/sd-webui-infinite-image-browsing#102]
就是我在本地文件里如果删了照片或者进行了修改，插间里显示顺序就被打乱了，这个有什么好的解决方法么
![image](https://user-images.githubusercontent.com/130427069/236660904-31d4467d-f460-4957-a17c-327a19e2f1ef.png)

![image](https://user-images.githubusercontent.com/130427069/236660820-f40623af-8360-4f57-a9ac-9a2df4bc6d31.png)

**Comment by zanllp** [comment]
默认是按照修改时间来排的顺序，最近被修改的文件夹会被排在前面，你那边没符合预期吗？

左右都是按修改时间排序，看起来一样的
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/25872019/236662599-2e95aa5c-ea3f-48c4-a4d3-cdd92540b1e8.png">

你可以在右上角更多里面调整当前的排序方式

**Comment by zanllp** [comment]
也可以按名称排
<img width="1902" alt="image" src="https://user-images.githubusercontent.com/25872019/236663021-945c3e6f-0d45-4023-a0eb-62bc775cc080.png">

这边主要是考虑到想让最新生成的图片排在前面

**Comment by zietenL** [comment]
主要是有时想把以前的旧图删了或者重命名做个更改，然后一整个文件夹就跑前面去了，整个顺序就乱了，我试试用名称排序

**Comment by zanllp** [comment]
这种场景下感觉是有点变扭，我后面看看能不能将排序拉到外面显示，然后还是保存起来的

**Comment by zietenL** [comment]
其实感觉或许能增加一个按照创建时间的排序？这样文件夹应该就不会乱跑了

**Comment by zanllp** [comment]
确实可以，我忘记了还有创建日期，我过会加上，并改成默认

**Comment by zietenL** [comment]
谢谢大佬！！

**Comment by zanllp** [comment]
我已经更新到主分支，你可以更新下插件看看，之前因为是多种文件系统混合，另外一个只有修改时间，我就一直忽略了这个事情。这个确实是能对体验有很大的改善

以后要是star多点搞个贡献者名单，肯定把你拉进idea里面
