### ISSUE TITLE
Bug: a missing english translation for Copy source file preview link message

### ISSUE THREAD

**Issue by sean-kang** [zanllp/sd-webui-infinite-image-browsing#109]
If I click "Copy source file preview link" on an image, it returns a message in Chinese as below.

"已复制内容 "/infinite_image_browsing/file?filename=%2Fhome%2Fredacted%2Fstable-diffusion-webui%2Foutputs%2Fsave%2Fredacted.png" 到粘贴板"

**Comment by zanllp** [comment]
It's probably an untranslated function, don't worry about it. The message above is just to let you know that the copy has been completed.

**Comment by zanllp** [comment]
Already fixed.
. If you have any further problems or requests, please create a new issue.
