### ISSUE TITLE
Sent to XXX sends all the settings as prompt

### ISSUE THREAD

**Issue by Mozoloa** [zanllp/sd-webui-infinite-image-browsing#115]
When selecting and image, then send it to txt2img for instance from the context menu, all the settings are sent as a prompt, so now the prompt containts model hash, cfg, seed etc

**Comment by zanllp** [comment]
The current behavior is as expected.
 I didn't quite understand what you meant.Are you asking to only send the prompt?

**Comment by zanllp** [comment]
It looks like it has been a while since a reply. If you need to respond, please reopen this issue
