### ISSUE TITLE
Lock access to specific folders

### ISSUE THREAD

**Issue by MichaelDavidGK** [zanllp/sd-webui-infinite-image-browsing#116]
Any chance you could add locking access to specific folders only?
This is especially useful when sharing SD webui with other people
Otherwise they will simply be able to access almost everything on your PC

**Comment by zanllp** [comment]
Will allow you to add specific paths to “quick move”.

**Comment by zanllp** [comment]
this feature may be implemented together with #67 . It requires more effort compared to other features, and its benefits may not be very clear for individual users.

**Comment by MichaelDavidGK** [comment]
No worries, for now I use another user with restricted permissions cause of
that 😅

**Comment by offroadguy56** [comment]
I too would like to restrict access to a specific folder path. But on a networked folder such as \\SERVERNAME\StableDiffusionImages\output\

**Comment by zanllp** [comment]
This feature has already been implemented.

see https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/131
