### ISSUE TITLE
Quick Move broken for networked folders

### ISSUE THREAD

**Issue by offroadguy56** [zanllp/sd-webui-infinite-image-browsing#122]
It seems the quick move is broken for output folders that are stored on a networked drive over Samba. When I load up Image Search for the first time I go through the process of indexing everything. It succeeds without issue. I can see in the console that it properly locates my folders. (an example:   Processing folder: \\\SERVERNAME\StableDiffusionImages\output\txt2img-images). I am able to search my images and locate them no problem via Image Search. 

When I go over to Launch>Local. I cannot find the networked folders. When I go to Launch from Quick Move and click txt2img it says "Move failed. Check your path input.SERVERNAME not found"

**Comment by zanllp** [comment]
Python's os.listdir function does not support directly listing files in network drives. This issue may be resolved after implementing feature #116.

**Comment by offroadguy56** [comment]
Network folders still don't seem to work in IIB. 

However if you map a network folder to a drive letter it works.

Not my intended solution, but it will work until more support is added. 

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/6194572/2bccfea5-f9ee-4a41-a485-6c878ab39afd)
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/6194572/9bd67ef9-d379-4804-9f0e-083daaf612eb)

**Comment by zanllp** [comment]
Network paths are now supported.
