### ISSUE TITLE
Image Search doesn't automatically update after each image generation

### ISSUE THREAD

**Issue by offroadguy56** [zanllp/sd-webui-infinite-image-browsing#123]
As the title says.
Generate an image or set of images. Go to the Image Search and search for tags that will result in finding those images. They do not show up in the results. If the webui webpage is reloaded you can go back and search for the images and they will be there. 

Not a huge issue, just an annoyance.

**Comment by zanllp** [comment]
For performance reasons, currently we only check for updates to the index when you create a new image search tab. 

Previously, I didn't consider the possibility that someone might be generating images while simultaneously searching for the images just generated. 

 I'll explore if there is a better way to address this issue.

**Comment by zanllp** [comment]
New feature: When you return to the extension, the image search will automatically check if the index is expired. If the index is expired, you can update it by clicking the 'Update Index' button. 

Then, after clicking the search button, you will be able to see the newly generated images.

https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/cc4a4cf6-7a38-4cb1-af5c-8a17a8b858bf

**Comment by offroadguy56** [comment]
I would say this update is only a marginal improvement over before. I still have to clear my search, put the tags back in, then it will update the index and return my new images.

If clicking the search button each time also performed an index that would be nice. Or the index could be referenced to the image generate button. Pull the status of current generation then when it sees it complete check for changes in the folders. Or have the index check for changes periodically? I haven't see any performance issues yet. Though I only have about 13,000 images.

**Comment by offroadguy56** [comment]
> Previously, I didn't consider the possibility that someone might be generating images while simultaneously searching for the images just generated.

In reply to that. I will leave the search open, go make changes to various prompts. Then look at the results in image search. For the first time on the session, its not an issue because the new image search tab will do the index. But afterwards when I generate more images and I left the image search open to get back to where I was quickly I will have to close the tab, or as it is now, remove the search tags and then put them back in the search box.

**Comment by zanllp** [comment]
You don't need to clear the search. 


https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/caf68573-7a71-4e87-9e5d-d9d5d1c47eb7

**Comment by offroadguy56** [comment]
How very strange. It definitely wasn't doing that after I updated the extension. I swear I'm not crazy.

But it seems to be working now after leaving my computer be for several hours.

Great stuff! Keep up the work!

**Comment by zanllp** [comment]
Perhaps it's caused by browser cache. After updating, it's best to restart sd-webui.
If you have any further problems or requests, please create a new issue.
