### ISSUE TITLE
插件起个英文的名称吧

### ISSUE THREAD

**Issue by arpir** [zanllp/sd-webui-infinite-image-browsing#125]
![Snipaste_2023-05-11_23-49-19](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25816449/9dfeeee0-0c22-48bd-bf6e-954a0eb44416)

给插件个英文名字吧,逼死强迫症了

**Comment by zanllp** [comment]
🤣，插件名称是根据你系统的语言动态返回中文还是英文的，目前几个翻译好像都没收录我的插件，如果他们收录了是可以只保留英文
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/4c8901a3-beb9-4f17-81fb-b4e6e9afeb7c)

**Comment by arpir** [comment]
> 🤣，插件名称是根据你系统的语言动态返回中文还是英文的，目前几个翻译好像都没收录我的插件，如果他们收录了是可以只保留英文 ![image](https://user-images.githubusercontent.com/25872019/237746237-4c8901a3-beb9-4f17-81fb-b4e6e9afeb7c.png)

你的主题图标很好看呀,我的界面切回英文,不使用翻译文件的时候,插件还是会显示中文,就不知道为什么没有英文[infinite image browsing]

**Comment by zanllp** [comment]
> > 🤣，插件名称是根据你系统的语言动态返回中文还是英文的，目前几个翻译好像都没收录我的插件，如果他们收录了是可以只保留英文 ![image](https://user-images.githubusercontent.com/25872019/237746237-4c8901a3-beb9-4f17-81fb-b4e6e9afeb7c.png)
> 
> 你的主题图标很好看呀,我的界面切回英文,不使用翻译文件的时候,插件还是会显示中文,就不知道为什么没有英文[infinite image browsing]

插件的前后端i18n是分离的，目前选英文只能控制前端。你真想要英文可以把 [locale = get_locale()](https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/d67fcf939465d943b2abfda284a8c2e25f53042f/scripts/tool.py#L190)  改成`locale = 'en'`

但这会干扰到以后升级

**Comment by arpir** [comment]
> > > 🤣，插件名称是根据你系统的语言动态返回中文还是英文的，目前几个翻译好像都没收录我的插件，如果他们收录了是可以只保留英文 ![image](https://user-images.githubusercontent.com/25872019/237746237-4c8901a3-beb9-4f17-81fb-b4e6e9afeb7c.png)
> > 
> > 
> > 你的主题图标很好看呀,我的界面切回英文,不使用翻译文件的时候,插件还是会显示中文,就不知道为什么没有英文[infinite image browsing]
> 
> 插件的前后端i18n是分离的，目前选英文只能控制前端。你真想要英文可以把 [locale = get_locale()](https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/d67fcf939465d943b2abfda284a8c2e25f53042f/scripts/tool.py#L190) 改成`locale = 'en'`
> 
> 但这会干扰到以后升级

我试着手动修改 [locale = get_locale()](https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/d67fcf939465d943b2abfda284a8c2e25f53042f/scripts/tool.py#L190) ,然后在i18n的翻译文件添加"Infinite image browsing": "无边图像浏览",这个时候，其他地方都是中英双语，Infinite image browsing 只显示英文了😂

**Comment by zanllp** [comment]
<img width="955" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/83dbf558-7b4e-4c27-bda1-535199c921ca">


typo了吧
```json
{
   "Infinite image browsing": "贼快的图像浏览器"
}
```

**Comment by arpir** [comment]
> <img alt="image" width="955" src="https://user-images.githubusercontent.com/25872019/237970316-83dbf558-7b4e-4c27-bda1-535199c921ca.png">
> typo了吧
> 
> ```json
> {
>    "Infinite image browsing": "贼快的图像浏览器"
> }
> ```

可以了，可以了，贼快😂
