### ISSUE TITLE
Send to Saved button in full preview mode

### ISSUE THREAD

**Issue by Averytingwong** [zanllp/sd-webui-infinite-image-browsing#128]
Hi,

Id love a send to saved or mark as favorite button while in full screen preview. I just want to flip through images without having to leave full sized preview mode. I know there is a right click menu, but that doesn't work in full sized mode, when I'm browsing on my tablet I have to exit full size mode, right click (or hold tap on mobile), and I  menu is a little hard to use, since it often leads to mistaps. There is already a zoom and rotate icons on the top right of full size preview, that would be a great spot to add this button.

Thank you!

**Comment by zanllp** [comment]
Thanks for your suggestion! I'll optimize the app for tablet devices and enable opening the context menu with a finger tap. Regarding the new button, unfortunately, I won't be able to place it together with the zoom button since that is a third-party component that I can't modify. However, I'll find a suitable location for it and make it easy to use. Thank you again for your feedback!

**Comment by Averytingwong** [comment]
No, thank YOU for making such an awesome extension!

Another thing I noticed while on tablet, if I hold tap on an image to save, it saves as "file.jpg" instead of the actual image name. I spent an hour the other day saving images into my tablet only to find out I was overwriting the same image over and over. I don't have this issue with the other image browser extension (but that one isnt nearly as fast and easy to use as yours). I'm using Firefox Nightly Build on an Android tablet if that info has any use.

**Comment by zanllp** [comment]
Update to the latest version and do not save directly. Instead, use the download option from the context menu. I tried it on my phone and didn't find any issues.

https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/7997984b-5616-4c9d-aedc-70127f880efb

**Comment by Averytingwong** [comment]
> Update to the latest version and do not save directly. Instead, use the download option from the context menu. I tried it on my phone and didn't find any issues.
> 5DC94FE0C0439E9ACA29F375F296FAF1.mp4

Thanks for looking into this. While this works, it is not a useful solution for what I'm looking for. I'm looking for a quick way to flip through images and to save the actual file and retaining the original image filename onto my tablet (tap next, hold tap, save). The context menu requires 7 taps per image (select image, tap the expand info icon, tap context menu, tap save to drive (which opens a new tab), tap close new browser tab, tap collapse info window (so I can see the image since it blocks a quarter of the view, it also this often gets stuck and does not collapse), tap next image, repeat.

**Comment by zanllp** [comment]
I found another method that you can update the extension with. Now you can save it like any other image in other extensions. However, implementing this feature was difficult due to the extension's more granular control over caching.
