### ISSUE TITLE
Cannot find save folder on fresh webui install until /log/images is manually created [Linux]

### ISSUE THREAD

**Issue by dunkeroni** [zanllp/sd-webui-infinite-image-browsing#130]
The default save directory is in the config.json ("outdir_save": "log/images") of webui but it does not exist by default in the folder structure. Images cannot be sent there until the log/images folder is manually created.

That might be different on Windows. I have only tested on Linux Mint.

**Comment by zanllp** [comment]
I'll add a check later to create a new folder if it doesn't exist. I've always assumed that these folders already exist by default.

**Comment by zanllp** [comment]
Already added， I'm sorry for the delay after such a long time.
