### ISSUE TITLE
Feature request: Move .txt file along with img when using "Save to Saved Folder"

### ISSUE THREAD

**Issue by oshimoto** [zanllp/sd-webui-infinite-image-browsing#140]
Hi! 
Would you please consider adding an option to move the .txt file with generational parameters along with the image, when using the  "Send to Saved Folder" function. 
The text file is created by the "Create a text file next to every image with generation parameter" option in the WebUI.

Thanks for all the great work you are putting in this project, I really appreciate it!

**Comment by zanllp** [comment]
Thank you for bringing up this issue and sorry for the delay in getting back to you.

 You can update to the latest version to resolve it. When you delete or move an image now, the corresponding .txt file will also be moved or deleted together.
