### ISSUE TITLE
如何清理重置缩略图缓存？

### ISSUE THREAD

**Issue by tangerdream** [zanllp/sd-webui-infinite-image-browsing#141]
![QQ截图20230515132554](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/72326927/ce70317e-00c7-4149-a953-8830211b49c4)
这是一张我已经删除的图像的缩略图，但是它并没有在插件中消失，因为我又重新生成了一张同名的图像，然而缩略图还是旧的已经被我删除的那个。。没有更新。。所以有没有清除缩略图缓存的方法

**Comment by zanllp** [comment]
<img width="930" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/e19587b5-997d-42c4-9f2a-54ef5230eb08">

手动清理临时文件夹，下面是插件获取的文件夹的环境变量
<img width="619" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/91a0e5a5-578f-41dc-98e7-1aa33d681eb9">

**Comment by zanllp** [comment]
如果还有其他问题重新开一个issue，或者reopen
