### ISSUE TITLE
建议加一个打开图片所在文件夹的功能

### ISSUE THREAD

**Issue by pimin12** [zanllp/sd-webui-infinite-image-browsing#146]
有时候还是直接在文件夹里方便，批量删除之类的

**Comment by zanllp** [comment]
不过目前在拓展外删除图片好像会对搜索造成问题，因为我不知道你删除了哪些图片，那些图片还会留在数据库内。

你想批量删除直接用拓展的多选删除也可以

**Comment by zanllp** [comment]
支持了 see https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/131
