### ISSUE TITLE
How fav/like works?

### ISSUE THREAD

**Issue by rubensicko** [zanllp/sd-webui-infinite-image-browsing#151]
If I want to like/fav a photo, it shows me an error:

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/75501780/b2f386f2-d963-41b9-8167-8ba9a658c187)

How can I add photos to favorites and be able to see them later?

Thanks

**Comment by zanllp** [comment]
The image you have saved, is it not in the folder specified by the stable diffusion webui? Or maybe you are running this repo independently?

**Comment by rubensicko** [comment]
Hi, i save the images outside of sd webui. I'm running this repo as extensions in auto1111. It works fine, i can seach, browse, but the fav toggle doesn't work in my case. Can i make it work?

**Comment by zanllp** [comment]
At the moment, it is not possible to favorite pictures outside of the folder specified in sd-webui. However, this feature will be supported in the near future.

**Comment by zanllp** [comment]
The feature is already supported. Please refer to https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/131 for details.

You can add it to the search scan path.
