### ISSUE TITLE
Bug: Auto refresh works sometimes

### ISSUE THREAD

**Issue by nickion** [zanllp/sd-webui-infinite-image-browsing#157]
The autorefresh that the plugin has at the moment works great when it works, however it's very hit and miss. Sometimes when switching to the browsing tab it will say that changes are detected and refresh, however it never seems to update when switching to any other views that may exist. So if there is both a txt2img and img2img view for example, and txt2img is the one that's selected, when switching to the browser tab the txt2img view may refresh, but then flipping to the img2img view there never seems to be an update and it's always stale. Clicking refresh is always required to bring it up to date.

**Comment by zanllp** [comment]
Automatic refresh only works under the following conditions, you can check if it meets your expectations. This feature is currently designed to allow you to view the generated images in this extension after switching to the infinite-image-browsing tab in the stable diffusion webui or when there is a visibilityState change, which includes:

1. Switching to the infinite-image-browsing tab in the stable diffusion webui.
2. VisibilityState change, which includes:
   1. User minimizes the browser window or switches to other tabs or applications.
   2. User minimizes the browser window or switches to other tabs or applications, and then restores the window to its original state.
   3. User switches back to the current page from other tabs or applications.

**Comment by zanllp** [comment]
The automatic refresh is not available in walk mode.

**Comment by nickion** [comment]
Thanks, and sorry for not being aware of that. I tend to have tabs for txt2 and img2 open, and I find using the "walk" links to add them is easiest; particularly with directories on Unix likely to be shown out of order, having to locate the directory for the current date can be awkward, and it might not even exist yet when it's a new day.  I'll close as it's not a bug, and if you ever get a chance to tackle auto refresh for walk views such as https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/138 or something better that you might come up with, it would make the plugin even more awesome than it already is.

**Comment by zanllp** [comment]
This extension will continue to be improved, but my energy is limited.
