### ISSUE TITLE
Walk模式的预览图文件夹路径与实际不一致

### ISSUE THREAD

**Issue by yincangshiwei** [zanllp/sd-webui-infinite-image-browsing#158]
Walk模式的文生图文件夹路径与快速启动路径不一致，并且是不对的。
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/8185843/742a158a-b353-4e11-beab-5ca57aad1b47)
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/8185843/b6e10151-873b-4309-b7c6-ab119349d8f1)
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/8185843/82405397-1e34-4aeb-9d2e-f2c09b090efc)

**Comment by zanllp** [comment]
看起来没什么问题啊，walk下的路径栏显示的是当前加载到的文件夹。walk模式下是把文生图下面的子文件夹都合并到一起，你当前文件夹的图片看完了，就自动按照排序给你加载下一个
