### ISSUE TITLE
Feature request: Assign keys to the tag system for quicker tagging

### ISSUE THREAD

**Issue by PointOfKnowReturnWiki** [zanllp/sd-webui-infinite-image-browsing#159]
The tag system is awesome, customizable, and expandable. A feature for me to interact with it more quickly would be nice. Being able to assign a key to the tags that applies while previewed, Ex. "F = Like" would achieve this.

**Comment by zanllp** [comment]
Looks useful. I will look into how to implement it later.

**Comment by zanllp** [comment]
Deleting and favoriting the current image in full-screen preview mode is now supported. I will be adding more operation support soon, such as toggling custom tag selected.

https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/c3615fdc-3184-46b7-ace5-5ca1c923cedb

**Comment by PointOfKnowReturnWiki** [comment]
So cool, this is a game changer!
