### ISSUE TITLE
Feature request: Possible addition of Show/Hide toggle?

### ISSUE THREAD

**Issue by sparuj** [zanllp/sd-webui-infinite-image-browsing#165]
Hello,

Thank you very much for this extension, amazing work!

I just wanted to ask if you are planning on adding a Show/Hide toggle for Model, LoRa, Positive Prompt, Size in the future?

![1](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/50428238/d07773e3-c57b-4bae-9366-6718250d365e)
![2](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/50428238/519ad524-21dd-4caf-b3b4-f3b71639164e)

Best Regards!

**Comment by zanllp** [comment]
It has been implemented.
