### ISSUE TITLE
Bug: File retrieval on Linux (WSL2)

### ISSUE THREAD

**Issue by bilwis** [zanllp/sd-webui-infinite-image-browsing#168]
First, thanks for your work, it looks exactly what I've been looking for!

I'm running your program standalone on WSL2 running Ubuntu 22.04 with vladmandic's Stable Diffusion WebUI. The output folder is symlinked (ln -s) to a "Windows drive", which hasn't been a problem so far. However, I'm running into some issues with your program, which I suspect are related to file retrieval.

First off, walk mode is extremely slow, with the program working about ~1 minute at ~25% CPU load to open any folder, even ones with only one file.

Secondly, when it opens a folder, it will display the thumbnail previews and the generation parameters, but not the full image. The log says: 

```
...
INFO:     127.0.0.1:33578 - "GET /infinite_image_browsing/image_geninfo?path=%2Fhome%2Fbilwis%2Fautomatic%2Foutputs%2Fsave%2Ffilename.jpg HTTP/1.1" 200 OK
INFO:     127.0.0.1:33578 - "GET /infinite_image_browsing/file//home/bilwis/automatic/outputs/save/filename.jpg?t=2023-05-09%2017%3A53%3A04 HTTP/1.1" 404 Not Found
...
```

Changing the WSL2 config.json to absolute paths to the "Windows drive", i.e. /mnt/e/outputs, bypassing the symlink, resulted in the same behaviour.

When running the program on Windows and pointing it directly to the output directory with an edited config.json, everything works fine.

If you need any more info, I'll be happy to provide it!

**Comment by zanllp** [comment]
alread fixed ， update to latest version to resolve it

**Comment by bilwis** [comment]
Confirmed working. Very nice, thank you!
