### ISSUE TITLE
[Enhancement] Image Preview Navigation

### ISSUE THREAD

**Issue by KominoStyle** [zanllp/sd-webui-infinite-image-browsing#172]
When using the right navigation to view other images, I noticed that at some point, the button on the right becomes disabled, and an info message appears saying "loading files from the next folder." Interestingly, this can happen even if the images are in the same folder. I understand that this delay in loading images is likely for performance reasons, but the problem is that nothing happens when the button is disabled. To continue navigating, I have to scroll down to load the next batch of images in the preview. The same issue occurs when we reach the end and can no longer load more images.

Would it be possible for you to implement a feature that automatically loads the next batch of images when reaching the end of the preview? This would greatly improve the experience by eliminating the need for manual scrolling and loading.

**Comment by zanllp** [comment]
It seems to be a bug caused by some feature modifications, as this feature was supported previously. I will fix this issue soon.

**Comment by zanllp** [comment]
Already fixed
