### ISSUE TITLE
Bug: error due to inability to remove "quick move" folders

### ISSUE THREAD

**Issue by PaperOrb** [zanllp/sd-webui-infinite-image-browsing#173]
How to reproduce: if you add a folder to the quick move menu and then delete that folder on the OS, any time you go to an image search tab you'll be greeted with a red X notification that says the folder is missing. The notification gives no way to remedy the situation. From now on, every time you visit the image search tab, you'll get an annoying little red x notification that lingers any time you click update index on the search page. Also the "update index" button becomes unclickable as a result.

This could be fixed if folders could be removed from the quick move menu. It also wouldn't hurt to have a way to close these popup notifications since they linger a little too long before disappearing, which can be annoying.

**Comment by zanllp** [comment]
You can temporarily create the deleted folder first, and then remove it from Quick Move in the More menu at the upper right corner. 

Alternatively, you can delete iib.db, but any manually added data will be lost. 

Or you can wait for me to handle this issue later

**Comment by zanllp** [comment]
Already fixed

**Comment by PaperOrb** [comment]
> Already fixed

I was going to say np and take your time but then saw this comment lol. I'll check it out, much appreciated!
