### ISSUE TITLE
功能请求:可否在大图片界面增加删除功能和发送到各个功能界面的功能？

### ISSUE THREAD

**Issue by YIULIYL** [zanllp/sd-webui-infinite-image-browsing#181]
原来用图库浏览器，最近更新了用不了，换了这个，蛮好用的，有很多功能很惊喜
但是也有些比较常用的功能可以增加
比如删除按钮，随出随删更方便
还有就是把参数和图片直接发送到图生图、文生图各种界面
我用SD图库插件最大的原因就是这两个，因为可以在webUI里直接进行互动才是我选择在UI里操作的理由嘛
还有就是图片大了很容易被图片参数遮住，可否设置一个固定一点的位置放参数不要让它挡在最前面？

**Comment by YIULIYL** [comment]
啊，在预览界面有这个功能，我主要想请求在大图界面能有设置加一个的选项，毕竟这俩功能蛮常用的，小图右键挺不方便的

**Comment by YIULIYL** [comment]
> <img alt="image" width="1658" src="https://user-images.githubusercontent.com/25872019/240270475-5d2b1365-229c-47e4-a9b1-89b0f6d8dcc9.png"> 不是有吗，现在需要你鼠标移动上去才会出现上下文菜单，后面会直接展开可以点

哦哦，原来是在这里，那这种菜单能做成界面样式吗，这个信息框超级容易挡在图片前面，放长图又要动一下，放宽图又要动一下，感觉放在哪里都好尴尬……
个人认为在SD ui里用插件主要是图操作方便，希望这几个按钮尽可能容易按到一点
没必要太要求图片显示太大。最好能切换界面模式和无边模式就最好了……

**Comment by zanllp** [comment]
这块暂时不会做太大改动，很多第三方的库，我改起来很困难
