### ISSUE TITLE
希望软件语言能默认跟随sd-webui的设置

### ISSUE THREAD

**Issue by gustavmilo** [zanllp/sd-webui-infinite-image-browsing#189]
![2023-05-26_231632](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/129682674/365adb9f-97e8-4958-8440-1859d5b7cb62)

希望软件语言能默认跟随sd-webui的设置
现在所有标签都是英文的，只有无界浏览相关标签是中文，有点尴尬呢

谢谢你的优秀插件，确实很实用，相应灰常快，很赞

**Comment by zanllp** [comment]
这个拓展架构和其他不太一样,很多都是我们自己实现的，别人的而json翻译插件用不了且文本量很大。 
sd-webui是只有英文，我们自动检测你的本地化来切换。

我后面再.env里面加个配置吧，允许强制指定语言

**Comment by gustavmilo** [comment]
> 这个拓展架构和其他不太一样,很多都是我们自己实现的，别人的json翻译插件用不了且文本量很大。 sd-webui是只有英文，然后有拓展通过配置i18n来覆盖，我们是自动检测你的本地化来切换。
> 
> 我后面在.env里面加个配置吧，允许强制指定语言

谢谢你的回复，那就有劳大佬了

**Comment by zanllp** [comment]
<img width="746" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/71e837cd-1fe5-43e0-9795-38a71ada6cd4">
拓展根目录下面从.env.example 复制个.env 文件，然后把语言设置为en就行了

**Comment by gustavmilo** [comment]
![2023-05-27_123545](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/129682674/32b9cf31-ec5d-4bba-8754-936ad3fe849a)
按照你给定的步骤操作了，缺省【空白启动页】标签仍然出现中文，手动新建空白标签能很好地显示英文

**Comment by zanllp** [comment]
更新下看看

**Comment by gustavmilo** [comment]
更新后 问题依旧呢 清空浏览器缓存 貌似也不起作用
另外 换了一个浏览器后 默认【全局设置】自动回到了中文，而且空白标签页的问题依旧

**Comment by zanllp** [comment]
换浏览器回到中文是正常的，前端部分的配置目前是保存在浏览器上，即使是跨域都会重置

你更新后尝试重启sd-webui了吗

**Comment by gustavmilo** [comment]
重启了呢

**Comment by zanllp** [comment]
你确认更新到这个commit了吗 ，我感觉这是不太可能的事情
<img width="1019" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/c3950fe6-bb7f-43b4-ae5d-e30c561299d7">


你也可以把前端f12的禁用缓存暂时打开看看 
<img width="790" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/99fe95f9-a1f0-4e39-9f0a-bea2587ef9b8">

**Comment by gustavmilo** [comment]
刚是没更新到最新，这会儿更新到#194后问题解决了，感谢大佬的耐心！

**Comment by zanllp** [comment]
那行，有其他问题重新提
