### ISSUE TITLE
cannot import name secret_key from scripts.tool

### ISSUE THREAD

**Issue by picobyte** [zanllp/sd-webui-infinite-image-browsing#192]
```
Error loading script: api.py
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/api.py", line 5, in <module>
    from scripts.tool import (
ImportError: cannot import name 'secret_key' from 'scripts.tool' (/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/tool.py)
```
and my stablediffusion was dysfunctional on runpod, also my local (on CPU) became dysfunctional after updates (three; this extension was one that got updated, yesterday local did work). Disabling this extension made stable-diffusion_webui work again.

Not 100% what causes the import of secret_key to fail. Maybe it should be assigned "" if environment lookup returns None?

**Comment by zanllp** [comment]
I have tested on my Win10 PC, MacBook Pro, WSL, Colab, and several cloud platforms, but I couldn't reproduce this issue. You can check if you've made any changes to the code.

You can execute the following command in the root directory of this extension to reset to the latest commit and then try restarting the SD-WebUI:

```bash
git reset --hard 6174b58e84d89e4dbf81fd12b1a2d9641c1b46a5
```

**Comment by zanllp** [comment]
Although I'm a Python newbie, I don't think ImportError is caused by None.

**Comment by picobyte** [comment]
I didn't have local changes. Today I did another update of my extensions, and now the issue seems resolved. Not sure what the issue was, but I'll close it as no longer reproducible. It may be just a bleeding edge issue? Thanks anyway, for your attention.
