### ISSUE TITLE
请求加入评分系统

### ISSUE THREAD

**Issue by 350640267** [zanllp/sd-webui-infinite-image-browsing#196]
像原生图库浏览那样可以评分1-5分以及根据评分筛选，谢谢！！

**Comment by 350640267** [comment]
还有批量删除功能。。。谢谢！

**Comment by zanllp** [comment]
<img width="309" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/d2467e70-40d7-41b7-93f2-fd004657c5fb">
批量删除可以用， ，或直接右键打开本地浏览器删除

评分这种东西说实话，那是我感觉他们没办法实现自定义tag和通过tag反查图片才想出来的替代品。  

虽然你们用习惯了，但是我大概率不会实现，当然提的人多了我还是会加的

**Comment by 350640267** [comment]
谢谢回复！

**Comment by zanllp** [comment]
那行，我先关了。如果有其他问题重新提一个，功能会根据更多的反馈来调整，这个实现起来成本也不低
