### ISSUE TITLE
这个插件是否和其他插件有冲突 我在装了这个插件之后 所有模型都消失了

### ISSUE THREAD

**Issue by baifagg** [zanllp/sd-webui-infinite-image-browsing#198]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/51266591/6ba9e1fc-c6b0-4ea6-b172-65d0cf1feb86)
如图 刷新按钮失效，模型消失，我确定是在安装这个插件之后模型消失了，不知道进行了什么改变，然后在我完全删除这个插件文件夹之后，重启webui就会恢复正常。

**Comment by baifagg** [comment]
我猜测最有可能冲突的是kitchen主题，因为在我取消加载kitchen插件之后，模型又出现了
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/51266591/1b965cb4-70a5-475b-9f0b-4b5b614fdcc7)
我不知道是什么原因产生了这个改变，但是您两位的插件都是我很喜欢的，也很感谢两位的辛苦付出和无私分享，不知道其他人是否和我有一样的问题

**Comment by zanllp** [comment]
命令行有消息输出吗？，我看用这个的之前也有人在用kitchen,应该不至于

**Comment by baifagg** [comment]
> 命令行有消息输出吗？，我看用这个的之前也有人在用kitchen,应该不至于

稍等 我给你看一下

**Comment by zanllp** [comment]
<img width="1917" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/34199ea6-e837-4af2-ac31-e1f36d1f59fd">
试了下应该没问题

**Comment by baifagg** [comment]
> <img alt="image" width="1917" src="https://user-images.githubusercontent.com/25872019/241411685-34199ea6-e837-4af2-ac31-e1f36d1f59fd.png"> 试了下应该没问题

我之前还重装过一次webui，一个一个插件来排除是哪个插件，现在看来是只有我有这个问题。太难受了，稍等我开放一下自己的网址你看是否可以访问 这个我之后会关了或者删除

**Comment by zanllp** [comment]
你加我qq吧，直接放出来太危险了
