### ISSUE TITLE
Feature Request - multiple selection

### ISSUE THREAD

**Issue by stavsap** [zanllp/sd-webui-infinite-image-browsing#199]
is it possible to ad multiple selection for bulk operation such as delete?

**Comment by zanllp** [comment]
<img width="521" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/cbeb9452-dda2-4a9c-814f-24feadd6ec90">

**Comment by stavsap** [comment]
sorry, missed this, great thank you
