### ISSUE TITLE
[功能建议] 希望未来可以加入关键词搜索的功能

### ISSUE THREAD

**Issue by zyd232** [zanllp/sd-webui-infinite-image-browsing#20]
主要是对图片中 exif 信息的搜索，方便通过搜索tag在以前生成的海量图片里找到相关的图

**Comment by zanllp** [comment]
之前就有想过这个，想把prompt ,lora ,model 这些都转成tag。自己也可以右键手动添加tag。
tag会通过词云，或者列表什么的放在一起显示管理。
还可以进行and or not这些给你放在多选框里面查询进行查询。

当前主要是有几个性能相关的点，还有我们经常从其他电脑通过百度云移动过来的图片怎么处理 还没想好。

**Comment by zanllp** [comment]
因为一些原因，我临时上了个未完成的版本你可以先看下
