### ISSUE TITLE
Feature request: Persistent view

### ISSUE THREAD

**Issue by nickion** [zanllp/sd-webui-infinite-image-browsing#201]
The UI state is currently lost if the A1111 page is refreshed. Add an option to persist the UI state and restore on load to avoid the need for the user to setup their view again.

**Comment by zanllp** [comment]
It used to be possible to achieve this by clicking on this button, but there seems to be some issue recently and I haven't had the time to fix it

<img width="502" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/a758b235-da4a-4506-9cb4-23a5738203eb">

**Comment by zanllp** [comment]
<img width="1145" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/8cdcbf85-f75f-4266-bb99-2fa2b7421988">
You can click here to implement this function.
