### ISSUE TITLE
最新版本无法正确启动

### ISSUE THREAD

**Issue by yuno779** [zanllp/sd-webui-infinite-image-browsing#211]
在6月1日的版本中运行是正常的，但是当我使用6月3日的最新版本时出现了一片漆黑的情况。我尝试使用了包括停用缓存等一系列操作，最后都不起作用
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/131428984/cd9986db-4ab5-4759-a656-f51eb4f0e3c6)
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/131428984/c4eebd16-a5b8-4b6d-a1bd-989bf276fbf0)

**Comment by yuno779** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/131428984/89ac3378-83f0-43ef-9478-1cd779eb6ead)

**Comment by zanllp** [comment]
有什么其他的错误信息吗

**Comment by MonkeyDocs** [comment]
I have this error too
![Screens](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/61049870/478bc60a-99be-43a2-ae33-d5156eb9d82c)

**Comment by zanllp** [comment]
@yuno779 @MonkeyDocs 升级到最新版解决问题  update to the latest version to resolve the issue

**Comment by MonkeyDocs** [comment]
> @yuno779 @MonkeyDocs 升级到最新版解决问题 update to the latest version to resolve the issue

It's working now, thanks!
