### ISSUE TITLE
Feature request: Window height settings

### ISSUE THREAD

**Issue by Kampfarsch** [zanllp/sd-webui-infinite-image-browsing#216]
Just a checkbox that resizes it to fit into your window height would be fine too.
Right now I have to scroll down 1.5 clicks to see the entire window but then all the SD tabs at the top are off-screen that makes using this extension pretty annoying.

**Comment by zanllp** [comment]
You can temporarily alleviate this issue by using 'Open in new tab'.
<img width="636" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/fa733aae-8cb4-4c6a-8315-d8890652a602">

**Comment by zanllp** [comment]
In the latest version of IIB, it is able to occupy all the space outside the top tab bar precisely, without causing dual scroll bars to appear
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/f474bf97-4247-4599-b33f-f0fdf3bb7930)

**Comment by Kampfarsch** [comment]
Very cool thank you
