### ISSUE TITLE
Security Feature Request: virtual root

### ISSUE THREAD

**Issue by nickion** [zanllp/sd-webui-infinite-image-browsing#221]
If sharing access to a system via a tunnel, a remote user can currently browse images anywhere on the system, discover the names of directories, and view and delete image content. This poses a substantial security and privacy risk.

It would be beneficial to have a setting outside of the UI that configures how far up the directory structure a user can go. If it's not possible to tell whether a client is local or remote then a single setting would suffice, but otherwise a setting for both local and remote users would be nice.  My suggestion would then be to default local users to unrestricted, and remote users to the root being the A1111 install itself. Include the feature also via the web UI settings so that a user can discover its existence, and then show text that instructs them how to edit a relevant json file on their system with the settings.

**Comment by zanllp** [comment]
Currently, you can protect your computer with a password. 
<img width="790" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/e9bb1f2a-28af-4d8b-9cc3-3c522a0ea930">


As for the concept of virtual root mentioned in #116, it's similar, and I've been wanting to implement it. However, it would require significant changes to the current architecture and would take a long time to develop and test.

**Comment by zanllp** [comment]
Currently, you can protect your computer with a password. 
<img width="755" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/0b226716-6d20-4ebd-b402-6ffbecc33156">


The concept of "virtual root" that you mentioned is similar to the "Lock access" concept mentioned in #116. I have been wanting to implement it, but it would require significant changes to the current architecture and an extensive development and testing period.

**Comment by nickion** [comment]
#116 does seem similar although perhaps the other way around, and while password access is something, it cannot guarantee protection against unauthorised access. Even if intended users with access to the UI are trusted, someone unknown might obtain access to a logged in session on a remote machine, and users with access might not be sufficiently trusted. 

I've not looked in depth at the plugin architecture, but if tackling this myself (and I wish I had time to), I would first look at the directory scanning code, and aim simply to patch that to return contents of an empty directory for an unauthorised path. This should at least prevent discovery. After that, if the code that reads an image could be patched to validate a path as within the trusted path(s) and return an empty image if not, then that should complete the process. Essentially it would just be a patch to validate that the leading part of the `realpath()` to a file or directory open matches a trusted path, and if not, empty contents are returned instead.  I'd implement a function such as `isPathTrusted()`, and then given that, the rest of the patch I'd imagine to be trivial, but maybe there is a reason I'm not aware of for why it wouldn't be.

**Comment by zanllp** [comment]
Yes, it seems like using `isPathTrusted()` to filter access to the files is a better choice. 

I have been struggling with the idea of having the extension directly access the file list in `txt2img/20xx-xx-xx`, skipping its parent folder, which has been delaying this idea.

**Comment by zanllp** [comment]
This feature has already been implemented.

see https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/131
