### ISSUE TITLE
Bug: Obvious keys for tag and delete are unavailable

### ISSUE THREAD

**Issue by nickion** [zanllp/sd-webui-infinite-image-browsing#222]
Neither space, delete nor backspace work as key sequences, either alone or with a modifier. As there is only an option of a like tag at the moment, the space bar is an obvious key to use as it's the largest, and delete/backspace are the most obvious choice for deleting. This is with Chrome on Windows 11. Haven't tested Linux yet or fired up Browser Stack to test other environments, and it may be a feature/limitation and not necessarily a bug per-se, however one would expect it to work so worth resolving is possible.

**Comment by zanllp** [comment]
only key sequences involving the keys 'shift', 'ctrl', and alphanumeric characters (a to z, 0 to 9) are currently allowed
