### ISSUE TITLE
Feature request: [edited] Add colour tagging

### ISSUE THREAD

**Issue by nickion** [zanllp/sd-webui-infinite-image-browsing#226]
(removed request for arbitrary tags as discovered this is supported 👍 )

Lightroom also has a colour tag option, and this can be very useful. It can be accessed via the UI and via shortcuts, and is very visual and quick to spot. How a user interprets colours is up to them, which is one of the benefits. Auto assigning colours based on criteria would also be good (I won't create a feature request yet as colours aren't a feature yet), but you could imagine auto colouring based on criteria such as image resolution, or properties such as upscaler type, model checkpoint, specific prompt tags and so on.

**Comment by nickion** [comment]
I updated to take out the request for arbitrary tags as I found that on the search page, and revising this idea slightly, what would be great is if tags could be assigned colours. Colouring is then linked to tagging, which makes sense as colours are used to indicate categorisation, which is what tagging does too. Colouring can be shown with a coloured border to an image, which would likely still be usable If an image has multiple tags that have colours (up to 4 at least should be feasible), and colours could also or instead (as an option) be shown as coloured dots below the image or overlayed.

**Comment by zanllp** [comment]
At the moment, I am prioritizing the implementation of the "virtual root" and "trash bin" functionalities, so I won't be able to review your requests right away. However, I appreciate your suggestions and will definitely take them into consideration when I have the chance.

**Comment by nickion** [comment]
No problem at all, and whatever you get the time to add is always appreciated. Hope you don't mind the stream of ideas.

**Comment by zanllp** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/37ec1184-acf5-42a2-b86a-736e9a49ba2c)


Currently, it assigns colors based on the names of custom tags and displays them directly.

https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/131
