### ISSUE TITLE
nginx 代理有路径的情况下使用不了，404

### ISSUE THREAD

**Issue by inewlife** [zanllp/sd-webui-infinite-image-browsing#230]
baseURL能不能修改成window.location.origin + window.location.pathname，兼容webui有代理路径的情况

**Comment by inewlife** [comment]
就是nginx 反向代理配置/subpath 到webui，访问的时候，/infinite_image_browsing这个路径404

**Comment by zanllp** [comment]
这样我感觉会引入更多风险
你们可以改成  stable-diffusion.xxx-corp.com 这种形式
或者后面我加个环境变量，你们自己手动编译一下前端

**Comment by zanllp** [comment]
对了，你直接转发不就行了
```nginx
 location /infinite_image_browsing {
        proxy_pass http://127.0.0.1:7866/infinite_image_browsing;
    }
```

**Comment by inewlife** [comment]
> 

这个有了吗

**Comment by zanllp** [comment]
没有，你在nginx那边加个代理吧。
base搞成动态有风险，我们一般要么写死，要么用环境变量编译时替换

**Comment by inewlife** [comment]
> 没有，你在nginx那边加个代理吧。 base搞成动态有风险，我们一般要么写死，要么用环境变量编译时替换

环境变量怎么设置呢

**Comment by zanllp** [comment]
一般这样 `ROUTE_BASE=/path/to/iib && yarn build` 但是这样其实也太不适合本项目，首先你得懂前端怎么编译的，而且因为这边是直接交付的编译好的产物，你重新编译完就会冲突了，所以后面使用git升级起来比较麻烦。

远不如直接转发
