### ISSUE TITLE
Bug: Search limitations

### ISSUE THREAD

**Issue by nickion** [zanllp/sd-webui-infinite-image-browsing#233]
A couple of issues with search; these may be on a todo list already (is there a public one?).

1. the search button only activates when there is content in the exact match field. A full search for items that don't have a "Like" tag is then not possible, and the user needs to find tags to use in the exact match field (e.g. resolution). Searching should be possible when any of the fields have content.

2. Clicking tags in the tag cloud always populates the exact match field. That may be an intentional design choice, but it would be nice if clicking a tag populated the text search field that had focus. Typing a short tag name in the other fields isn't too bad, but adding longer prompts to the match any field would be much harder than simply clicking the relevant tag. You might also be able to keep or regain focus on the text field after clicking on a tag to give a visual cue of which field will receive new tags, or the label of the text field or some other indicator could be used. Colour coding active tags in the tag cloud to identify which field they are in would be a nice touch, and adding a tag to a field would remove it from any other field that it was in (I don't think a tag in multiple fields makes sense).

**Comment by Chubbly** [comment]
There is another limitation of search, which is the maximum number of results that can be returned: https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/d6e84bbcd89350d200c3852cf85cc64e2962fec7/scripts/iib/db/datamodel.py#L355

I imagine this is a performance constraint. However, what is the proposed workflow to find, for example, "liked" images that have been tagged beyond the last 500 images? There doesn't appear to be a way to search for all tagged images with this limitation.

**Comment by zanllp** [comment]
> There is another limitation of search, which is the maximum number of results that can be returned:
> 
> https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/d6e84bbcd89350d200c3852cf85cc64e2962fec7/scripts/iib/db/datamodel.py#L355
> 
> I imagine this is a performance constraint. However, what is the proposed workflow to find, for example, "liked" images that have been tagged beyond the last 500 images? There doesn't appear to be a way to search for all tagged images with this limitation.

Yes, the maximum limit of 500 images returned by the image search is indeed due to performance considerations. When I was implementing this feature, I thought that 500 images would be sufficient, and any additional images beyond that limit may not be particularly necessary. However, you can still find these images by adding more matching conditions. 

In our company's projects, we usually solve this problem through pagination, but that can be cumbersome. At the moment, I don't have the enough energy or time to make such changes.

**Comment by zanllp** [comment]
> There is another limitation of search, which is the maximum number of results that can be returned:
> 
> https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/d6e84bbcd89350d200c3852cf85cc64e2962fec7/scripts/iib/db/datamodel.py#L355
> 
> I imagine this is a performance constraint. However, what is the proposed workflow to find, for example, "liked" images that have been tagged beyond the last 500 images? There doesn't appear to be a way to search for all tagged images with this limitation.

I resolved this issue in PR #390

**Comment by zanllp** [comment]
Already resolved.
