### ISSUE TITLE
Getting Error when sending to img2img

### ISSUE THREAD

**Issue by notatallshaw** [zanllp/sd-webui-infinite-image-browsing#235]
Whenever I have am browsing and select "Send to img2img" the sd webui stops working and I have this traceback in the console:

```
Traceback (most recent call last):
  File "C:\Users\damia\imagegen\stable-diffusion-webui\.venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\damia\imagegen\stable-diffusion-webui\.venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\damia\imagegen\stable-diffusion-webui\.venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\damia\imagegen\stable-diffusion-webui\.venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\damia\imagegen\stable-diffusion-webui\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\damia\imagegen\stable-diffusion-webui\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\damia\imagegen\stable-diffusion-webui\modules\generation_parameters_copypaste.py", line 379, in paste_func
    v = key(params)
  File "C:\Users\damia\imagegen\stable-diffusion-webui\modules\generation_parameters_copypaste.py", line 414, in paste_settings
    v = shared.opts.cast_value(setting_name, v)
  File "C:\Users\damia\imagegen\stable-diffusion-webui\modules\shared.py", line 692, in cast_value
    value = expected_type(value)
ValueError: invalid literal for int() with base 10: '1.5'
```

I would normally help debug issues like this but in this case I have no idea how to assist, happy to investigate with any tips.

**Comment by zanllp** [comment]
Does this happen to every image when it is send to img2img?

**Comment by notatallshaw** [comment]
My version information:

> version: [v1.3.2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/baf6946e06249c5af9851c60171692c44ef633e0)  •  python: 3.10.10  •  torch: 2.0.1+cu118  •  xformers: 0.0.17  •  gradio: 3.32.0  •  checkpoint: [7f6146b8a9](https://google.com/search?q=7f6146b8a9ad2a92b739954c1d5ef34e26fb0b65eef2d70ffd128e6046a3d0ab)

Yes it happens on every img2img, but it didn't when I first installed it, don't know what's changed.

Here's an example of the generated information:

```
Closeup of a Flower , Stary Night, Moonlight
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3022233034, Size: 512x512, Model hash: 7f6146b8a9, Model: edgeOfRealism_eorV20Fp16BakedVAE, Token merging ratio: 0.5, NGMS: 1.5, Version: v1.3.2
```

Noticing that `1.5` for NGMS looks suspicious given `1.5` is in the traceback I set it to `0` and it now I no longer get the error. Is there anyway to support having NGMS set? Or at least filter it out given it's a global setting.

**Comment by zanllp** [comment]
The code that is causing the error is actually from the sd-webui, not from our extension. Our extension is only responsible for forwarding and not for the specific parsing work. 

Although I can remove it on my end, doing so would introduce more risks. If only a few people are experiencing this error, I will not address this issue. 

This is the first time I have seen this NGMS, and as you can see, in most cases, my prompt is as follows.


```
1girl, bangs, arms behind back, simple background, bare_shoulders, blue_eyes, choker, closed_mouth, dress, flower, frills, hat, hat_bow, hat_flower, holding, long_hair, looking_at_viewer, off_shoulder, silver_hair, smile, solo, sun_hat, twintails, very_long_hair, white_dress, ((masterpiece, best quality)),,((masterpiece, best quality)),
Negative prompt: EasyNegative, (worst quality, low quality:1.3), (low quality, worst quality:1.4),multiple breasts, (mutated hands and fingers:1.5 ), (long body :1.3), (mutation, poorly drawn :1.2) , black-white, bad anatomy, liquid body, 
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3291593736, Size: 512x512, Model hash: bd83b90a2e, Model: Counterfeit-V2.5, Denoising strength: 0.7, Hires upscale: 2, Hires upscaler: Latent, Version: v1.4.0-RC
```

**Comment by aomaoyyw** [comment]
> Gotcha, I'll raise an issue with sd-webui

Token merging ratio: 0.5, NGMS: 1.5 属于提示词合并功能的参数（NGMS=反向提示词引导最小sigma）。通常情况下实现这些参数是需要重置webui的，而目前发送过去是靠复制粘贴函数，因此出错了。（你会发现所有的默认浏览器都无法把这张图发送过去，包括文生图、图生图）
在没有解决这个问题前，你可以把token合并的相关功能全部禁用来阻止生成类似NGMS的参数 :)

Token merging ratio: 0.5, NGMS: 1.5 are the parameters of the prompt merging function  (NGMS = Negative Prompt Minimum Sigma, i guess).
Usually, to realize these parameters, the webui needs to be reset, but currently sending them is by copying and pasting, so there is an error. (You will find that all default images browsers cannot send this picture, including txt2img and img2img)
Before solving this problem, you can disable all related functions of token merging to prevent the generation of parameters similar to NGMS :)
