### ISSUE TITLE
Standalone version feature requests: welcome, paths, and browser

### ISSUE THREAD

**Issue by steinhaug** [zanllp/sd-webui-infinite-image-browsing#239]
Great extension / app. Here are some thoughts regarding the standalone edition:

__Right now I am  using it like this: __  

    c.json: {"outdir_txt2img_samples": "some_dir","outdir_img2img_samples": "some_dir","outdir_extras_samples": "some_dir"}
    > python app.py --port=7888 --sd_webui_config="c.json"

__Feature requests:__

**Welcome page**  
since SD is not connected, I would like to have another welcome page. I do not need the "Use Walk mode to browse images" neither the "Launch from Quick Move".

**sd_webui_config**  
Directory "root" gives access for all possible drives, however would be nice with some custom starting points. Example could a configuration be {"e:/somepath/dir", "f:\another}. Theese could have direct links from welcome page?

**image-browser**  
Option to disable most of the existing options, also maby an option to add new options with a simple template. Say I wanted a program to open the image and the syntax was "c:\usr\prg.exe --path imagepath", would be great to have this in options.

**image-browser: preview mode**  
Option do disable this one

**Comment by zanllp** [comment]
You can manually add folders to Quick Move, which is a shortcut. You can open this folder from 'Launch from Quick Move' and it will take you directly to it.
<img width="625" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/4d62652f-f2d1-43eb-8a58-9b7c7c22ca27">
<img width="539" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/68d010bb-d538-47bb-9e31-ea6309b69da5">

**Comment by zanllp** [comment]
If you haven't passed in txt2img or img2img, 'Walk mode' will not be displayed.   

I will consider other features. The idea of being able to customize adding shortcuts during startup is a good one.

**Comment by zanllp** [comment]
Refer to the command below to implement this function.
```bash
 python app.py --extra_paths C:\Users\zanllp\Desktop\sd-remote-save\img2img-grids C:\Users\zanllp\Desktop\sd-remote-save\img2img-grids
```
<img width="1445" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/46d345b0-1a79-4b03-a1fd-f6f71cabba8c">
<img width="839" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/5361dc87-b337-41f4-94fe-973628060723">
