### ISSUE TITLE
You mind making an English version? 

### ISSUE THREAD

**Issue by xJexix** [zanllp/sd-webui-infinite-image-browsing#24]
This is better than the regular image browser for Stable Diffusion. I wanted something like this for a long time, but I can't read any of it, so an English version might be better also to add 

Also, when viewing the prompt and when you press OK, it doesn't close, but only the cancel button works. I don't know if it was made like this, but the OK button doesn't close the prompt viewing.

**Comment by zanllp** [comment]
No problem, since there's a need for it, I'll add an English version and aim to have it ready by this weekend.

Regarding the issue of viewing prompts, it will be improved together with the upcoming updates.

**Comment by zanllp** [comment]
The English version is now available and it will automatically adjust to your system preferences. 
You can also manually adjust the language in the global settings(全局设置).
You can view the English version of the readme at https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/README-en.md.
 
Upgrade the plugin and enjoy it!
