### ISSUE TITLE
Feature request: Use independent domain name to directly access image directory

### ISSUE THREAD

**Issue by ccc2020666** [zanllp/sd-webui-infinite-image-browsing#240]
Thank you for developing this great program. I want to use an independent domain name to directly access the picture directory. At the same time, I can customize functions such as removing and deleting pictures. Do not click on the file path directory. How can I achieve it? Thanks!
for example:
https://www.xxxx.com/custom picture directory 1
https://www.xxxx.com/custom picture directory 2
https://www.xxxx.com/custom picture directory 3

Place pictures directly under custom picture directories 1, 2, and 3.

**Comment by zanllp** [comment]
already added this feature. see https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/131 for more detail
