### ISSUE TITLE
Extension the remember prompts when reloading the page

### ISSUE THREAD

**Issue by JingJang** [zanllp/sd-webui-infinite-image-browsing#241]
I had an extension that remembers the prompts when reloading or applying the settings. I can no longer find it. Can someone tell me the name.

**Comment by zanllp** [comment]
This is an issue unrelated to this repository, and you should not raise it here. 


Moreover, this feature does not require any additional extension, you just need to click this button to restore it.

<img width="657" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/fbfa19d1-222b-49c2-a8ab-2f6575fb0ee0">
