### ISSUE TITLE
Feature request: saving the default image sort method in settings

### ISSUE THREAD

**Issue by sean-kang** [zanllp/sd-webui-infinite-image-browsing#242]
It seems the image sorting method is always reverted back to the default "Sort by created date by descending" no matter how many times I change the method to something else. It will be nice if the default sort method can be set in Global Settings. Thank you.

**Comment by zanllp** [comment]
already added this feature.  #131

**Comment by ali0une** [comment]
Hi there!
i'm sorry but i can't set the default sort order by name descending persists across reboots.
if i set it in the Global settings, it works, thenif i close A1111 (CTRL+C in terminal and close the browser) when i restart the sort order is back to Updated date ascending.
is there something i'm doing wrong?
i'm on Linux, any file to edit to change this for good?

Thanks for this great extension btw.

**Comment by zanllp** [comment]
> Hi there! i'm sorry but i can't set the default sort order by name descending persists across reboots. if i set it in the Global settings, it works, then if i close A1111 (CTRL+C in terminal and close the browser) when i restart the sort order is back to Updated date ascending. is there something i'm doing wrong? i'm on Linux, any file to edit to change this for good?
> 
> Thanks for this great extension btw.

@ali0une 
These settings are stored in the browser and are subject to cross-domain restrictions. If you open IIB with a link from a different domain or in incognito mode, these settings will be reset. Refer to https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by ali0une** [comment]
@zanllp many thanks! Didn't think about that as the site settings are set to be deleted in my Firefox.
