### ISSUE TITLE
Feature Request: include/exclude folders or specific file path in fuzzy search

### ISSUE THREAD

**Issue by paul-mcnamee** [zanllp/sd-webui-infinite-image-browsing#243]
First off, this plugin is great. I wanted to know if it was currently possible to confine the fuzzy search to a specified folder. I do not currently see a way to do this. I tried using the folder name with the search term in a variety of different ways but I don't know if the fuzzy search is including the path of the file as a part of the data it searches. This could be a simple fix to just include the file path in the search terms, or it would be nice to have a multi-select list of the folder sources to include/exclude.

Let me know if this exists, if not I can probably help add the functionality.

**Comment by zanllp** [comment]
It looks a bit like the search function in VSCode. It sounds good, but implementing this feature requires a lot of effort, and it doesn't seem like many people would use it. So, the priority for implementing it wouldn't be very high.

But PR welcome

<img width="411" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/b2c7de81-1074-47b3-896a-0899bac8cb27">

**Comment by paul-mcnamee** [comment]
Thanks for the response, I will take a look at the code and try to implement something when I have some more time in the coming weeks.
