### ISSUE TITLE
求助：请问发送到controlnet的功能有些情况下用不了

### ISSUE THREAD

**Issue by aomaoyyw** [zanllp/sd-webui-infinite-image-browsing#244]
之前一直挺好用的，最近几次更新后出现了如下的问题：
1、使用Chrome时，在新页面中打开的无边浏览器，无法发送到controlnet，且无提示；
但是在gradio中打开的无边浏览器可以。（chrome版本114.0.5735.134）
2、使用Firefox时，无论何种模式都无法发送到controlnet，且均无提示。（FF版本114.0.1）
能帮忙看下是什么原因吗？感谢你的插件，非常的棒

It used to be very easy to use, but after the last few updates, the following problems appeared:
1. When using Chrome, the infinite-image-browsing opened in a new page cannot execute the commands sent to the controlnet, and there is no error message; 
but the one opened in gradio can. (chrome version 114.0.5735.134)
3. When using Firefox, no matter what the mode is, it cannot be sent to the controlnet, and there is no error message. (FF version 114.0.1)
Can you help me find out why? Thanks for the plugin, it's great.

**Comment by zanllp** [comment]
什么版本的，感觉可能是gradio升级导致的，我这边没什么问题
<img width="1564" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/a573d85c-0e46-4149-a34a-faac78bf9331">

**Comment by aomaoyyw** [comment]
我的版本信息如下
ControlNet v1.1.224
version: [v1.3.2]  •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.19  •  gradio: 3.32.0  •  checkpoint: [a62b4ac3a2]
今天又用edge试了一下，症状和chrome一样，就是新开网页发送不过去，在gradio里能发送到controlnet。
也许就是Firefox哪里不兼容吧

**Comment by zanllp** [comment]
新页面中打开时确实无法发送这是正常的，我根本没实现这块的功能。
之前发送到图生图，文生图在新页面能用是其他人帮忙实现的，我暂时还没空，还有几个比较重要的功能实现后我看看

**Comment by aomaoyyw** [comment]
作者您好，今天用chrome浏览器使用发送到文生图和图生图的时候也出现了错误，症状是发送了某个特别的文件之后，其他所有的都发送不了了，刷新页面之后又可以正常使用；后台的提示如下：

> Traceback (most recent call last):
>   File "D:\stable diffusion\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
>     output = await app.get_blocks().process_api(
>   File "D:\stable diffusion\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
>     result = await self.call_function(
>   File "D:\stable diffusion\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1051, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "D:\stable diffusion\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "D:\stable diffusion\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "D:\stable diffusion\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "D:\stable diffusion\sd-webui-aki-v4\modules\generation_parameters_copypaste.py", line 379, in paste_func
>     v = key(params)
>   File "D:\stable diffusion\sd-webui-aki-v4\modules\generation_parameters_copypaste.py", line 414, in paste_settings
>     v = shared.opts.cast_value(setting_name, v)
>   File "D:\stable diffusion\sd-webui-aki-v4\modules\shared.py", line 692, in cast_value
>     value = expected_type(value)
> ValueError: invalid literal for int() with base 10: '0.75'
> 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
能帮忙看下是什么问题吗？

**Comment by zanllp** [comment]
我认为这不是我这的问题， 参考 https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/235

**Comment by aomaoyyw** [comment]
> 我认为这不是我这的问题， 参考 #235

是的 我也发现了

**Comment by zanllp** [comment]
controlnet那个我加上了，firefox搞了几个小时还是不太行，等大佬吧 #131
