### ISSUE TITLE
[Feature request] Fuzzy search with regular expressions

### ISSUE THREAD

**Issue by younyokel** [zanllp/sd-webui-infinite-image-browsing#247]
Request to add a button that enables regular expression like VS Code search, if it's possible
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/53343081/373a2122-0790-46f9-8b9f-fe1f312254d3)

**Comment by zanllp** [comment]
It looks promising. We'll definitely look into how we can implement it and keep you updated on our progress.

**Comment by zanllp** [comment]
Already added

**Comment by younyokel** [comment]
@zanllp 
It works, but when I'm trying to match "thing + hires upscaler" or something of two words, (like `kobold.*hires upscaler`, it shows blank or only one or two images. ImageBrowser does this correctly, maybe it's matching the metadata as a single line string without linebreaks?
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/53343081/fe5516e7-5c3e-4cfd-9fea-989552878b12)
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/53343081/f84544a4-e9ee-4fdf-9a45-14a3e2c77d25)

**Comment by zanllp** [comment]
Thank you for the reminder. I overlooked this point, but it has been fixed now. You can update to the latest version and give it another try.

**Comment by younyokel** [comment]
> Thank you for the reminder. I overlooked this point, but it has been fixed now. You can update to the latest version and give it another try.

Oh, great to hear! Works good now.

**Comment by younyokel** [comment]
Any way to exclude negative prompt though?

**Comment by zanllp** [comment]
`Negative prompt: (?!.*\bTARGET_WORLD\b).*$`
<img width="308" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/974a69ff-2f01-4266-a011-0a56e229a50c">

**Comment by younyokel** [comment]
Thanks. I mean to find a word in a  prompt but exclude the search for negative at the same time.

**Comment by zanllp** [comment]
Is it like the one below?
`detached_sleeves.+Negative prompt: (?!.*\bEasyNegative\b).*$`
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/0b24d86b-b663-4f41-8cd0-278dda08cfbe)
