### ISSUE TITLE
How do I get the extension to work without the interface on the colab version?

### ISSUE THREAD

**Issue by Loli-Kyn** [zanllp/sd-webui-infinite-image-browsing#250]
C did what was said in topic [#47](https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/47), but it didn't work. Can you tell me step by step what I should do?

![246688090-5b6bd52d-5526-4b1e-beba-1ce9c165cfe5](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/52761837/173c9df6-80a1-4842-ba5c-90375525a362)

**Comment by zanllp** [comment]
I feel like this person has already explained it well.


<img width="758" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/6aabb8fd-e9db-4fd1-afb2-064e81a435c8">

**Comment by zanllp** [comment]
You can refer to or directly use this.

https://github.com/Linaqruf/sd-notebook-collection/blob/main/Infinite_Image_Browsing_Demo.ipynb

**Comment by WSH032** [comment]
@Loli-Kyn
ok, let's continue from https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/47#issuecomment-1597908445

you said, 
> but it doesn't show my pictures.

I dont understand.

You mean colab dont display iframe? Or you mean `config.json` didn't work?
### For the first one, try this:
```python
from google.colab.output import serve_kernel_port_as_iframe, serve_kernel_port_as_window
from google.colab import output
from threading import Thread
import time

!git clone https://github.com/zanllp/sd-webui-infinite-image-browsing.git
%cd sd-webui-infinite-image-browsing
!pip install -r requirements.txt
output.clear()

port = 7888  # your port
config_file = "your_sd_webui_config_path"

def run_app():
    !python app.py --port={port}  # --sd_webui_config={config_file} # if you want

thread = Thread(target=run_app)
thread.start()
time.sleep(0.1)
# serve_kernel_port_as_window(port)  # it also work, use which one is up to you
serve_kernel_port_as_iframe(port)

# thread.join()  # if you want execute synchronously
```
It work good for me.

![M2K`OV@N{N64I{~A6$HM071](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/126865849/a557cb3b-a22c-4983-9dad-a2d6ef6cd7d3)

### For the second one
I dont konw how `cagliostro-colab-ui` work
So, i can't offer help
Sorry about that.

**Comment by Loli-Kyn** [comment]
@WSH032 
![Скриншот 20-06-2023 042450](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/52761837/3eed0a6d-5353-4fc8-b30b-d4bb59a81ebe)

**Comment by WSH032** [comment]
emm...
It seems like Colab's problem
I have encountered it once before, and restarting Colab may help

**Comment by zanllp** [comment]
> @WSH032 ![Скриншот 20-06-2023 042450](https://user-images.githubusercontent.com/52761837/246981031-3eed0a6d-5353-4fc8-b30b-d4bb59a81ebe.jpg)
<img width="448" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/c03a5053-0bef-48c4-b5d9-2f9ef42c9fef">
Have you replaced this with the actual configuration file path?

**Comment by Loli-Kyn** [comment]
@WSH032 Should I try changing the colab(diffusion) and check?

**Comment by WSH032** [comment]
No, you don't need to change anything, just try again.

https://github.com/zanllp/sd-webui-infinite-image-browsing/pull/261

```python
# install
from google.colab.output import serve_kernel_port_as_iframe, serve_kernel_port_as_window
from google.colab import output
import sys
import os

!git clone https://github.com/zanllp/sd-webui-infinite-image-browsing.git
%cd sd-webui-infinite-image-browsing
!pip install -r requirements.txt
sys.path.append( os.getcwd() )
output.clear()

```
```python
# launch
import app  # after pip

port = 9998  # change by yourself # your port
extra_paths = [ "your_extra_paths" ] # change by yourself # type: List[str]
sd_webui_config = "your_sd_webui_config_path"  # change by yourself
update_image_index = True  # change by yourself

serve_kernel_port_as_iframe(port)

await app.async_launch_app(
    port = port,
    extra_paths = extra_paths,
    update_image_index = update_image_index,
    sd_webui_config = sd_webui_config,
)

```
![84AAN13%YZ6@$B9E 4_F)XR](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/126865849/c3f4ab39-2d86-441d-8c5e-3184648af3c8)

---

by the way, may be you should need to change the extension name, because Colab prohibits running code with webui characters

**Comment by Loli-Kyn** [comment]
@WSH032 I still don't understand...

**Comment by steinhaug** [comment]
Could someone bother to set up a jupyther notebook example? I have an updated Colab noptebook using your script here. Right now this is not very fast thats for sure.

[![Open in Colab](https://img.shields.io/badge/StableDiffusionWEBUI--Automatic-OpenInColab-blue?logo=googlecolab)](https://colab.research.google.com/github/steinhaug/stable-diffusion/blob/main/KISTA_WebUI_Colab.ipynb?v1.5)

I'll try your examples and see what happends.

**Comment by steinhaug** [comment]
> You can refer to or directly use this.
> 
> https://github.com/Linaqruf/sd-notebook-collection/blob/main/Infinite_Image_Browsing_Demo.ipynb

I have tried this one, however I have a question. Is this supposed to buffer or preload any data, to me it loads very slow and does not buffer / cache any data it seems. So each time I reenter a folder, all images / thumbs needs to be recalculated ? Is this correct?

**Comment by zanllp** [comment]
> I have tried this one, however I have a question. Is this supposed to buffer or preload any data, to me it loads very slow and does not buffer / cache any data it seems. So each time I reenter a folder, all images / thumbs needs to be recalculated ? Is this correct?

By default, IIB will compress images into 512x512 webp format and save them in the system's temporary folder. For example, a 1024x1024 PNG image that is about 1MB in size will be compressed to around 30KB. This is typically very beneficial. However, for platforms like Colab where a different machine may be allocated each time you start, you may need to regenerate the cache each time. You can choose to turn off thumbnail previews or save the cache folder to restore it for future use.
