### ISSUE TITLE
Help: Standalone Operation By Gradio | 求助 ：关于独立运行迁移至Gradio 

### ISSUE THREAD

**Issue by WSH032** [zanllp/sd-webui-infinite-image-browsing#251]
作者你好
我正在尝试将独立运行的启动部分从uvicorn迁移至gradio
我英文不是很好，我就直接用中文和你交流把。

我已经取得了一定的进展，但我仍想和你确认下，我是不是错过了什么部分。
![ST~}Q)Z XEOK4K_{I V~DXA](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/126865849/646ce358-ce7d-461f-a969-d618f0ceade9)

---

我不了解关于FastAPI、JS用法和SD-WebUI的具体运行方式
我只知道gradio的用法

我想问下，这个项目做为SD-WebUI的插件运行时，逻辑是这样的吗？
1. 启动FastAPI做为后端
2. 在WebUI中注册发送按钮并隐藏
3. WebUI渲染后通过`javascript/index.js`替换gr.HTML组件的显示内容
4. WebUI前端的交互均通过`javascript/index.js`完成？
5. 在涉及到前端点击发送时，通过`javascript/index.js`模拟点击被隐藏的按钮

全部的流程是这样吗？我是不是漏了什么？

---

顺便问下，你了解SD-WebUI的运行方式吗
主要是关于在SD-WebUI中执行`script_callbacks.on_app_started(infinite_image_browsing_api)`后对gradio-app的修改

**Comment by WSH032** [comment]
> 不过搞这个干嘛，特意再套上一层

我想把你的项目和[stable-diffusion-webui-dataset-tag-editor](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor)和[image-deduplicate-cluster-webui](https://github.com/WSH032/image-deduplicate-cluster-webui)整合起来，做为一个独立于SD-WebUI运行（因为我打算支持在Colab中使用）的图片训练集制作的项目

我计划用Gradio进行整合，因为很多SD-WebUI扩展都是以gradio方式编写的，我可以很方便地进行整合。
而且Gradio对Colab的支持不错

---

>顺便问下，你了解SD-WebUI的运行方式吗
>主要是关于在SD-WebUI中执行script_callbacks.on_app_started(infinite_image_browsing_api)后对gradio-app的修改

我主要的疑惑是，SD-WebUI中这个函数似乎是会把SD-WebUI运行时的`gradio-app: fastapi.FastAPI`传给你的`infinite_image_browsing_api`进行操作，这种对`gradio-app`的修改不会有什么隐患吗？
我注意到SD-WebUI在执行完这个后，还进行了一系列对`gradio-app`的修改，不知道是不是为了消除隐患

我的实现中并没有进一步进行一系列的修改，不过仍然能正常运行。

**Comment by zanllp** [comment]
不用担心 infinite_image_browsing_api 根本没用到gradio-app

**Comment by zanllp** [comment]
你是不是认为在担心视图刷新后图像浏览器的挂载用的容器会重新创建dom，导致图像浏览器的界面消失，目前看来好像不会

**Comment by zanllp** [comment]
这个我认为基本不会

**Comment by WSH032** [comment]
好的，我基本没什么问题了。感谢你的帮助。:smile:

将关闭，如果有新的问题我再重新打开

---

最后问下，我可以引用这个项目吗（就是我上面说的整合）？

**Comment by WSH032** [comment]
好的，再次感谢
