### ISSUE TITLE
Upgrading to new commits within A1111 causes extension to fail

### ISSUE THREAD

**Issue by bobpuffer1** [zanllp/sd-webui-infinite-image-browsing#253]
Restarted stable diffusion.
Restarted GUI
Failed to load
Refreshed the page
Still fails to load

On MBP M2 Max

**Comment by zanllp** [comment]
You can  update the extension and try again.

**Comment by bobpuffer1** [comment]
Select several files from search results
Drag and drop them to my folder on Finder
I get this text snippet in finder... nothing else
{"includeDir":false,"loc":"search-result","path":["/Users/bobpuffer/stable-diffusion-webui/outputs/txt2img-images/2023-06-17/00114-4167484829.png","/Users/bobpuffer/stable-diffusion-webui/outputs/txt2img-images/2023-06-17/00184-3895176330.png","/Users/bobpuffer/stable-diffusion-webui/outputs/txt2img-images/2023-06-17/00181-3895176327.png","/Users/bobpuffer/stable-diffusion-webui/outputs/txt2img-images/2023-06-17/00118-4167484833.png"]}

I still get an error when I try to open with local file browser

**Comment by zanllp** [comment]
Is your operation consistent with the screen recording below? If there are other errors, please take a screenshot and paste it to have a look.


https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/51e3cf47-fff2-4f38-a3de-8371aa03f647

**Comment by zanllp** [comment]
It's good now. Please update the extension and try again. It works fine on my MBP.

**Comment by bobpuffer1** [comment]
Yes, seems to work well

**Comment by bobpuffer1** [comment]
This has been resolved
