### ISSUE TITLE
Plugins often do not display during use

### ISSUE THREAD

**Issue by mayjack0312** [zanllp/sd-webui-infinite-image-browsing#257]
The version I am using:
version: [v1.3.2]
•  python: 3.10.6
•  torch: 2.0.0+cu118
•  xformers: 0.0.21.dev542
•  gradio: 3.31.0

Do not display this plugin when frequently starting or refreshing

**Comment by zanllp** [comment]
A bit of a strange issue, but I tried it a few times and it seemed to be working fine. Could you try updating the plugin and giving it a few more tries? It might have been a previous bug.
