### ISSUE TITLE
Suggest adding batch processing function

### ISSUE THREAD

**Issue by mayjack0312** [zanllp/sd-webui-infinite-image-browsing#258]
The versions used are as follows:

Extend | URL |  | Branch | Date | Update
-- | -- | -- | -- | -- | --
sd-webui-infinite-image-browsing | https://github.com/zanllp/sd-webui-infinite-image-browsing | main | 55d154e3 | Sat Jun 3 16:20:49 2023 | unknown

Suggest adding features:
Multiple images can be selected simultaneously for deletion and other functions

**Comment by zanllp** [comment]
This feature is certainly supported.

<img width="741" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/97eb9dfa-2359-4d75-bb2a-5d1989060bc8">

You can click on the link below to see my screen recording.



https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/253#issuecomment-1599197676

**Comment by mayjack0312** [comment]
> This feature is certainly supported.
> 
> <img alt="image" width="741" src="https://user-images.githubusercontent.com/25872019/247224612-97eb9dfa-2359-4d75-bb2a-5d1989060bc8.png">
> You can click on the link below to see my screen recording.
> 
> [#253 (comment)](https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/253#issuecomment-1599197676)

Okay, thank you. I'm very sorry I didn't see this one before. I'll give it a try
