### ISSUE TITLE
[Feature request] Path format，Quickly move，Adjusting thumbnail size | 调整路径字符，更方便的切换路径，灵活调整缩略图

### ISSUE THREAD

**Issue by WSH032** [zanllp/sd-webui-infinite-image-browsing#259]
## 在某些情况下，我需要在多个选项卡之间，频繁的复制路径
![Y1I~ M()NKEIUC3687W$L0P](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/126865849/fe193f85-f262-4bab-896b-f46b87155737)
![E@MT~21OHB7 EUL19(TEVB3](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/126865849/959192e3-8a03-49f4-8cbd-3e2b69b579aa)

但目前图库浏览器显示的地址是不能直接复制来使用的，我必须对其进行修改
```diff
- 根/D盘/BA画风训练集/_6_blue_archive style
+ D:/BA画风训练集/_6_blue_archive style
```

我觉得可以把显示的路径字符统一换成标准的路径的形式？

---
## `前往`功能被藏的太深了

![RKOU}0$ZD5D6V7)}E@@0UEP](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/126865849/7af8944d-e22a-4412-9d68-217b19b49598)

通常情况，我并不将图库浏览器做为SD-WebUI的插件使用，我更多是在将它做为文件管理器使用

有时候我需要频繁的切换地址，每次都要点击`更多`才能使用`前往`

能把它移到最前吗
![ZN8@0CBMEHM9`{5`C(XSN2C](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/126865849/ae52ca66-57f7-4b47-b4a1-59eae73f83e9)

---

## 有办法能灵活调整显示缩略图的大小吗，我希望能显示更多图片
![H$1_QC3ME56YNH3_ZUBV99F](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/126865849/95897f5c-4089-478a-be7a-1fa37f541240)

**Comment by zanllp** [comment]
我不是提供了复制路径吗

<img width="581" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/a9230f72-e90f-45fa-acac-95eb9d0a31e8">

**Comment by zanllp** [comment]
现在有很大的一个问题就是有很多功能我已经实现了，但是他们根本就不知道这个功能存在，我正在着力处理这个问题
就例如很重要 多选删除/移动，我在非常早期的版本就已经实现了，但是起码不下五个人跑来提feature request

**Comment by zanllp** [comment]
> 有办法能灵活调整显示缩略图的大小吗，我希望能显示更多图片


没有，暂时只提供256和512，后面考虑多增加几个选项，或者自定义。设计时感觉mbp的屏幕已经够小了，5个已经够用了

<img width="1511" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/58ea53d2-a809-4126-b85a-e0c76c220624">

**Comment by WSH032** [comment]
> 我不是提供了复制路径吗
我觉得还是比较麻烦，像 `复制路径` , `前往` , `本地打开` 这种占用显示很小，而且使用频率很高的选项，都可以放在最前端，让它们和 `刷新` 在一起

可能在window下觉得没啥，但是在Colab这种运行上linux上的，没有GUI界面的环境，如果你能尽可能模仿window资源管理器的交互，是非常有用的

---

>现在有很大的一个问题就是有很多功能我已经实现了，但是他们根本就不知道这个功能存在，我正在着力处理这个问题
就例如很重要 多选删除/移动，我在非常早期的版本就已经实现了，但是起码不下五个人跑来提feature request

你的插件用起来太方便了，门槛很低，所以你应该默认用户是不会去看文档的，更多的是通过前端到处乱点来尝试交互，从而发现相应功能

对于一些不好通过交互发现的功能，可以考虑在前端直接显示使用提示Tips

---

> 没有，暂时只提供256和512，后面考虑多增加几个选项，或者自定义。设计时感觉mbp的屏幕已经够小了，5个已经够用了

我这边笔记本只能显示4个每行

我觉得不应该按像素点来确定缩略图大小，应该按个数来确定显示大小

Gradio的Gallery组件是可以很方便的根据整数参数来控制每行显示图片的数量

我不了解Vue，我不知道在Vue下实现起来的难度怎么样

**Comment by zanllp** [comment]
> 不能让像 D盘 这样的中文显示，改成 D: 吗，先不考虑分割符号是 \ 的问题

当然可以，纯粹是不好看才使用现在这样

> 我觉得还是比较麻烦，像 复制路径 , 前往 , 本地打开 这种占用显示很小，而且使用频率很高的选项，都可以放在最前端，让它们和 刷新 在一起

我正在搞一个功能，如果路径栏有多余位置那就直接显示，没有的话再塞到更多里面


> Gradio的Gallery组件是可以很方便的根据整数参数来控制每行显示图片的数量, 我不了解Vue，我不知道在Vue下实现起来的难度怎么样

前端这边的实现还挺复杂的，是一个无限滚动的虚拟列表，很多类似我们常用的media query都不能用，这些尺寸都实时计算的，但也不是不能做。
使用按个数来确定显示大小。会带来一个问题，这个插件的布局控制是完全参考的vscode，如果是左右分屏的话这种情况怎么处理，如果在左右分屏时使用在单tab下的图片大小那样又会回到之前方案

**Comment by zanllp** [comment]
我改进了下路径栏，现在体验应该好一些

**Comment by xyzDist** [comment]
> 

for the 

> > 有办法能灵活调整显示缩略图的大小吗，我希望能显示更多图片
> 
> 没有，暂时只提供256和512，后面考虑多增加几个选项，或者自定义。设计时感觉mbp的屏幕已经够小了，5个已经够用了
> 
> <img alt="image" width="1511" src="https://user-images.githubusercontent.com/25872019/247383218-58ea53d2-a809-4126-b85a-e0c76c220624.png">

really looking forward for the user free to definite the thumbnail size!!

**Comment by WSH032** [comment]
> 我改进了下路径栏，现在体验应该好一些

awesome，现在在colab里用起来很方便了

**Comment by zanllp** [comment]
@WSH032 @xyzDist   加上了，already  added 
见 https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/131

**Comment by WSH032** [comment]
nice，十分感谢😃

**Comment by Raivshard** [comment]
The minimum image size way too large. It is extremely annoying for those of us who have to use larger scaling sizes in Windows.

**Comment by zanllp** [comment]
> The minimum image size way too large. It is extremely annoying for those of us who have to use larger scaling sizes in Windows.

The allowed range for image size is from 64px to 1024px, so why do you think it is too large?

<img width="1917" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/96f6a14f-e6cb-4142-8a15-db12926ec2cc">

**Comment by Raivshard** [comment]
Ah, whoops, that comment was sitting there in a tab for two weeks because I forgot to hit "comment". I noticed the tab, hit it, and then forgot about it again. Just switched everything back on today. Sorry for the confusion. 

And thanks for the update! Awesome extension.
