### ISSUE TITLE
The .env is confusing

### ISSUE THREAD

**Issue by girllover2154** [zanllp/sd-webui-infinite-image-browsing#260]
The fact this makes the "--administrator" command absolutely useless when browsing folder, and the fact that the whole .env thing is confusing as hell, makes the need to have this a terrible idea.

**Comment by zanllp** [comment]
I'm not sure what this option does, it doesn't seem to be used at all in the v1.40-rc version of sd-webui.

<img width="419" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/1e8b8176-e7ad-4469-ad19-80e90c6608d5">
