### ISSUE TITLE
[Feature request] Standalone support for config.json using relative paths

### ISSUE THREAD

**Issue by WSH032** [zanllp/sd-webui-infinite-image-browsing#262]
# 希望独立运行模式支持config.json采用相对路径

我觉得config.json的生成方法大概就两种，一种是这个config.json由A1111的SD-WebUI创建，一种是由采用独立运行的用户手动创建

当config.json内使用了相对路径

 - 对于第一种情况，config.json就位于SD-WebUI的根目录，所以扩展为绝对路径的时候，不应该用getcwd()来填充，应该用config.json所在的文件夹位置来填充
 - 对于第二种情况，config.json可以位于任意位置，但我想，既然它采取了相对路径，就应该更倾向认为相对位置是对于config.json而言的，所以也应该采用与第一种情况相同的处理方式
 
或许可以做一个折中，先使用config.json所在的位置扩展为绝对路径，找不到，再使用getcwd()扩展？

---

目前的情况是，我按上述想法修改了`get_valid_img_dirs()`和`paths_check()`中`abs_path = os.path.join(rel_path_prefix, path)`

更新索引功能确实能可以正常运行，但是`从快速移动启动`中不会显示相应的如`文生图`等的选项

我无法找到你是如何判断 `文生图` 路径被正确指定并显示相应选项

**Comment by zanllp** [comment]
前端接收的是这个。
<img width="690" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/0040367e-3783-4358-98ad-10e9ded44528">


你想搞的话，不要隐式转换
```py
parser.add_argument("--sd_webui_path_relative_to_config", action="store_true", help="Use the file path of the sd_webui_config file as the base for all relative paths provided within the sd_webui_config file.")
```

可以通过kwargs传入或者全局变量，然后在函数里面替换

**Comment by zanllp** [comment]
我加上了  `--sd_webui_path_relative_to_config`

**Comment by WSH032** [comment]
> 我加上了 `--sd_webui_path_relative_to_config`

nice，我本来想周末再研究下这个的，感谢这个功能
