### ISSUE TITLE
[Feature request] Filename display while previewing images

### ISSUE THREAD

**Issue by peterAIML** [zanllp/sd-webui-infinite-image-browsing#269]
Great extension! Thanks for your awesome work.

Would it be possible to display the filename while using the preview mode for browsing? Right now the filename is not displayed. Which can be confusing to identify the right image when browsing lots of similar looking images in the preview mode.

![infinite](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/113024619/3fedd1d9-752d-492c-9ca0-8e7c0af5d99c)

Displaying the filename above where the prompt is displayed or together with the generation data (Steps, Sampler, CFG Scale, etc) would be super useful.

**Comment by zanllp** [comment]
already added
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/a0e75817-2d4c-4e4b-a6ab-387ff5d603ac)

**Comment by peterAIML** [comment]
Awesome! That was fast. Thank you so much.
