### ISSUE TITLE
无法使用收藏功能

### ISSUE THREAD

**Issue by sakura2333** [zanllp/sd-webui-infinite-image-browsing#274]
使用收藏（星标）提示需要index，感觉是权限问题
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/27041052/cd171a55-aac0-4966-bf21-5984506bc4cc)
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/27041052/984eabc9-5ed5-4cf6-bd2e-7b04bedaa23c)
按照提示，加上了访问密码（不知道这步操作对不对）
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/27041052/d4a31123-43ee-4825-9003-21f3a4bacc30)
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/27041052/ac018f08-f1bd-4159-ba9a-02bb01283825)

环境是内网的ubuntu 22.04 LTS server
访问浏览器的是macbook edge浏览器
加完密码之后 每一步操作都需要密码 然后所有页面都是空了
很奇怪的是  没有加密码之前访问是正常的

**Comment by zanllp** [comment]
访问控制是这个，IIB_ACCESS_CONTROL=disable 就行了
<img width="802" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/b818cd4f-af30-48e0-98f7-891f5fc73076">

**Comment by zanllp** [comment]
> 加完密码之后 每一步操作都需要密码 然后所有页面都是空了
你是不是开了无痕浏览，或者拒绝我的cookie设置之类的，你可以换成chrome试试

**Comment by zanllp** [comment]
你这是怎么运行的，独立模式还是作为插件运行的？，不应该什么都看不到

**Comment by sakura2333** [comment]
> 你这是怎么运行的，独立模式还是作为插件运行的？，不应该什么都看不到

是插件模式   好像是开了密码验证就会什么都看不到   

是我开始想多了，不加密码，把access_control关了确实访问控制的提示没了
但是好像不会自动index，有办法手动触发吗

**Comment by zanllp** [comment]
你访问的图像应该不在sd_webui提供的文件夹内吧。对于sd_webui外部的图像默认是不建立索引的，手动添加一下就行了

<img width="727" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/ff3eaa3f-1826-43c0-b38c-cfee40485686">

**Comment by sakura2333** [comment]
啊啊啊啊  太糗了   是我看的不仔细 一开始没找到那个按钮  抱歉耽误那么多时间

**Comment by zanllp** [comment]
好像有点问题

**Comment by zanllp** [comment]
修好了，你可以更新下试试。顺便改进了下提示

**Comment by sakura2333** [comment]
> 

我试了一下  git pull
修改env需要密码
重启webui
浏览器操作：开发者模式 清空浏览器缓存并硬刷新  检查完没有cookie
默认的空启动页  右边的最近部分也能列出我的路径
但是每一步都需要操作密码   
而且好像切换到别的tab页再回到sd的tab页也会导致弹出2次密码验证
并且所有目录文件夹还是显示为空

**Comment by sakura2333** [comment]
> 修好了，你可以更新下试试。顺便改进了下提示

我试了一下  git pull
修改env需要密码
重启webui
浏览器操作：开发者模式 清空浏览器缓存并硬刷新  检查完没有cookie
默认的空启动页  右边的最近部分也能列出我的路径
但是每一步都需要操作密码   
而且好像切换到别的tab页再回到sd的tab页也会导致弹出2次密码验证
并且所有目录文件夹还是显示为空

**Comment by zanllp** [comment]
你使用什么链接去访问的？发出来看看（如果是公开的随机替换掉几个字母）

换个浏览器试试？

应该是cookie IIB_S没有设置成功，每次访问时都会检查cookie里面有没有IIB_S，没有就401弹窗了

**Comment by zanllp** [comment]
> 你使用什么链接去访问的？发出来看看（如果是公开的随机替换掉几个字母）
> 
> 换个浏览器试试？
> 
> 应该是cookie IIB_S没有设置成功，每次访问时都会检查cookie里面有没有IIB_S，没有就401弹窗了

我用gradio的--share在chrome下没什么问题，我感觉可能是被浏览器或者是什么网关阻止了
<img width="1154" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/944b792b-a6ea-47f8-9eae-61e8dcbb6f6d">

**Comment by sakura2333** [comment]
> > 你使用什么链接去访问的？发出来看看（如果是公开的随机替换掉几个字母）
> > 换个浏览器试试？
> > 应该是cookie IIB_S没有设置成功，每次访问时都会检查cookie里面有没有IIB_S，没有就401弹窗了
> 
> 我用gradio的--share在chrome下没什么问题，我感觉可能是被浏览器或者是什么网关阻止了
我换成了chrome  会不会是最后那个图的问题
 <img alt="image" width="1154" src="https://user-images.githubusercontent.com/25872019/249376957-944b792b-a6ea-47f8-9eae-61e8dcbb6f6d.png">

<img width="634" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/27041052/33f86db1-9a8a-40aa-acc9-e5ce53730378">
<img width="652" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/27041052/93699a78-e046-4f1d-9f0b-62f45ef9c6ec">
<img width="804" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/27041052/536562ff-4792-475c-a38f-66fc9fab2268">

**Comment by zanllp** [comment]
emmmm,你这个链接属于是不安全上下文，加密算法用不了，我看能不能搞下兼容

**Comment by sakura2333** [comment]
> emmmm,你这个链接属于是不安全上下文，加密算法用不了，我看能不能搞下兼容

<img width="597" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/27041052/d36dde33-b557-43eb-82c4-b8ca22dcd4da">
额  是因为我没有https么

**Comment by zanllp** [comment]
是的，没https也不是127.0.0.1，我换个加密库应该就能解决

**Comment by sakura2333** [comment]
> 是的，没https也不是127.0.0.1，我换个加密库应该就能解决

感谢解惑

**Comment by zanllp** [comment]
更新下，应该可以了

最近功能加的太多，很多边缘case都来不及测试

**Comment by sakura2333** [comment]
> 更新下，应该可以了
> 
> 最近功能加的太多，很多边缘case都来不及测试

可以了！！ 大佬给力
