### ISSUE TITLE
这个插件我电脑一连上网（wifi）就特别慢

### ISSUE THREAD

**Issue by Light555555** [zanllp/sd-webui-infinite-image-browsing#282]
不知为何，这个插件我电脑一连上网就特别慢，walk模式要好半天才出来，但是把网断了就秒出
![Quicker_20230628_220027](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/138024036/e96858c7-0840-47eb-98b8-787d8beebbc1)

**Comment by Light555555** [comment]
其他模式也是如此，要先显示个“本地”文件夹，好几十秒才能读出来

**Comment by zanllp** [comment]
通过什么链接访问的？  开控制台截图看下

<img width="1250" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/fc1b2c04-2908-4638-ae3f-32f63b268ba3">

**Comment by zanllp** [comment]
是通过什么链接访问的，都是127.0.0.1?

**Comment by Light555555** [comment]
是的，就，大大的插件是巨好用的一个插件，但是不知道为什么会这样，要不我重启下我的网络试试？
![微信截图_20230628230713](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/138024036/887847c5-17e2-488b-a4bf-2b0df2230840)

**Comment by zanllp** [comment]
可以重启下试试，我也没什么头绪，我以前遇到这种问题都是自己不小心开启限速来测试弱网然后忘记关造成的。


要不然你可以试试使用独立模式会不会出现这个问题?  

```bash
cd extensions\sd-webui-infinite-image-browsing # 移到到插件repo的根目录下
git pull # 更新到最新版
python app.py --sd_webui_config="YOUR_SD_WEBUI_PATH\config.json"  --sd_webui_path_relative_to_config
```

**Comment by Light555555** [comment]
计算机完全重启了，网络也重启了，浏览器插件也全部关了，还是不行，这次打开甚至需要1分多钟，完全不知道为啥

**Comment by zanllp** [comment]
其他遇到系统问题的参考 
<img width="467" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/c831c497-b683-409b-a054-b23d13e3800c">
