### ISSUE TITLE
File explorer closes after being opened through "Open with Local File Browser"

### ISSUE THREAD

**Issue by Deiwulf** [zanllp/sd-webui-infinite-image-browsing#290]
Title. It's just so bizarre, no information, no warnings, no errors, nothing. Just closes casually by itself after 3-5 seconds. Meanwhile, all's fine going there manually ¯\_(ツ)_/¯

**Comment by zanllp** [comment]
Could you please provide more information about the issue you're experiencing? In particular, it would be helpful to know your system and extension versions.

**Comment by Deiwulf** [comment]
Sure.
Win 10.0.19045 Build 19045
Firefox 115.0b9 (64-bit)
Extension version [56b9c1d4](https://github.com/zanllp/sd-webui-infinite-image-browsing/commit/56b9c1d49c5c538606bc0acac63b35ea724362f1)
And as SD goes: version: [v1.4.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/394ffa7b0a7fff3ec484bcd084e673a8b301ccc8)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0

**Comment by zanllp** [comment]
It does seem quite strange as we haven't received any similar reports before. I have tested it on Windows 10 version 19045 and Firefox, and I didn't encounter any issues. Could you please try restarting your computer and see if that resolves the issue?

**Comment by Deiwulf** [comment]
Still the same, but after some fiddling around I found the culprit: Tagging for Windows. Uninstalled it, and all's fine. So random -_-
Can close.
