### ISSUE TITLE
Generation Information Panel Out of Screen

### ISSUE THREAD

**Issue by pto2k** [zanllp/sd-webui-infinite-image-browsing#295]
Not sure what is the reason (maybe usage of Kitchen UI or dual-monitor), the generation info panel became missing when I view an image in IIB. 

Later I found that it is there but just out of view. 

I zoomed out the web page to 75% and it came into view. I dragged it close to center and it is all good again.

**Comment by zanllp** [comment]
It's strange that the generation info panel can be dragged out of view. I'll add a check to reset the panel's position if it goes out of bounds. 

In case this happens again, you can follow the steps in the attached image to delete the stored value and refresh the page to reset the panel.
<img width="1032" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/5fe8bdb2-385c-4cbd-ac75-d099477cdcc4">

**Comment by zanllp** [comment]
Already added
