### ISSUE TITLE
全局设置里的“网格宽度”设置无效

### ISSUE THREAD

**Issue by catshitz** [zanllp/sd-webui-infinite-image-browsing#297]
不论设置多少根本不会改变

**Comment by zanllp** [comment]
那是设置里面缩略图的分辨率宽度，调高了后你有没有发现清晰了点
网格大小还在实现

**Comment by zanllp** [comment]
加上了 见 https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/131

**Comment by catshitz** [comment]
> 加上了 见 #131

确实可以了，感谢！
