### ISSUE TITLE
有个小小的请求，关于主题

### ISSUE THREAD

**Issue by joindn** [zanllp/sd-webui-infinite-image-browsing#299]
能不能跟随系统主题，其他插件都跟随系统主题的，[其他插件](https://7b5635fd.pek3b.qingstor.com/12.png),
[咱们这个插件](https://7b5635fd.pek3b.qingstor.com/2.png)
我这是装了这个主题
https://github.com/catppuccin/stable-diffusion-webui.git

**Comment by zanllp** [comment]
没问题啊，只要你url里面没包含__theme就是使用的系统的
https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/e1e20f6f-4c89-4c75-9bc1-2dbbc52c3105

**Comment by joindn** [comment]
我可能没说清楚，应该不是系统的，是https://github.com/catppuccin/stable-diffusion-webui.git 这个插件会给全局设置各种样式，但是咱们这个插件不会跟着变，其他的插件都会，[比如我可以改成绿色的主题你看连接](https://7b5635fd.pek3b.qingstor.com/111.png)

**Comment by zanllp** [comment]
那就不可能了，他那个应该是通过增加规则来覆盖gradio的样式，这个插件并不是gradio实现的，所以没效果很正常

而且我还特意花了很大功夫来做个防止污染
