### ISSUE TITLE
Keyboard navigation always triggers "Are you sure you want to delete?"

### ISSUE THREAD

**Issue by theDanielJLewis** [zanllp/sd-webui-infinite-image-browsing#301]
I don't know what version started this, but trying to use the keyboard to navigate the images, or even pressing Escape to exit the larger view, now tries to delete the image.

On the first image, it says, "Due to technical limitations, the first image cannot be deleted when opening the fullscreen preview."

All other images after that say, "Are you sure you want to delete?" with a prompt that layers over more of the same prompts.

**Comment by zanllp** [comment]
Try upgrading to the latest version and see if the issue is resolved.
