### ISSUE TITLE
Bug: "send to ..." functions needs to send .txt files

### ISSUE THREAD

**Issue by steinhaug** [zanllp/sd-webui-infinite-image-browsing#303]
When using the "save_txt" feature, that is creating a seperate txt file together with the image file containing generation data, this file is not taken into considerations when moving images.

I would argue that when moving an image, say "send to saved folder" as an example. Then when sending the image, one should also check if there is a .txt file with the same name and if so move that one aswell as it belongs to the image. Atleast this is my understanding.

Say image is called **0001-1000.jpg**, the **0001-1000.txt** file typically contains:

```
the_prompt_text
Negative prompt: the_negative_prompt_text
Steps: 20, Sampler: DDIM, CFG scale: 7, Seed: 1276181096, Size: 512x768, Model hash: 5493A0EC49, Model: abyssorangemix3AOM3_aom3a1b
```

**Comment by zanllp** [comment]
Is your extension the latest version? I remember this issue was already resolved a long time ago.

**Comment by steinhaug** [comment]
OOOPS! Sorry for this, just updated the extension and I see this is fixed. Close this one.
