### ISSUE TITLE
Feature Request - LyCORIS support

### ISSUE THREAD

**Issue by skynetua** [zanllp/sd-webui-infinite-image-browsing#305]
Could you please add Lora's Lycoris type to tags list. 
https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

**Comment by skynetua** [comment]
It is the same as Lora, the only difference is prefix `<lyco:`

<img width="765" alt="Screenshot 2023-07-11 at 23 14 26" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/3670941/c6f64de1-721b-4a9e-a8a3-9123a74d9384">

**Comment by zanllp** [comment]
already supported
![XR11935Y71XP@ZE2$O(9`RV](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/7838c278-a941-4372-8476-6e3a96c7ce10)

**Comment by skynetua** [comment]
Thanks
