### ISSUE TITLE
Allow to serve only the "save" folder

### ISSUE THREAD

**Issue by djmaze** [zanllp/sd-webui-infinite-image-browsing#310]
I think I do not understand the "access control" feature. Is there a way to limit access e.g. only to the `save` folder?

**Comment by zanllp** [comment]
I have created a diagram that may help you understand the purpose of the access control feature. Additionally, if you would like to limit access to only the "save" folder, I can add an environment variable `IIB_ACCESS_CONTROL_ALLOW=save,extra` to accomplish this.

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/aa4cab3f-ce18-4ba8-9d8b-d602f9c211dc)

**Comment by djmaze** [comment]
Oh, nice, thanks! Yes, a "save only" feature would be really helpful from a data protection standpoint.

**Comment by gilbertgong** [comment]
sorry for piggybacking on this issue, but one thing I noticed is that while you can't see files in the "disabled" section, it does appear you can see the directory structure.  Is this intended?  I would suggest it would be preferable to make the directory structure also not visible.

**Comment by gilbertgong** [comment]
Is `IIB_ACCESS_CONTROL=enabled` supposed to function in standalone mode?

I'm running with standalone mode, a config.json containing only `{}`, and `IIB_ACCESS_CONTROL=enabled` set in .env file, and it seems to allow viewing the entire directory structure from `/` down as well as any and all images.

**Comment by zanllp** [comment]
> I'm running with standalone mode, a config.json containing only `{}`, and `IIB_ACCESS_CONTROL=enabled` set in .env file, and it seems to allow viewing the entire directory structure from `/` down as well as any and all images.

It seems like a typo.
```diff
- IIB_ACCESS_CONTROL=enabled
+ IIB_ACCESS_CONTROL=enable
```

**Comment by gilbertgong** [comment]
Oh, thank you so much.  Sorry - my foolish mistake..

**Comment by zanllp** [comment]
This feature is already supported. I also support permission control of IIB. You can refer to the code below to make IIB only allow access to the "save" folder and in read-only mode:

```env
IIB_ACCESS_CONTROL=enable
IIB_ACCESS_CONTROL_ALLOWED_PATHS=save
IIB_ACCESS_CONTROL_PERMISSION=read-only
```

For more details, please refer to (https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/.env.example.
