### ISSUE TITLE
Bug? : Untranslated tab name/未翻译的标签页名称？

### ISSUE THREAD

**Issue by Edge-GH** [zanllp/sd-webui-infinite-image-browsing#312]
The tab displays as '无边图像浏览', even though I have set the language to English in the global settings.
我已经在全局设置中将语言改为英语了，但是标签页仍然是【无边图像浏览】。

<img width="1038" alt="untranslated part" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/116174645/1bcbb97b-097c-4012-8681-dd8f7305593c">

**Comment by zanllp** [comment]
用这个
<img width="894" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/d519c686-c78b-4e4e-92b2-5ebcf5bf454b">

**Comment by Edge-GH** [comment]
感谢，问题解决了
