### ISSUE TITLE
【功能请求】可否直接在信息栏里显示已打过的标签

### ISSUE THREAD

**Issue by 350640267** [zanllp/sd-webui-infinite-image-browsing#317]
可否直接在信息栏里显示已打过的标签，比如【like】等等，这样会比较直观看到作品有没有收藏或者加了其他标签

**Comment by zanllp** [comment]
这个已经在做了，网格视图的话后面会显示在图片右下角，就像这样。  
<img width="230" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/60cbc7f3-60ff-474e-bfc3-57bb57a4eac3">


只不过一次性要查询的量比较大，需要花点时间来优化性能

**Comment by 350640267** [comment]
> 这个已经在做了，网格视图的话后面会显示在图片右下角，就像这样。 <img alt="image" width="230" src="https://user-images.githubusercontent.com/25872019/253882668-60cbc7f3-60ff-474e-bfc3-57bb57a4eac3.png">
> 
> 只不过一次性要查询的量比较大，需要花点时间来优化性能

感谢大佬

**Comment by zanllp** [comment]
加上了 。具体可以看 https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/131
