### ISSUE TITLE
Walk mode not working correctly if images are saved in two levels of subfolders

### ISSUE THREAD

**Issue by HacksoreDE** [zanllp/sd-webui-infinite-image-browsing#318]
If you have your automatic1111 directory name pattern set up so that your generated images are saved to two levels of subfolders

![Unbenannt](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/69366622/6ba67878-e594-4bcd-909f-dc9aebe67025)
and then try to use the walk mode, it just shows the folder names of the first subfolder level instead of all the images

![Unbenannt](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/69366622/0caa005d-bf8b-4804-8ee7-5fb4abb5a4db)

**Comment by zanllp** [comment]
This problem will be resolved in the near future, as the current walk mode is not a true depth-first search.

**Comment by HacksoreDE** [comment]
Alright, thank you for the quick response

**Comment by zanllp** [comment]
upgrade to the latest version to resolve this issue

**Comment by HacksoreDE** [comment]
Works like a charm. Thank you so much for the update!
