### ISSUE TITLE
Feature Request: Allow download of many selected images at once.

### ISSUE THREAD

**Issue by drphero** [zanllp/sd-webui-infinite-image-browsing#319]
Delete and move are supported for this. It would be awesome if download worked as well.

**Comment by zanllp** [comment]
If you're running locally, you can use the 'copy'  to achieve the download functionality. 

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/de3798b4-e3d0-495c-bd6a-fca3596b3d3f)

**Comment by drphero** [comment]
> If you're running locally, you can use the 'copy' to achieve the download functionality.

I'm using runpod, so unfortunately that won't work. Thanks though.

**Comment by zanllp** [comment]
Already supported. See #131 for more detail.
