### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by Tobe2d** [zanllp/sd-webui-infinite-image-browsing#32]
Thank you for this nice extention ;-)

I would like to Request a Feature for adding filters for the images showing, for example new to old or old to new so it arrange the images based on date of creation from up to down or the other way around.

**Comment by zanllp** [comment]
You can choose the sorting method in the upper-right corner of the TabPane

More -> sorting method

<img width="445" alt="image" src="https://user-images.githubusercontent.com/25872019/233480083-7c121ce0-4c79-4786-befb-d388398e565f.png">

**Comment by Tobe2d** [comment]
Totally missed that as it is looking this way for me:

![image](https://user-images.githubusercontent.com/4099839/233487683-61babb31-9300-46e7-ae83-f8ab28806259.png)

**Comment by Tobe2d** [comment]
Maybe due the dark theme

**Comment by zanllp** [comment]
The dark mode seems to be having some issues on your device. What browser and system are you using?

**Comment by zanllp** [comment]
fixed

**Comment by Tobe2d** [comment]
Yes! it is perfict now. Thank you 🙏
