### ISSUE TITLE
modular image browser

### ISSUE THREAD

**Issue by picobyte** [zanllp/sd-webui-infinite-image-browsing#320]
Currently I've become maintainer of Toriato's original [webui-wd14-tagger](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger). In my last [commit](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/commit/34be00c452115b07a8a4f5c9603cd9240ee2f199) I've added a rudimentary image browser, which is now able to display image duplicates. Ideally I'd also like to add some more functionality, issues [8](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/issues/8) and [15](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/issues/15). Of course I could try implementing this from scratch, is it maybe possible to implement a browser based on the infinite image browser as a module on a gradio gallery tab?

I'll investigate a little myself, but let me know if this is already a feature.

**Comment by zanllp** [comment]
You could take a look at @WSH032's [sd-webui-fast-dataset-maker](https://github.com/WSH032/sd-webui-fast-dataset-maker) on GitHub for inspiration, as it also uses Gradio and includes an image browser.
