### ISSUE TITLE
Can sd-webui-infinite-image-browsing limit the access to files/folders that are not specified？

### ISSUE THREAD

**Issue by ThomasXuyuntao** [zanllp/sd-webui-infinite-image-browsing#323]
Hi,

this tools can list all the files/folder in the system without any limitation, it is not safe at all. 
i  can easly change the path and see all of the files/folder in this server/pc.

can you introduce a config to limit it ?

**Comment by zanllp** [comment]
When you allow others to access, the 'access control' mode will be automatically enabled.

 See #310 https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/.env.example for reference.

**Comment by ThomasXuyuntao** [comment]
cool man
