### ISSUE TITLE
Broken with lobe / Kitchen Theme UI

### ISSUE THREAD

**Issue by gurukast** [zanllp/sd-webui-infinite-image-browsing#330]
was working prior to the **2023-7-21** update.
[Lob Theme ]( https://github.com/canisminor1990/sd-webui-lobe-theme)
Before, would take up entire container, now it's stuck in this tiny narrow strip

![framed](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/132414857/f74ba97e-72ca-4bf0-8b1d-1daa310404ae)

**Comment by zanllp** [comment]
During development, I also tested it under Lobe and didn't encounter any issues. Could you please press F12 to open the console and check for any errors?
<img width="1920" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/8b6b4308-698c-4710-9912-318e6187b60a">

**Comment by gurukast** [comment]
Hope this helps
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/132414857/2d32f07c-af95-4ebc-8ded-b3143f226fb2)

**Comment by zanllp** [comment]
It seems like there isn't any useful information. You can switch to the tab that this extension belongs to, as some errors may only appear when you switch to that tab.

**Comment by mart-hill** [comment]
I've noticed, it happens with Vlad's UI as well:
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/55754730/212f57f6-5231-44b3-9413-aefc246cbdc0)

I wonder, if this warning has something to do with it?
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/55754730/7a7940c2-e69b-4ec8-bda5-cc6e50207843)

**Comment by zanllp** [comment]
@mart-hill 

I'll add a fallback. If there's an issue, it should be an error rather than a warning.

**Comment by mart-hill** [comment]
Thank you!

There are lots of errors around these 2 warnings, I don't know, if they have anything to do with that issue though. The names in gray show, that they probably don't. 🙂 
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/55754730/2e7fc5a7-d886-43da-9841-888029aaa339)

**Comment by zanllp** [comment]
@gurukast @mart-hill 
I have added a fallback for mounted failure. If the mount fails, a message will be printed to the console, similar to the screenshot below.


<img width="611" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/c9eaa806-694e-4e26-8150-fff26fa7bc7e">

**Comment by zanllp** [comment]
If there are any issues similar to the screenshot, please display them so that I can fix them. The modifications added on 7-21 have the potential to bring a significant improvement to the user experience.

**Comment by mart-hill** [comment]
The fallback helped, though I don't see the error shown above. Maybe Brave browser simply likes that solution? 🙂

**Comment by gurukast** [comment]
same, everything works as it should now,  still getting exactly the same messages in the f12 console, so no idea what went wrong before..i guess it can be closed?
