### ISSUE TITLE
Walk mode gone in latest version

### ISSUE THREAD

**Issue by drphero** [zanllp/sd-webui-infinite-image-browsing#337]
As can be seen in the screenshot below, walk mode is gone. I have tried completely removing the extension and reinstalling it, but it's the same. Also, in many places it refers to clicking 'More' in the upper right, but there is nothing like that.

![walkmode](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/14174687/1f8c5930-69f7-4fbd-ba34-7311db514a78)

**Comment by drphero** [comment]
If I roll back to this commit [d3b3599b73a22f742323a52da9c3db8ff56ceeda](https://github.com/zanllp/sd-webui-infinite-image-browsing/commit/d3b3599b73a22f742323a52da9c3db8ff56ceeda), the walk mode is back and the 'More' link is back as well.

**Comment by zanllp** [comment]
Are you running in standalone mode?

**Comment by zanllp** [comment]
Did you pass the IIB_ACCESS_CONTROL_ALLOWED_PATHS environment variable? If passed, it will overwrite the default trusted paths.

**Comment by drphero** [comment]
I'm not running in standalone more and I've never used the .env for it.

**Comment by zanllp** [comment]
You can try updating to the latest version and see if it works. I tried it under WSL and didn't encounter any issues.

**Comment by zanllp** [comment]
It's fixed now, maybe.
