### ISSUE TITLE
Feature request: Prompts when viewing an image and Right-click menu on big image.

### ISSUE THREAD

**Issue by ostap667inbox** [zanllp/sd-webui-infinite-image-browsing#34]
**It is very necessary** to see the generation info (prompts, etc) when an image is open. We can flip through images with arrows, it would be very convenient for the artist to see _how the prompt changes_. Now it is VERY inconvenient to see the generation info - you have to make several clicks for each picture.

There also needs to be a copy button for the generation info and a right-click menu with the same options as the right-click menu on the preview pictures.

Probably, it is necessary to make this text block optional, so that those who don't need it could disable it.

![browser](https://user-images.githubusercontent.com/123593542/233770208-738b568c-cfc7-4640-b179-9df2af5cac57.png)
![browser-right-click](https://user-images.githubusercontent.com/123593542/233770506-61324b0c-2ac0-4b3f-b95d-88a9054d7b39.jpg)

**Comment by zanllp** [comment]
Thank you for your feature request! We think it's a great idea and we’re happy to accept it. We will add it to our roadmap and prioritize it accordingly.

**Comment by nightgolfer** [comment]
I'm really loving the image browser, especially after the "don't show other files"-fix!

Being able to see prompts and other generation data on zoom is also something I would love to see, hope this gets implemented soon! 😃

**Comment by zanllp** [comment]
@ostap667inbox @nightgolfer 

I have implemented this feature. You can watch the demo video added in the README to learn more.

https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/README-en.md#full-screen-preview

**Comment by ostap667inbox** [comment]
> I have implemented this feature.

Great! It became very comfortable. Thank you!
If it will be technically possible to add to the context menu "Delete this image" - it will become even more convenient. It will also be very useful if to delete the open picture will be accepted by pressing Delete key on the keyboard. With a confirmation, of course.

**Comment by zanllp** [comment]
> > I have implemented this feature.
> 
> Great! It became very comfortable. Thank you! If it will be technically possible to add to the context menu "Delete this image" - it will become even more convenient. It will also be very useful if to delete the open picture will be accepted by pressing Delete key on the keyboard. With a confirmation, of course. Now you have to close a large picture to delete it, and then look for it in the preview list to select and delete it.
> 
> From a usability point of view, it would be best if after deleting the currently opened picture, the next one would be opened immediately. This way it would be convenient to view detailed pictures in enlarged view and delete unnecessary ones one by one.
> 
> _Deleting pictures is a very important part of workflow. There are always a very large number of images to be deleted at the end of a job. It would be great if special attention were paid to the convenience of this action._

I will add the delete feature later. Currently, it is not included because it is relatively complicated to implement.

**Comment by zanllp** [comment]
> > I have implemented this feature.
> 
> Great! It became very comfortable. Thank you! If it will be technically possible to add to the context menu "Delete this image" - it will become even more convenient. It will also be very useful if to delete the open picture will be accepted by pressing Delete key on the keyboard. With a confirmation, of course. Now you have to close a large picture to delete it, and then look for it in the preview list to select and delete it.
> 
> From a usability point of view, it would be best if after deleting the currently opened picture, the next one would be opened immediately. This way it would be convenient to view detailed pictures in enlarged view and delete unnecessary ones one by one.
> 
> _Deleting pictures is a very important part of workflow. There are always a very large number of images to be deleted at the end of a job. It would be great if special attention were paid to the convenience of this action._

The feature has been implemented, but there are still a few minor bugs that have not been resolved yet. For example, after deleting the last image, there is a chance that you may need to manually tap on the background to exit the full-screen preview.

**Comment by zanllp** [comment]
I have closed this issue. If you have any further problems or requests, please create a new issue.
