### ISSUE TITLE
移动失败，检查你的路径输入C:/ not found

### ISSUE THREAD

**Issue by liony-hyh** [zanllp/sd-webui-infinite-image-browsing#342]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/130450263/54837027-e2ac-4c9f-bc0d-624a188b74f7)

搜索 like 标签提示错误：移动失败，检查你的路径输入C:/ not found
操作步骤：
1. 更换新电脑，将旧电脑的硬盘拔下来接入新电脑
2. 在新电脑中可以正常读取sd的生成图片，并且可以正常启动sd（秋叶整合包）
3. 启动sd后，选择“无边图像浏览”
4. 选择“图像搜索”，选择 like 标签
5. 点击“搜索”按钮，提示错误“移动失败，检查你的路径输入C:/ not found”
6. 右侧正常出现搜索结果分屏边栏，但是搜索结果为空（正常应该是有结果才对，我之前给不少找片都打过like标签）

**Comment by liony-hyh** [comment]
补充，选择任意的搜索条件都会有同样的错误提示：移动失败，检查你的路径输入C:/ not found。
但是搜索结果可以正常出现。

**Comment by zanllp** [comment]
你要不先更新下插件看看，我想不太出来这个是怎么触发的

**Comment by liony-hyh** [comment]
我更新到最新版了。。T_T
我也很纳闷，我甚至重装了一遍插件，重建索引，仍然会有这个错误。
请问索引是存在哪里的？感觉上是读取某个目录失败，然后尝试读取C盘根目录

**Comment by zanllp** [comment]
根目录下iib.db。
我好像找到了问题。这两天加上的只读和允许范围路径控制 功能问题有点太多了

对了，文生图，图生图，保存，额外那些可以用吗

**Comment by liony-hyh** [comment]
其他功能都正常

**Comment by zanllp** [comment]
应该好了你更新下试试。

**Comment by liony-hyh** [comment]
还是不行，跟之前的错误一样

**Comment by zanllp** [comment]
> 还是不行，跟之前的错误一样

能不能直接使用git更新，我记得启动器有缓存的

**Comment by zanllp** [comment]
图像like tag搜索不出来的问题，我感觉是因为你那些图像的路径变化了，和数据库内的对应不上。这个暂时还没想到什么解决办法，如果是直接把写在文件里面我怕速度太慢，而且复制的文件处理也很麻烦，如果是使用iib自带的移动功能只移动图像（不包含文件夹）它倒是会处理这个问题直接。

**Comment by liony-hyh** [comment]
图像like tag搜索不出来的问题 —— 并不是完全搜不出来，我新打的 like tag是可以搜出来的，搜不出来的是以前在旧电脑上打的tag

**Comment by zanllp** [comment]
> 图像like tag搜索不出来的问题 —— 并不是完全搜不出来，我新打的 like tag是可以搜出来的，搜不出来的是以前在旧电脑上打的tag

这个倒是正常符合预期的。想要搜出旧的，除非图片存放的路径一致

**Comment by liony-hyh** [comment]
重建缓存是不是应该就可以了，应该怎么重建缓存呢

**Comment by zanllp** [comment]
不行的。重建索引直接iib.db删除然后再打开搜索页建立就行, 但那只是将你的prompt,lora,modal这些的生成信息转成tag，再建立图像和这些生成信息的tag之间多对多的索引。

但是像收藏like这些的是你手动打上去没办法. 但是如果旧电脑上的拓展文件夹下iib.db还在的话，那还可以直接修改把数据库的路径，不过也挺麻烦
