### ISSUE TITLE
Send to save folder - doesnt send the .txt file with prompt details

### ISSUE THREAD

**Issue by steinhaug** [zanllp/sd-webui-infinite-image-browsing#345]
I just upgraded to the latest version right now, and notice that the .txt file thats named same as image does not get copied anymore. This was fixed in a previous version but doesnt seem to work right now.

Using the "outdir_save" in config.json, moving an image or several images will move the image files. However the TXT files are not 
moved and left behind.

example:

    imagename.jpg
    imagename.txt

only *imagename.jpg* is moved.

I am running the "standalone" version, windows.

__update__
Strange, now it did work, seems it doesnt work for some folders. This folder did NOT work "orangemix.vae", this folder "perfectdeliberate_v40" DID work.

**Comment by zanllp** [comment]
It looks fine on my end. The only thing is that after moving, the txt file on the right side is still displayed on the page. However, I usually only show images and folders, so I don't think this is a big problem. You can just forget about the existence of the txt file and refresh the page if necessary. You can check if the behavior on your end matches this.
https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/59a7f314-1171-4a29-adf5-bcf97ef79865

**Comment by zanllp** [comment]
I think I've found the reason for the error. It seems that there cannot be a "." in the file path, otherwise the replacement will fail. I'll fix it later.

https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/d6e84bbcd89350d200c3852cf85cc64e2962fec7/scripts/iib/tool.py#L286-L290

**Comment by zanllp** [comment]
upgrade to the latest version to resolve this issue
