### ISSUE TITLE
能否添加一个密码解锁功能

### ISSUE THREAD

**Issue by li775176364** [zanllp/sd-webui-infinite-image-browsing#363]
当我把SD投射到公司网络和公网上多人使用时，很需要给图片文件夹加密，只有管理员能访问，以规避一些安全问题

可以很简单的：
1.设置密码
2.每次刷新网页需要输入密码以解锁界面

**Comment by zanllp** [comment]
```env
IIB_SECRET_KEY=key123
IIB_ACCESS_CONTROL_ALLOWED_PATHS=save,extra
IIB_ACCESS_CONTROL_PERMISSION=read-only
```
参考 https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/.env.example

**Comment by zanllp** [comment]
可以看下这个 https://www.bilibili.com/video/BV1zm4y1W7W9

**Comment by li775176364** [comment]
非常感谢，太棒了
