### ISSUE TITLE
Security risk!

### ISSUE THREAD

**Issue by sebaxakerhtc** [zanllp/sd-webui-infinite-image-browsing#367]
mydomain/infinite_image_browsing is accessable without authentication!

**Comment by zanllp** [comment]
I think you can start by reading the readme first and refer to the following links.

https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/.env.example

https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/323

<img width="826" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/06b1d5b9-0359-4015-a95f-d717dc6aa570">

**Comment by sebaxakerhtc** [comment]
That's nice, but people installed this extension through webUI
![222](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/32651506/09f8ea36-5c8f-4e01-b6b9-f328834b7f49)

Do you see something about Privacy and Security?

Your work is great, but it's better to set some security by default
Don't you think so?

**Comment by zanllp** [comment]
Did you use gradio-auth for authentication?

**Comment by sebaxakerhtc** [comment]
> Did you use gradio-auth for authentication?

Of cource

**Comment by zanllp** [comment]
I added an error, if you configured gradio-auth, IIB will forcibly require you to configure Secret Key
<img width="1190" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/31d54f5c-b4bb-44f7-b3cf-07d26ac6104f">

**Comment by sebaxakerhtc** [comment]
> I added an error, if you configured gradio-auth, IIB will forcibly require you to configure Secret Key <img alt="image" width="1190" src="https://user-images.githubusercontent.com/25872019/258541048-31d54f5c-b4bb-44f7-b3cf-07d26ac6104f.png">

It's nice solution!!
