### ISSUE TITLE
【suggestion】is it possible to add a search funtion to this extention?

### ISSUE THREAD

**Issue by jasoncow007** [zanllp/sd-webui-infinite-image-browsing#369]
for quick fitch the pic we remembered, we could search the keyword from the promt words,  its a far more resonable way, isnt it?

**Comment by zanllp** [comment]
Both "image search" and "fuzzy search" support using prompts to search for images.

**Comment by jasoncow007** [comment]
the meaning of search in this extenion is after searching, the result could be sent to img2img/txt2img immediately

**Comment by zanllp** [comment]
I didn't quite understand what you were saying.
If you want to move search results to a specific folder, you can simply drag and drop them、.

**Comment by jasoncow007** [comment]
I mean if you want to re-paint a image with  old prompts, its a good way to search keywords in this brower, and click sent to img2img to repaint

**Comment by zanllp** [comment]
You can refer to the video below for this functionality. It is supported now.

https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/bbdf211e-dea8-46bf-8861-767078273c10

**Comment by jasoncow007** [comment]
got it! my fault，I missed the match function
