### ISSUE TITLE
keep dark theme in new tab

### ISSUE THREAD

**Issue by eumelzocker** [zanllp/sd-webui-infinite-image-browsing#370]
My browser in set to light theme in the default settings. Therefore I always use sd-webui with the "--theme dark" param. This adds "?__theme=dark" to my sd-webui URL. When I open infinite_image_browsing in a new tab this param is not kept and I must add it manually every time. Very inconvenient, would be great if this would be done automatically.

**Comment by zanllp** [comment]
Already added
