### ISSUE TITLE
[Feature Request]: Graceful failure if ComfyUI EXIF fails to parse

### ISSUE THREAD

**Issue by Chubbly** [zanllp/sd-webui-infinite-image-browsing#371]
Thank you for all your efforts to add ComfyUI support, it is very appreciated! The current EXIF parsing works when using ComfyUI nodes but fails when certain custom nodes are used to do sampling. With the current way EXIF data is managed in Comfy, I don't think it is possible to cover custom node implementations so it would be preferable that if the EXIF data fails to parse because it can't locate the KSampler node, it doesn't show an error in the UI. It makes it hard to navigate when the error keeps appearing for looking over ComfyUI images.

I've attached an example PNG where it fails to parse.

![colorful_v31 - 82 - Instagram-Pose (119) png _00001_](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/5073911/b7000884-a5e1-4b24-8b6b-e64a6d5a07c2)

**Comment by zanllp** [comment]
Already added

**Comment by Chubbly** [comment]
Amazing, works like a charm 😄
