### ISSUE TITLE
Paths don't have the same drive after updating

### ISSUE THREAD

**Issue by markheaps** [zanllp/sd-webui-infinite-image-browsing#376]
When entering the tab I see "ERROR:scripts.iib.logger:Paths don't have the same drive" being logged as it loads.  

I have the latest version, and by default I am viewing the txt2img and a custom path d:\Pics

**Comment by zanllp** [comment]
Ignore this, just disregard it. If you haven't passed in APP_ENV=dev, this error will only appear in the log.log file.
