### ISSUE TITLE
Workflow improvements tagging

### ISSUE THREAD

**Issue by scottix** [zanllp/sd-webui-infinite-image-browsing#380]
When browsing photos. Making it easier to like a photo would make my workflow a lot easer.

**Workflow**
What I normally do is keep iterating on image prompts, producing lots of different images and idea.
Then I go into Infinite Image Browser and start tagging like to the images I think are good.
Then use the Image Search to get all the like photos.
Then I iterate again, until I find the best one I like.

My problem is like and unlike photos has too many clicks to be efficient.

**Solution 1**
Add an outline heart next to the three dot menu.

**Solution 2**
Another acceptable solution is in the right-click menu add the custom tags in the first level menu, preferably at the top. Would make it easier to access them faster.

**Extra**
Kind of outside the scope, but having separate boards of projects and maybe going a little further of like is a star 1-5 system.

**Comment by zanllp** [comment]
Sounds good, but I'm currently very busy. I'll look into how to implement it later.

**Comment by zanllp** [comment]
Already added. https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Change-log#2023-8-31

You can use custom tags such as star-1, star-2, star-3 , etc.  to replace "star 1-5". Currently, there are no plans for an official implementation of this feature.

**Comment by scottix** [comment]
Awesome can't wait to try it.
