### ISSUE TITLE
No Image Viewer tab on SD1.5 A1111 v1.5.1 on Runpod

### ISSUE THREAD

**Issue by Kornifikator** [zanllp/sd-webui-infinite-image-browsing#383]
Hello, I use Runpod, a virtual GPU space, with SD1.5 A1111 v1.5.1. I installed the current version of this great extension as described, but I can't see the extension tab. Some weeks ago I already used your extension in a previous version and it worked instantaneously perfect. 
Don't get me wrong, I really appreciate your work and the extension itself is awesome, but why on earth do people always have "to improve things for the worse"?? Why did you have to introduce this IIB_ACCESS_CONTROL stuff, that requires downloading weird extra files to some folder and changing variables in files that are for no use for most users?! Especially when things worked totally fine before that...

Anyway, as stated before, I can't see the tab any more and therefore I can't use the extension at all.
Jupyter Lab environment can't show/doesn't accept .env-files with anything before the (.). 
YES: I already tried #284 and it didn't work
NO: #84 doesn't do the trick either. Moreover, I can't change the URL (localhost or public) in Runpod anyway

Any ideas to get it running as intended? A link to a previous version before .env and IIB stuff would be okay too.
Thank you very much in advanced!

**Comment by zanllp** [comment]
The absence of the infinite-image-browsing tab is not related to the .env file. You can check the console for any other errors.

**Comment by zanllp** [comment]
If you want to use an older version of IIB
```bash
git clone -b <TAG> https://github.com/zanllp/sd-webui-infinite-image-browsing.git
# FOR EXAMPLE

git clone -b v0.3.0 https://github.com/zanllp/sd-webui-infinite-image-browsing.git.
```

**Comment by MikeBivins** [comment]
im on automatic1111 initially facing the same issue on runpod with no tab to select. However after I set --update-alll-extensions then force kill the port to restart the ui and terminal it shows up. Now I dont have a clue if this is the case always but you could give it a try

**Comment by aiiven** [comment]
I have the same issue. Did someone make sd-webui-infinite-image-browsing work on Runpod? The tab just doesn't show up.
