### ISSUE TITLE
[Multiple Tabs]: When using send to text2img, the prompts will be sent to all tabs that are opened.

### ISSUE THREAD

**Issue by melovewrestling** [zanllp/sd-webui-infinite-image-browsing#385]
Hi, thanks for the amazing image browser. This is definitely one of the best if not THE best out there! 
Good work!
I just noticed for a while, that when using send to text2img, (same goes for send to img2img, inpaint, extra, etc), the prompts and all settings will be send to ALL the stable diffusion tabs that are currently opened. It would be great if this function can be applied with the restriction of affecting only the active tab that are using the infinite image browser.

Otherwise, thanks for the amazing work! Xiexie!

**Comment by zanllp** [comment]
In the latest version, if you are not using IIB in a separate browser tab, then IIB will only send the file to the page it is on.

**Comment by melovewrestling** [comment]
Many thanks! I've updated it to the latest version and it works like a charm now! 10/10 tool!
