### ISSUE TITLE
Security Vulnerability: Unauthenticated Local File Inclusion

### ISSUE THREAD

**Issue by vysecurity** [zanllp/sd-webui-infinite-image-browsing#387]
# Issue

The extension exposes the Web UI instance to an unauthenticated Local File Inclusion vulnerability.

Example request:

```
GET /infinite_image_browsing/file?path=/proc/self/environ&t=2023-05-08%2017%3A55%3A10 HTTP/1.1
Host: redacted
```

An attacker could read the `/etc/passwd` file for example, `/etc/hosts`, `/etc/resolv.conf` to gain more information about the system.

An attacker could also read the `/proc/self/environ` variable to read the command line arguments used to execute Web UI and extract the username and password to login to the server.

# Fix:
* Ensure that the user is authenticated before allowing the API to be called.
* Restrict the file paths and types that the browsing can access.

# Next:

If you can replicate, please let me know. Trying to get a CVE assigned, thanks.

If you don't plan to fix please also let me know.

**Comment by zanllp** [comment]
Have you seen this document? https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/.env.example
.

Or, have you tried making sd-webui accessible to the public （--share）, and were you able to access sensitive files afterwards?

**Comment by vysecurity** [comment]
I found the issue when performing a security test previously. I do not have a SD Web UI set up unfortunately with the plugin correctly configured with the secret key to be able to replicate now.

Do you have an instance you can message me with so that I can replicate and test for you?

In general it did not appear that anything would stop the access to sensitive files because the Web UI I was testing was already password protected using `--gradio-auth`.

**Comment by zanllp** [comment]
The design philosophy of IIB is to grant all permissions locally for easy user operation, and narrow down the allowed permissions by default when allowing public access. It switches based on different environments.



> Do you have an instance you can message me with so that I can replicate and test for you?

Unfortunately, I don't use products like Colab, so I can't easily provide you with a test instance. However, if you have sd-webui installed, you just need to input any one of the following parameters, and IIB will automatically enable protection: --share, --ngork, --listen, --server-name.

https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/38a04a4b93e057d887371c6ea6ca46c513d7f37e/scripts/iib/tool.py#L244-L262



> In general it did not appear that anything would stop the access to sensitive files because the Web UI I was testing was already password protected using --gradio-auth. The IIB key, I do not recall having tested it specifically, but it's worth verifying to see if it would bypass the control. 


If you pass in "gradio-auth" in the sd-webui CLI, IIB will also require you to enter a password.

https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/38a04a4b93e057d887371c6ea6ca46c513d7f37e/scripts/iib/api.py#L79-L82
https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/38a04a4b93e057d887371c6ea6ca46c513d7f37e/scripts/iib/tool.py#L235-L243

**Comment by vysecurity** [comment]
When was the secret key added? I tested this plugin around 3 weeks ago and it did not protect the app. Thanks!

**Comment by zanllp** [comment]
The secret key feature was added early on. 
However, the requirement to add a secret key after configuring gradio-auth was enforced in pull request #368. Perhaps you just happened to miss that particular pull request.
