### ISSUE TITLE
Move failed. Check your path input.C:/ not found

### ISSUE THREAD

**Issue by ianbrophy** [zanllp/sd-webui-infinite-image-browsing#393]
I am unable to browse any images and receive this error:

_Move failed. Check your path input.C:/ not found_

I have tried various other paths, and tried to add absolute paths, but have not been able to get around this error. I have checked for a new update, but the GUI shows now update for this extension.

Is this a common issue? 
Thank you

**Comment by zanllp** [comment]
This is not a common issue. It seems that there might be a problem with the file path configuration of your sd-webui's image output folder, as shown in the image below. 

<img width="1312" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/35a7faeb-d33b-42f6-a384-05b7d10e3d23">

You can try renaming the config.json file located in the root directory of sd-webui as a backup, and then restart sd-webui. It will generate a new config.json file. You can check if IIB can function properly in this situation.


When this error occurs, the browser's console also prints relevant error messages. Can you take a screenshot of it and share it for me to see?

**Comment by zanllp** [comment]
I fixed an error that may have caused this issue. You can update to the latest version and take a look.
