### ISSUE TITLE
Support for Fooocus-MRE

### ISSUE THREAD

**Issue by Jisevind** [zanllp/sd-webui-infinite-image-browsing#394]
Please consider adding support for Fooocus-MRE metadata, https://github.com/MoonRide303/Fooocus-MRE

Image browsing works fine but it would be great to have the metadata too.

Here is an example of the metadata that is either embedded in the image file or as a separate json file:

{"prompt": "Halloween witch, full body, simple 2d vector, white background, clean outline", "negative_prompt": "", "style": "sai-comic book", "seed": 8834915829939807712, "width": 1152, "height": 896, "p_txt": "comic Halloween witch, full body, simple 2d vector, white background, clean outline . graphic illustration, comic art, graphic novel art, vibrant, highly detailed", "n_txt": "photograph, deformed, glitch, noisy, realistic, stock photo, ", "sampler": "dpmpp_2m_sde_gpu", "scheduler": "karras", "performance": "Speed", "steps": 30, "switch": 20, "sharpness": 2, "cfg": 7, "base_clip_skip": -2, "refiner_clip_skip": -2, "base_model": "morphxl_v10.safetensors", "refiner_model": "None", "l1": "sd_xl_offset_example-lora_1.0.safetensors", "w1": 0.5, "l2": "add-detail-xl.safetensors", "w2": 0.5, "l3": "None", "w3": 0.5, "l4": "None", "w4": 0.5, "l5": "None", "w5": 0.5, "img2img": false, "revision": false, "zero_out_positive": false, "zero_out_negative": false, "control_lora_canny": false, "control_lora_depth": false, "software": "Fooocus 1.0.43 MRE"}

**Comment by zanllp** [comment]
Can you provide a few image files for me to test? I need two different types. Please save them in a compressed file.

**Comment by Jisevind** [comment]
Sure, here are some images, let me know if you need something else.

[Fooocus-MRE Images.zip](https://github.com/zanllp/sd-webui-infinite-image-browsing/files/12505628/Fooocus-MRE.Images.zip)

**Comment by zanllp** [comment]
Currently, IIB has already supported Fooocus and will not support the mre version.
