### ISSUE TITLE
Virus inside "Infinite.Image.Browsing_0.4.0_x64-setup.exe"

### ISSUE THREAD

**Issue by Mikekre** [zanllp/sd-webui-infinite-image-browsing#397]
Hey,
I downloaded the Infinite.Image.Browsing_0.4.0_x64-setup.exe file, it was blocked and removed by my antivirus.
I run virustotal on this file and I got 25 out 67 security vendors:
"**Popular threat label trojan.redcap/python Threat categories trojan Family labels redcap python".**
https://www.virustotal.com/gui/file/cbaf646e97b57764cfd49ccd49a99177fda2fcc4d2c735c0818b9f4c10587ae1
Could you confirm that your program is safe?.
Thankks.
MK

**Comment by zanllp** [comment]
It is true that some antivirus software may identify the sidecar of iib as a virus, but this is a false positive and can be ignored. You can refer to https://github.com/Nuitka/Nuitka/issues/2081 for more information.

You can also choose to run it in Python or compile it yourself, if you're really worried.

**Comment by MojoJojo43** [comment]
> Hey, I downloaded the Infinite.Image.Browsing_0.4.0_x64-setup.exe file, it was blocked and removed by my antivirus. I run virustotal on this file and I got 25 out 67 security vendors: "**Popular threat label trojan.redcap/python Threat categories trojan Family labels redcap python".** https://www.virustotal.com/gui/file/cbaf646e97b57764cfd49ccd49a99177fda2fcc4d2c735c0818b9f4c10587ae1 Could you confirm that your program is safe?. Thankks. MK

Hey did you try installing this? I came across the same issue with Defender. Thoughts?

**Comment by zanllp** [comment]
In the latest release, a PyInstaller-compiled version has been added, significantly reducing the likelihood of false positive virus detections. https://github.com/zanllp/sd-webui-infinite-image-browsing/releases/tag/v0.17.0
