### ISSUE TITLE
Please add a support to view and downnload mp4 videos

### ISSUE THREAD

**Issue by otorre1** [zanllp/sd-webui-infinite-image-browsing#403]
i am using sd-webui in a cloud computing, so your extension has been a solution for me to download, delete and move files and folders 

 I tried searching for my videos made on deforum using this extension, but the output folders only contains images

Or you can create another  sdui extension for files explorer

Sorry my english

**Comment by zanllp** [comment]
Sounds good, but there's quite a lot of work to be done, such as video thumbnail generation.

**Comment by zanllp** [comment]
Already supported. See https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Change-log for more information.

**Comment by otorre1** [comment]
Thank you!
