### ISSUE TITLE
Files are saved with the generic name "file" instead of the actual filename when saving an image from preview

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [zanllp/sd-webui-infinite-image-browsing#404]
Files are saved with the generic name "file" instead of the actual filename when saving an image from preview.
I know that there is an option to click in UI to download that saving with proper names - but this option is less intuitive than just clicking on an image and saving it.
Adding a keyboard shortcut to save could be a good option too.

**Comment by zanllp** [comment]
already added

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/78195ee3-2b98-47b7-bf06-a5cd83a3f7d5)

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/46cec544-a8ce-4856-8b7d-89e99661fd25)

**Comment by a-l-e-x-d-s-9** [comment]
@zanllp 
Thank you very much!
