### ISSUE TITLE
Download of multiple selected files only downloading up to 11 images

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [zanllp/sd-webui-infinite-image-browsing#405]
I selected around 70 images and clicked to download them, but only 11 images were downloaded.

**Comment by zanllp** [comment]
Try using batch download.
<img width="298" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/054f938a-6106-4b4d-999f-81f0e49c750e">

**Comment by a-l-e-x-d-s-9** [comment]
@zanllp 
Ok. But this batch downloader looks like a workaround - it's not intuitive, zipping and unzipping is just a waste of time and space, and it's additional UI and logic that requires maintenance.
Wouldn't it be easier to run a thread that pushes downloads slightly more gradually, and make sure that all files actually downloaded?

**Comment by zanllp** [comment]
I currently don't have the extra energy to deal with these tasks. For my machine, saving 200 images only takes a few seconds, so I won't make too many changes for now. Additionally, batch downloading is the proper solution, as directly downloading multiple selected files immediately can cause complications for subsequent archiving. Furthermore, batch downloading can serve as a temporary workspace to consolidate multiple selected results.

**Comment by a-l-e-x-d-s-9** [comment]
First of all, thank you for your good work.
I can live with a batch downloader.
But I disagree with you that it's a "proper solution".
You select files and click download, you want the files to be downloaded. Making additional storage place only adds more steps for the user and more code for you to maintain.
I suggest not downloading all files at the same time, only to download a few, and to have a FIFO queue with thread that downloads additional, when previous files have been downloaded. Without zipping anything. I'm not familiar with your restrictions, but it sounds to me that this workflow should be possible.
