### ISSUE TITLE
It seems to have failed to load. You can try refreshing the page.

### ISSUE THREAD

**Issue by xixino** [zanllp/sd-webui-infinite-image-browsing#410]
`It seems to have failed to load. You can try refreshing the page.
If that doesn't work, click on [FAQ](https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/90) for help.`

大佬你好，我是代码小白，我在阿里云搭建了webui,以上是报错内容，我的访问路径只有[http://0.0.0.0:7860]，我尝试了#79 ，#9150，#84即刷新\重启\禁用缓存都没有用，我不知道要怎么做，希望你能帮我解答，万分感谢。

**Comment by xixino** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/72537603/e06ac290-50a3-41b4-abdc-e28502d32b3d)

**Comment by zanllp** [comment]
--share 然后用  gradio live的链接就能访问了，

不过这个问题实际上我感觉是什么是什么nginx 或者防火墙之类的配置问题，你们可以和做这个阿里云部署教程的人反馈下

**Comment by xixino** [comment]
是在webui-user.bat里面添加吗？添加后要运行吗？我昨天添加没起作用

**Comment by xixino** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/72537603/5833786c-9b18-4fd1-82e0-ae1c7d328915)

**Comment by zanllp** [comment]
阿里云一般是linux吧，linux系统 的话是添加在webui-user.sh里， windows才是bat

**Comment by xixino** [comment]
#!/bin/bash
#########################################################
# Uncomment and change the variables below to your need:#
#########################################################

# Install directory without trailing slash
#install_dir="/home/$(whoami)"

# Name of the subdirectory
#clone_dir="stable-diffusion-webui"

# Commandline arguments for webui.py, for example: export COMMANDLINE_ARGS="--medvram --opt-split-attention"
#export COMMANDLINE_ARGS=""

# python3 executable
#python_cmd="python3"

# git executable
#export GIT="git"

# python3 venv without trailing slash (defaults to ${install_dir}/${clone_dir}/venv)
#venv_dir="venv"

# script to launch to start the app
#export LAUNCH_SCRIPT="launch.py"

# install command for torch
#export TORCH_COMMAND="pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113"

# Requirements file to use for stable-diffusion-webui
#export REQS_FILE="requirements_versions.txt"

# Fixed git repos
#export K_DIFFUSION_PACKAGE=""
#export GFPGAN_PACKAGE=""

# Fixed git commits
#export STABLE_DIFFUSION_COMMIT_HASH=""
#export CODEFORMER_COMMIT_HASH=""
#export BLIP_COMMIT_HASH=""

# Uncomment to enable accelerated launch
#export ACCELERATE="True"

# Uncomment to disable TCMalloc
#export NO_TCMALLOC="True"

###########################################
他这个都是注释，我要在哪行添加呀【尴尬】

**Comment by zanllp** [comment]
<img width="516" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/d4a8eaf6-f062-4315-ad5f-5b7663c88411">

**Comment by xixino** [comment]
是需要在--gradio上注册一个账户然后输入账号跟密码对吗？
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/72537603/7567f00f-7e2a-4cb8-8824-d3cc6b5b1b8a)

**Comment by xixino** [comment]
我现在重启显示的是
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/72537603/67e762c8-a208-496d-ac93-4fdf1e020238)

**Comment by zanllp** [comment]
不用密码，不用注册

**Comment by zanllp** [comment]
注意别泄露url就行
<img width="1013" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/2bae3cf3-d419-40f5-8cb5-bd625c9fbdf0">

**Comment by xixino** [comment]
我怎么在linux下运行啊
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/72537603/d2ad154d-91ff-41ef-9d96-25c324ee9fea)
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/72537603/d11b6bfd-eeaa-4888-bff6-98f636fe53aa)
实在不懂这些，我现在运行还是只有7860

**Comment by zanllp** [comment]
完整的输出给我看下有没有错误，加了--share启动可能慢一些。这个终端看的我脑壳疼

**Comment by xixino** [comment]
`/mnt/workspace/stable-diffusion-webui
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing requirement for sd-webui-controlnet
Launching Web UI with arguments: --no-download-sd-model --xformers --share --listen --enable-insecure-extension-access
No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 1.13.1+cu117. You might want to consider upgrading.
==============================================================================
You are running torch 1.13.1+cu117.
The program is tested to work with torch 2.0.0.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.16rc425.
The program is tested to work with xformers 0.0.20.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
*** Error loading script: streamlit_helpers.py
    Traceback (most recent call last):
      File "/mnt/workspace/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/mnt/workspace/stable-diffusion-webui/extensions/ControlNet-for-SDXL/scripts/streamlit_helpers.py", line 9, in <module>
        from imwatermark import WatermarkEncoder
    ModuleNotFoundError: No module named 'imwatermark'

---
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
*** Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "/mnt/workspace/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-mov2mov/scripts/m2m_ui.py", line 12, in <module>
        from modules.ui import paste_symbol, clear_prompt_symbol, extra_networks_symbol, apply_style_symbol, save_style_symbol, \
    ImportError: cannot import name 'create_seed_inputs' from 'modules.ui' (/mnt/workspace/stable-diffusion-webui/modules/ui.py)

---
sd-webui-prompt-all-in-one background API service started successfully.
reading lora /mnt/workspace/stable-diffusion-webui/models/Lora/GoodHands-beta3.safetensors: AssertionError
Traceback (most recent call last):
  File "/mnt/workspace/stable-diffusion-webui/extensions-builtin/Lora/network.py", line 35, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "/mnt/workspace/stable-diffusion-webui/modules/cache.py", line 115, in cached_data_for_file
    value = func()
  File "/mnt/workspace/stable-diffusion-webui/extensions-builtin/Lora/network.py", line 28, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "/mnt/workspace/stable-diffusion-webui/modules/sd_models.py", line 269, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: /mnt/workspace/stable-diffusion-webui/models/Lora/GoodHands-beta3.safetensors is not a safetensors file

Checkpoint Counterfeit-V2.5_fp16.safetensors [71e703a0fc] not found; loading fallback analog-diffusion-1.0.safetensors [51f6fff508]
Loading weights [51f6fff508] from /mnt/workspace/stable-diffusion-webui/models/Stable-diffusion/analog-diffusion-1.0.safetensors
/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py:141: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  mask_image = gr.Gallery(
/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py:141: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  mask_image = gr.Gallery(
/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/metadata_editor.py:399: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/metadata_editor.py:521: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  cover_image = gr.Image(
/mnt/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-huggingface/scripts/huggingface.py:73: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=True):
/mnt/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-huggingface/scripts/huggingface.py:79: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=True):
/mnt/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-huggingface/scripts/huggingface.py:93: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=True):
/mnt/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-huggingface/scripts/huggingface.py:100: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=True):
Running on local URL:  [http://0.0.0.0:7860](https://dsw-gateway-cn-shanghai.data.aliyun.com/dsw-268039/proxy/7860/)
Creating model from config: /mnt/workspace/stable-diffusion-webui/configs/v1-inference.yaml
Loading VAE weights specified in settings: /mnt/workspace/stable-diffusion-webui/models/VAE/animevae.pt
Applying attention optimization: xformers... done.
Model loaded in 3.9s (load weights from disk: 1.0s, create model: 0.3s, apply weights to model: 1.4s, load VAE: 0.5s, calculate empty prompt: 0.6s).

Could not create share link. Missing file: /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /usr/local/lib/python3.10/dist-packages/gradio
Startup time: 146.2s (prepare environment: 3.6s, import torch: 2.1s, import gradio: 1.0s, setup paths: 0.9s, other imports: 0.3s, load scripts: 1.3s, create ui: 0.7s, gradio launch: 136.1s).`

**Comment by zanllp** [comment]
这里已经说明原因和解决办法了
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/e6111fd4-c6df-4e2e-bc6e-ed9fb73033f0)

```bash
curl -o /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2 https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
```

**Comment by xixino** [comment]
好的我试试，
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/72537603/9c10226a-a805-41d2-801b-17ca55d36576)

**Comment by xixino** [comment]
curl: (28) Failed to connect to cdn-media.huggingface.co port 443 after 129709 ms: Connection timed out链接失败，我可以去hugginface下载替换吗？

**Comment by zanllp** [comment]
当然可以

**Comment by xixino** [comment]
我已经安装了，运行后提示没报这个错，但是还是没有gradio
`/mnt/workspace/stable-diffusion-webui
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing requirement for sd-webui-controlnet
Launching Web UI with arguments: --no-download-sd-model --xformers --share --listen --enable-insecure-extension-access
No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 1.13.1+cu117. You might want to consider upgrading.
==============================================================================
You are running torch 1.13.1+cu117.
The program is tested to work with torch 2.0.0.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.16rc425.
The program is tested to work with xformers 0.0.20.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
*** Error loading script: streamlit_helpers.py
    Traceback (most recent call last):
      File "/mnt/workspace/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/mnt/workspace/stable-diffusion-webui/extensions/ControlNet-for-SDXL/scripts/streamlit_helpers.py", line 9, in <module>
        from imwatermark import WatermarkEncoder
    ModuleNotFoundError: No module named 'imwatermark'

---
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
*** Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "/mnt/workspace/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-mov2mov/scripts/m2m_ui.py", line 12, in <module>
        from modules.ui import paste_symbol, clear_prompt_symbol, extra_networks_symbol, apply_style_symbol, save_style_symbol, \
    ImportError: cannot import name 'create_seed_inputs' from 'modules.ui' (/mnt/workspace/stable-diffusion-webui/modules/ui.py)

---
sd-webui-prompt-all-in-one background API service started successfully.
reading lora /mnt/workspace/stable-diffusion-webui/models/Lora/GoodHands-beta3.safetensors: AssertionError
Traceback (most recent call last):
  File "/mnt/workspace/stable-diffusion-webui/extensions-builtin/Lora/network.py", line 35, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "/mnt/workspace/stable-diffusion-webui/modules/cache.py", line 115, in cached_data_for_file
    value = func()
  File "/mnt/workspace/stable-diffusion-webui/extensions-builtin/Lora/network.py", line 28, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "/mnt/workspace/stable-diffusion-webui/modules/sd_models.py", line 269, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: /mnt/workspace/stable-diffusion-webui/models/Lora/GoodHands-beta3.safetensors is not a safetensors file

Checkpoint Counterfeit-V2.5_fp16.safetensors [71e703a0fc] not found; loading fallback analog-diffusion-1.0.safetensors [51f6fff508]
Loading weights [51f6fff508] from /mnt/workspace/stable-diffusion-webui/models/Stable-diffusion/analog-diffusion-1.0.safetensors
/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py:141: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  mask_image = gr.Gallery(
/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py:141: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  mask_image = gr.Gallery(
/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/metadata_editor.py:399: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/metadata_editor.py:521: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  cover_image = gr.Image(
/mnt/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-huggingface/scripts/huggingface.py:73: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=True):
/mnt/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-huggingface/scripts/huggingface.py:79: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=True):
/mnt/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-huggingface/scripts/huggingface.py:93: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=True):
/mnt/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-huggingface/scripts/huggingface.py:100: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=True):
Running on local URL:  [http://0.0.0.0:7860](https://dsw-gateway-cn-shanghai.data.aliyun.com/dsw-268039/proxy/7860/)
Creating model from config: /mnt/workspace/stable-diffusion-webui/configs/v1-inference.yaml
Loading VAE weights specified in settings: /mnt/workspace/stable-diffusion-webui/models/VAE/animevae.pt
Applying attention optimization: xformers... done.
Model loaded in 3.9s (load weights from disk: 1.0s, create model: 0.3s, apply weights to model: 1.4s, load VAE: 0.5s, calculate empty prompt: 0.6s).`阿里云技术给我的回复是：**您好：
      针对您反馈的问题，gradio.live是 gradio 公司提供的内网隧道穿透服务，不是我们阿里云提供的服务，故无法保证稳定运行。我们DSW实例下的模型都走得是我们的内部网络，不支持公网访问。所以模型启动web ui时只会生成/0.0.0.0:7860或者127.0.0.1:7860这两种UI访问路径。其他的都不行。请知悉**

**Comment by zanllp** [comment]
先放着，后面有空我开下阿里云的试试，之前他们反馈是gradio就行

**Comment by xixino** [comment]
好的谢谢大佬今晚的帮助~

**Comment by xixino** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/72537603/f1fc2748-47a3-4e20-a80f-d43a7c265925)
可以啦可以了，谢谢大佬，我加了这个：export COMMANDLINE_ARGS="--share --gradio-auth aaa:bbb --enable-insecure-extension-access --xformers"，然后加了这个大佬的这个https://blog.csdn.net/qq_44193969/article/details/131966882。哇哇哇开心，谢谢你们，祝你们永远开心

**Comment by xixino** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/72537603/c81dad98-de1e-4426-91f9-10b9cfa80f8c)

**Comment by zanllp** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/d35e8210-79ea-4531-9991-d69b17556e7e)

我会把这个加入faq

**Comment by xixino** [comment]
一定要加，分享给更多人，可以发下b站更好，谢谢大佬啦

**Comment by kmoui** [comment]
> 一定要加，分享给更多人，可以发下b站更好，谢谢大佬啦

请问，具体解决办法是在webui-user.sh这个文件内添加
export COMMANDLINE_ARGS="--share --gradio-auth aaa:bbb --enable-insecure-extension-access --xformers"
chmod +x /home/miniconda3/envs/llm/lib/python3.11/site-packages/gradio/frpc_linux_amd64_v0.2
这两行吗？

**Comment by Keaidecx** [comment]
> > > 一定要加，分享给更多人，可以发下b站更好，谢谢大佬啦
> > 
> > 
> > 请问，具体解决办法是在webui-user.sh这个文件内添加 export COMMANDLINE_ARGS="--share --gradio-auth aaa:bbb --enable-insecure-extension-access --xformers" 导出 COMMANDLINE_ARGS="--share --gradio-auth aaa:bbb --enable-insecure-extension-access --xformers" chmod +x /home/miniconda3/envs/llm/lib/python3.11/site-packages/gradio/frpc_linux_amd64_v0.2 这两行吗？
> 
> chmod +x /home/miniconda3/envs/llm/lib/python3.11/site-packages/gradio/frpc_linux_amd64_v0.2这个要改为你自己的地址，这个代码是让其生效的意思

请问如果是windows该怎么修改webui-user.bat?
![屏幕截图 2023-12-23 234256](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/87927135/c00652ca-c0fd-42ad-8507-659992d27f57)
还有上面改为自己地址那是改gradio的地址吗，不是很懂..
