### ISSUE TITLE
新增 Walk 模式的資料夾後無法移除?

### ISSUE THREAD

**Issue by FrankHGS** [zanllp/sd-webui-infinite-image-browsing#414]
新增 Walk 模式的資料夾後無法移除?
另外是否能在新增資料夾時自訂名稱 一長串路徑蠻彆扭的 3Q ^^

**Comment by zanllp** [comment]
<img width="495" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/2e29fe65-8e85-4172-a57d-c4f869501c5a">
你那边没有这个吗？

自定义后面再考虑吧，需要实现的功能实在太多了，暂时没精力分到这个上面

**Comment by FrankHGS** [comment]
> <img alt="image" width="495" src="https://user-images.githubusercontent.com/25872019/267208273-2e29fe65-8e85-4172-a57d-c4f869501c5a.png"> 你那边没有这个吗？
> 自定义后面再考虑吧，需要实现的功能实在太多了，暂时没精力分到这个上面

是有移除按鈕 點下去 OK 顯示 Bad Request

**Comment by FrankHGS** [comment]
> 这个文件夹的路径是什么？ 控制台/终端 有没有错误输出，截个图我看下

![螢幕擷取畫面 2023-09-13 102643](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/132704944/ea2591ce-e98b-415b-815e-3f8ed67b3536)

其實是試試新增 見這一長串路徑便想作罷移除...

**Comment by zanllp** [comment]
哦，是这个因为这个路径其实是属于  sd-webui的预设文件夹。预设的文件夹设定上是无法移除的，一般是直接我提供给你的。你等我想想怎么处理

**Comment by zanllp** [comment]
应该可以了，更新下试试

**Comment by FrankHGS** [comment]
> 应该可以了，更新下试试

OK! 成功移除 ^^

**Comment by FrankHGS** [comment]
感謝作者~! 非常好的功能!
因為頻繁使用所以會發現很多及問題~
往後提出與上述建議再麻煩了! :P

**Comment by zanllp** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/4382aeb7-f21f-4966-913a-c37be200529f)
