### ISSUE TITLE
[Feature Request] Batch tag changing

### ISSUE THREAD

**Issue by Petermeinders** [zanllp/sd-webui-infinite-image-browsing#416]
**Problem**: Unable to tag multiple photos.
**Solution**: Add feature that allows all selected photos to be tagged instead of just one at a time.

**Replicate current situation:**
We can select groups of photos with ctrl or shift to move them from folder to folder, but if you select multiple photos and then change the tag by hovering and selecting it from the drop down menu then it ONLY changes on the clicked photo instead of all the actively selected photos.

**Comment by zanllp** [comment]
Already supported.
https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Change-log
