### ISSUE TITLE
文件夾名稱中有日文或韓文時，發送到文生圖會失效

### ISSUE THREAD

**Issue by Devon22** [zanllp/sd-webui-infinite-image-browsing#417]
感謝開發這個好用的軟體~

目前發現文件夾名稱中有日文或韓文時，發送到文生圖或圖生圖的選項會失效
以前的版本是會出現錯誤訊息，結果還是能成功發送
但目前最新版是無法成功發送了

**Comment by zanllp** [comment]
控制台/终端 有没有什么错误信息？截图发出来看看

我在本地试了下日文没什么问题

**Comment by Devon22** [comment]
sorry目前手邊只有舊版的錯誤訊息
![螢幕擷取畫面 2023-09-13 025336](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/95129064/8395da04-48fe-4638-ad39-bea17517b6fe)

**Comment by zanllp** [comment]
看起来是logger的问题，我先把这些logger的输出移除掉了，反正对你们来说用处不大

可以先升级到最新版本看看，后面再出问题的话，及时跟进

**Comment by Devon22** [comment]
已升級，但發送到文生圖或圖生圖的選項依舊沒有作用，測試過有日文及普通英數名稱的路徑都不行
大概是因為logger被移除的關係，這次沒有看到錯誤訊息

**Comment by zanllp** [comment]
能把图片发出来看看吗，我尝试下能不能复现

**Comment by Devon22** [comment]
不知道是怎麼回事，剛剛測試最新版是可以成功發送的，看來應該是沒問題了，感謝
