### ISSUE TITLE
刷新功能并不总是有用

### ISSUE THREAD

**Issue by liuyu-f** [zanllp/sd-webui-infinite-image-browsing#42]
查看文生图文件夹下的图片，然后到文生图生成一张图片，再回到图片浏览器，点击右上角的刷新没有反应，大概率需要重新打开一个标签，或者跳转到其他文件夹再跳转回来才行。

还有一个稳定的bug，重载前端后出错，打开任意硬盘提示 “ [WinError 123] 文件名、目录名或卷标语法不正确。: '/E:/' “此时包括搜索、最近记录等功能都不可使用，不过只要刷新一下页面功能就恢复正常。（非专业人士提供一个薄见，可能是页面重载某些地址变量刷新，但插件对地址的操作没有刷新？）

**Comment by liuyu-f** [comment]
提供线索：发现后台关闭后刷新依然可用且不会报错

**Comment by liuyu-f** [comment]
> 你可以更新下看看，刷新我复现不出来，但是我加了刷新后回到顶部。如果还出现问题你可以看下有没有api请求发出或者控制台报错。
> 
> 下面那个也你试下，如果还会的话最好录个屏截下图什么的。现在已知的是“还原上次记录”持久化好像有点问题？

不知道为什么，刷新问题我这里稳定复现，并且命令窗口没有任何提示。
而第二个情况我这里要么是像之前说的那样，要么现在重载前端后打开图片浏览器选项卡是空白，都是刷新一下页面才好。
怕下载出错，在这里直接下载安装也不行，不过可能是我个人出现这种状况，是的话请忽略。我能想到的可能是我的环境有问题，或者是[官方一键包](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases)的问题。

不过在这里提一个小功能，在图片右键选单中增加一项移动到保存文件夹功能，个人认为还是比较常用的，像文生图、图生图等文件夹毕竟只是生成图片的临时存放目录

**Comment by liuyu-f** [comment]
线索：到文生图浏览图片不要往下刷，此时生成图片，然后回到浏览器选项卡往下翻，刷到 “加载下一页” 被触发变灰，再刷新就正常刷新一次

**Comment by zanllp** [comment]
> > 你可以更新下看看，刷新我复现不出来，但是我加了刷新后回到顶部。如果还出现问题你可以看下有没有api请求发出或者控制台报错。
> > 下面那个也你试下，如果还会的话最好录个屏截下图什么的。现在已知的是“还原上次记录”持久化好像有点问题？
> 
> 不知道为什么，刷新问题我这里稳定复现，并且命令窗口没有任何提示。 而第二个情况我这里要么是像之前说的那样，要么现在重载前端后打开图片浏览器选项卡是空白，都是刷新一下页面才好。 怕下载出错，在这里直接下载安装也不行，不过可能是我个人出现这种状况，是的话请忽略。我能想到的可能是我的环境有问题，或者是[官方一键包](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases)的问题。
> 
> 不过在这里提一个小功能，在图片右键选单中增加一项移动到保存文件夹功能，个人认为还是比较常用的，像文生图、图生图等文件夹毕竟只是生成图片的临时存放目录

你是stable-diffusion-webui的最新版吗？

不是shell，是console这个不知道有没有报错。
<img width="621" alt="image" src="https://user-images.githubusercontent.com/25872019/234175289-f34bead1-d6dc-474e-a8ac-000c39dae02e.png">


移动文件夹过去本来感觉你们可以这样的 https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/40#issuecomment-1520157708  。不过看起来你们好像不止一个需要，我也加一个吧

**Comment by zanllp** [comment]
你的“重载”是指f5刷新页面?  我太没理解是什么意思。
如果是刷新后点击我们插件tab是一片空白的话，那可能是还没加载完成，浏览器同时只能加载6个，这个插件用了一些特殊的方法让可以使用vue写页面，但是也导致他的加载顺序是比其他插件后面的，而且体积比较大。

**Comment by zanllp** [comment]
那个支持了，我发现了一次特殊case下的刷新也修复了，其他等我能复现再说
<img width="326" alt="image" src="https://user-images.githubusercontent.com/25872019/234358401-ea6ce05b-6fbe-4b01-9572-df5218ca9751.png">

**Comment by liuyu-f** [comment]
> 那个支持了，我发现了一次特殊case下的刷新也修复了，其他等我能复现再说 <img alt="image" width="326" src="https://user-images.githubusercontent.com/25872019/234358401-ea6ce05b-6fbe-4b01-9572-df5218ca9751.png">

谢谢~，用的时候想不起来可以分屏，看到你的视频才想起来这用法233~
其他的bug我这里用视频展示下
https://user-images.githubusercontent.com/73892292/234867918-38e257a7-de81-4c60-8a31-0ab92ede67be.mp4

**Comment by liuyu-f** [comment]
不知道为什么，我上传的视频在网页上看不了，下载下来是可以看的。
还有两影响不大的bug

1：用 “Walk” 方式进入图片浏览界面，点击右上角的 “快速移动” 到其他文件夹，会发现标签页标题没有改变，此时点击刷新会回到原文件夹。
如进入 “Walk：文生图” 后点击右上角 “快速移动” 到 ‘图生图’ 文件夹，此时标签页标题依旧是 “Walk：文生图” ，点击刷新后会回到“Walk：文生图” 的图片浏览界面。

2：有多个标签页时，关闭正在显示的标签页，会自动跳转到左侧标签页，但关闭的是最左侧标签页时，内容处将什么都不显示，需要点击一下右侧其他标签页才显示其内容。

最后最后再提供一个思路哦，就是关闭最后一个标签页时可以不用提示，直接关闭并新建一个启动页。其实是我以前用360急速浏览器时的标签页的逻辑，个人感觉还挺方便的

**Comment by zanllp** [comment]
> 不知道为什么，我上传的视频在网页上看不了，下载下来是可以看的。 还有两影响不大的bug
> 
> 1：用 “Walk” 方式进入图片浏览界面，点击右上角的 “快速移动” 到其他文件夹，会发现标签页标题没有改变，此时点击刷新会回到原文件夹。 如进入 “Walk：文生图” 后点击右上角 “快速移动” 到 ‘图生图’ 文件夹，此时标签页标题依旧是 “Walk：文生图” ，点击刷新后会回到“Walk：文生图” 的图片浏览界面。
> 
> 2：有多个标签页时，关闭正在显示的标签页，会自动跳转到左侧标签页，但正在显示的是最左侧标签页并关闭后，将没有任何标签页获得焦点，此时内容处什么都不显示，需要点击一下右侧其他标签页才显示内容。
> 
> 最后最后再提供一个思路哦，就是关闭最后一个标签页时可以不用提示，直接关闭并新建一个启动页。这其实是我以前用360急速浏览器时养成的习惯，个人感觉还挺方便的

没事，我这边可以看。你这bug报的太棒了。这视频感觉比我演示视频做的好多了😂

**Comment by zanllp** [comment]
我重构了下刷新，你可以试下，之前是有条件会直接跳过刷新的，现在不会了，无论如何必须重新加载，刷新完会给你来个message提醒。

路径出错应该也没问题了。

walk模式强制不允许你点击面包屑的文件夹跳转，但是可以用快速移动。在walk模式下，无论你去到哪点击刷新就会回来这是正常的。因为本来就提供给你一个范围，然后让你不用进去退出就能查看这个范围内的所有图片。快速移动相当于给你开了新的范围

还有其他几个问题我后面再处理。

**Comment by liuyu-f** [comment]
很棒！~~刚才更新使用了下，，除了重载后默认面板显示有问题外，用着已经很流畅了！
