### ISSUE TITLE
Tab doesn't pop up

### ISSUE THREAD

**Issue by dongyun-kim-arch** [zanllp/sd-webui-infinite-image-browsing#421]
Hello,

I installed this extension in sd-webui, check the button to load it, and restart UI, but the tab doesn't show up.
I tried it in my 2 linux machines, but both are fail to make it appear.

When installing it, it doesn't give me any error message, so I am not sure why it doesn't work in my machines...

**Comment by zanllp** [comment]
Is there any error message in the browser console?

**Comment by le-khang** [comment]
I got the same error but when I delete the --skip-install in the webui-user.sh file (Commandline arguments) then restart SD the extension appears. Not sure about your case though.

**Comment by wlchn** [comment]
> I got the same issue but when I deleted the '--skip-install' from the 'webui-user.sh' file (under Commandline arguments) and then restarted SD, the extension appeared.

Resolved by deleted '--skip-install'.
