### ISSUE TITLE
儲存圖片...

### ISSUE THREAD

**Issue by FrankHGS** [zanllp/sd-webui-infinite-image-browsing#425]
是否可以自訂儲存圖片為複製 並不是移動 感謝!!

**Comment by zanllp** [comment]
有空我看下，最近搬家忙

**Comment by zanllp** [comment]
最近刚好在实现的一个功能可以解决这个问题

<img width="356" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/b33b0c9b-db24-43d3-9ff5-2f7b7b99bbb2">

**Comment by FrankHGS** [comment]
> 最近刚好在实现的一个功能可以解决这个问题
> 
哈哈!! 我看到了~!! 棒棒! ^^
