### ISSUE TITLE
open to walk mode menu missing after update

### ISSUE THREAD

**Issue by coldtoon** [zanllp/sd-webui-infinite-image-browsing#426]
Missing walk mode menu after updating and moving sd ai managers.App works fine otherwise.No errors reported. 
From a1111 autoinstaller Ai-ver.1.3.2>stability matrix Ai-ver.1.6.0 both using(sd-webui)

Before:
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/081707e0-773f-4964-8eec-4b62e328f7b9)

After: 
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/be4f1bed-81ef-4952-9816-7394c999544d)

**Comment by zanllp** [comment]
Please paste a screenshot of your path settings so that I can take a look. It should look like the image below.

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/6122cb2c-b3c8-4d44-9348-cbe33512e493)


Also, please provide the working directory for the "sd-webui" folder.

**Comment by coldtoon** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/86ae0a10-af61-4669-b57b-0b545ea6a10b)

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/5c1adcfe-4849-4c04-911a-08ae3133581b)

**Comment by coldtoon** [comment]
C:\Users\Cookie\Documents\StabilityMatrix\Packages\Stable Diffusion WebUI

**Comment by zanllp** [comment]
The settings you provided seem fine. However, I tried reproducing the issue after moving the sd-webui on my end, but I couldn't replicate it. Could you please check the browser console for any errors?

f12

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/fa397d14-5a8e-4ab0-8483-493ff8f78b8d)

**Comment by coldtoon** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/6c132cae-4187-449b-bda3-68bd3d5ed66c)

**Comment by coldtoon** [comment]
I can do discord call if needed

**Comment by coldtoon** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/aa04dc29-5463-40e6-8625-f916c60365fb)

**Comment by zanllp** [comment]
There is no desired information in the image. 

Can you provide a screenshot of it? As shown in the following image, check_path_exist may only appear after refreshing the page.

<img width="840" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/e3462319-a556-45f5-a730-43ad4e4f6b50">

**Comment by coldtoon** [comment]
not finding what you wanted
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/2e119027-5591-4548-b862-16cfb89d6e45)

**Comment by zanllp** [comment]
That shouldn't be the case. When you return to IIB from other tabs, it should also trigger this request. If it doesn't, there should be related errors in the console. Could you please try again and see if you can provide me with the requested information?

**Comment by zanllp** [comment]
Can you please provide a screenshot of the preview of global_setting first?

**Comment by coldtoon** [comment]
double click and open?

**Comment by coldtoon** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/c6ccf6ae-fabd-4806-aed3-37d2612c6351)

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/9cbfde32-a8d4-40e5-8936-8decc49c806d)

**Comment by coldtoon** [comment]
this is the ai manager:https://github.com/LykosAI/StabilityMatrix

**Comment by zanllp** [comment]
Not this one, I need something similar to the image below.

<img width="742" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/1748f4cc-34f1-4d42-adaf-eb375e1c71ce">

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/7b9491ad-909c-407e-9fee-0966c92334c6)

**Comment by coldtoon** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/3c8dec2a-a1ed-4ba3-a0bd-a1a21bf5e422)

**Comment by coldtoon** [comment]
that's as close as I can get I don't know any of this and the browser don't have that preview option

**Comment by coldtoon** [comment]
wait is this response it?
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/76ab27a7-564d-4d5f-8079-57d80fe53d88)

**Comment by zanllp** [comment]
I made some modifications. Now, regardless of the situation, you are allowed to add the "walk" mode folder. For now, please manually add it as a workaround solution. I feel that it would take too long to address the entire problem.

**Comment by coldtoon** [comment]
so update and the option should appear?

**Comment by zanllp** [comment]
> wait is this response it? ![image](https://user-images.githubusercontent.com/12128712/268471671-76ab27a7-564d-4d5f-8079-57d80fe53d88.png)


Yes. You can click on "raw" first, and then copy the content inside for me.
<img width="1136" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/c231657a-e4ac-41d7-a438-09c76157ff6c">

**Comment by zanllp** [comment]
> so update and the option should appear?

Certainly. You need to upgrade the extension first for it to take effect.

**Comment by coldtoon** [comment]
<html><body>

    <div id="mount"><div class="network-monitor"><div><div class="monitor-panel"><span id="netmonitor-toolbar-container"><span class="devtools-toolbar devtools-input-toolbar"></span></span></div></div></div></div><span id="netmonitor-toolbar-container"><span class="devtools-toolbar devtools-input-toolbar"><span class="devtools-separator"></span><div class="devtools-searchbox"><input class="devtools-filterinput" placeholder="Filter URLs" type="search" value="glo"></div></span></span><span id="netmonitor-toolbar-container"><span class="devtools-toolbar devtools-input-toolbar"><span class="devtools-separator"></span></span></span><span id="netmonitor-toolbar-container"><span class="devtools-toolbar devtools-input-toolbar"><span class="devtools-separator"></span><div class="requests-list-filter-buttons"></div></span></span><span id="netmonitor-toolbar-container"><span class="devtools-toolbar devtools-input-toolbar"><span class="devtools-separator"></span><label class="devtools-checkbox-label devtools-cache-checkbox" title="Disable HTTP cache"><input id="devtools-cache-checkbox" class="devtools-checkbox" type="checkbox">Disable Cache</label><span class="devtools-separator"></span></span></span><span id="netmonitor-toolbar-container"><span class="devtools-toolbar devtools-input-toolbar"><span class="devtools-separator"></span></span></span><div class="uncontrolled" role="presentation"><div class="split-box vert devtools-responsive-container" style="--split-box-controlled-panel-size: 550;"><div class="uncontrolled" role="presentation"><div class="request-list-container"><div class="requests-list-scroll" style="width: 993px; height: 469px;">





<div class="requests-list-scroll" style="width: 993px; height: 469px;"><div class="requests-list-anchor"></div></div><div class="devtools-toolbar devtools-toolbar-bottom"></div><div class="uncontrolled" role="presentation"><div class="split-box vert devtools-responsive-container" style="--split-box-controlled-panel-size: 550;"><div class="uncontrolled" role="presentation"><div class="request-list-container"><div class="devtools-toolbar devtools-toolbar-bottom"><div class="status-bar-label requests-list-network-summary-count" title="Number of requests">2 requests</div><div class="status-bar-label requests-list-network-summary-transfer" title="Size/transferred size of all requests">857 B / 1.01 kB transferred</div><div class="status-bar-label requests-list-network-summary-finish" title="Total time needed to load all requests">Finish: 10.91 s</div><div class="status-bar-label dom-content-loaded" title="Time when “DOMContentLoad” event occurred">DOMContentLoaded: 867 ms</div><div class="status-bar-label load" title="Time when “load” event occurred">load: 969 ms</div></div></div></div></div></div><div role="presentation" style="flex: 0 0 1px;" class="splitter"></div><div class="controlled" style="max-width: 80%; min-width: 50px; width: 543px;" role="presentation"><div class="network-details-bar"><div class="devtools-sidebar-tabs"><div class="tabs "><nav class="tabs-navigation"></nav></div></div></div></div><li class="tabs-menu-item panel-with-code " role="presentation"><span class="devtools-tab-line"></span></li><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="response-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="response-tab"><div class="tab-panel panel-with-code"><div class="panel-container"><div class="devtools-toolbar devtools-input-toolbar"><div class="devtools-searchbox"><input class="devtools-filterinput" placeholder="Filter properties" type="search" value=""></div></div><div tabindex="0"></div></div></div></div><div id="mount"><div class="network-monitor"><div><div class="monitor-panel"><div class="split-box vert devtools-responsive-container" style="--split-box-controlled-panel-size: 543;"><div class="controlled" style="max-width: 80%; min-width: 50px; width: 543px;" role="presentation"><div class="network-details-bar"><div class="devtools-sidebar-tabs"><div class="tabs "><div class="panels"><div id="response-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="response-tab"><div class="tab-panel panel-with-code"><div class="panel-container"><div class="editor-row-container"><div class="editor-row-container"><div class="source-editor-mount devtools-monospace"><div class="CodeMirror cm-s-mozilla" style="--caret-blink-time: 530ms;"><div style="overflow: hidden; position: relative; width: 3px; height: 0px; top: 4px; left: 50px;"><textarea style="position: absolute; bottom: -1em; padding: 0px; width: 1px; height: 1em; outline: none;" wrap="off" autocorrect="off" autocapitalize="none" spellcheck="false" readonly="readonly" tabindex="0"></textarea></div><div class="CodeMirror-hscrollbar" tabindex="-1" cm-not-content="true" style="display: block; right: 0px; left: 46px;"><div style="height: 100%; min-height: 1px; width: 5492px;"></div></div><div class="CodeMirror-scroll" tabindex="-1" draggable="true"><div class="CodeMirror-sizer" style="margin-left: 46px; margin-bottom: -17px; border-right-width: 33px; min-height: 21px; min-width: 5491.8px; padding-right: 0px; padding-bottom: 17px;"><div style="position: relative; top: 0px;"><div class="CodeMirror-lines" role="presentation"><div style="position: relative; outline: none;" role="presentation"><div class="CodeMirror-measure"><pre class="CodeMirror-line-like"><span></span></pre></div><div class="CodeMirror-measure"></div><div style="position: relative; z-index: 1;"></div><div class="CodeMirror-cursors"><div class="CodeMirror-cursor" style="left: 4px; top: 0px; height: 12.8px;"></div></div><div class="CodeMirror-code" role="presentation"><div style="position: relative;" class="CodeMirror-activeline"><div class="CodeMirror-activeline-background CodeMirror-linebackground"></div><div class="CodeMirror-gutter-background CodeMirror-activeline-gutter" style="left: -46px; width: 46px;"></div><div class="CodeMirror-gutter-wrapper CodeMirror-activeline-gutter" style="left: -46px;"><div class="CodeMirror-linenumber CodeMirror-gutter-elt" style="left: 0px; width: 21px;">1</div></div><pre class=" CodeMirror-line " role="presentation"><span role="presentation">{<span class="cm-string cm-property">"global_setting"</span>:{<span class="cm-string cm-property">"show_progress_type"</span>:<span class="cm-string">"TAESD"</span>,<span class="cm-string cm-property">"sd_model_checkpoint"</span>:<span class="cm-string">"yiffymix_V32.safetensors [fc344cebba]"</span>,<span class="cm-string cm-property">"sd_checkpoint_hash"</span>:<span class="cm-string">"fc344cebba58149d52794233a26985e4778081058f6ee1b1eb73dd612f92faa5"</span>,<span class="cm-string cm-property">"disabled_extensions"</span>:[<span class="cm-string">"DreamArtist-sd-webui-extension"</span>,<span class="cm-string">"sd_civitai_extension"</span>],<span class="cm-string cm-property">"disable_all_extensions"</span>:<span class="cm-string">"none"</span>},<span class="cm-string cm-property">"cwd"</span>:<span class="cm-string">"C:\\Users\\Cookie\\Documents\\StabilityMatrix\\Packages\\Stable Diffusion WebUI\\extensions\\sd-webui-infinite-image-browsing"</span>,<span class="cm-string cm-property">"is_win"</span>:<span class="cm-atom">true</span>,<span class="cm-string cm-property">"home"</span>:<span class="cm-string">"C:\\Users\\Cookie"</span>,<span class="cm-string cm-property">"sd_cwd"</span>:<span class="cm-string">"C:\\Users\\Cookie\\Documents\\StabilityMatrix\\Packages\\Stable Diffusion WebUI"</span>,<span class="cm-string cm-property">"all_custom_tags"</span>:[{<span class="cm-string cm-property">"name"</span>:<span class="cm-string">"like"</span>,<span class="cm-string cm-property">"score"</span>:<span class="cm-number">0</span>,<span class="cm-string cm-property">"type"</span>:<span class="cm-string">"custom"</span>,<span class="cm-string cm-property">"count"</span>:<span class="cm-number">0</span>,<span class="cm-string cm-property">"id"</span>:<span class="cm-number">1</span>,<span class="cm-string cm-property">"display_name"</span>:<span class="cm-atom">null</span>}],<span class="cm-string cm-property">"extra_paths"</span>:[{<span class="cm-string cm-property">"path"</span>:<span class="cm-string">"C:\\Users\\Cookie\\Documents\\StabilityMatrix\\Packages\\Stable Diffusion WebUI\\outputs"</span>,<span class="cm-string cm-property">"type"</span>:<span class="cm-string">"scanned"</span>}],<span class="cm-string cm-property">"enable_access_control"</span>:<span class="cm-atom">null</span>,<span class="cm-string cm-property">"launch_mode"</span>:<span class="cm-string">"sd"</span>}</span></pre></div></div></div></div></div></div><div style="position: absolute; height: 33px; width: 1px; border-bottom: 17px solid transparent; top: 21px;"></div><div class="CodeMirror-gutters" style="height: 71px; left: 0px;"><div class="CodeMirror-gutter CodeMirror-linenumbers" style="width: 29px;"></div><div class="CodeMirror-gutter CodeMirror-foldgutter"></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>
    
  


</body>
</html>

**Comment by coldtoon** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/0b95fd67-495d-4c51-8987-50bfe24c2f04)

**Comment by coldtoon** [comment]
yay it fixed it I think 
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/9e290209-63af-4c75-bb0b-280b30fb6a17)

**Comment by zanllp** [comment]
> Disable Cache
> 2 requests
> 857 B / 1.01 kB transferred
> Finish: 10.91 s
> DOMContentLoaded: 867 ms
> load: 969 ms
> * 
> <textarea style="position: absolute; bottom: -1em; padding: 0px; width: 1px; height: 1em; outline: none;" wrap="off" autocorrect="off" autocapitalize="none" spellcheck="false" readonly="readonly" tabindex="0"></textarea>
> 1
> {"global_setting":{"show_progress_type":"TAESD","sd_model_checkpoint":"yiffymix_V32.safetensors [fc344cebba]","sd_checkpoint_hash":"fc344cebba58149d52794233a26985e4778081058f6ee1b1eb73dd612f92faa5","disabled_extensions":["DreamArtist-sd-webui-extension","sd_civitai_extension"],"disable_all_extensions":"none"},"cwd":"C:\\Users\\Cookie\\Documents\\StabilityMatrix\\Packages\\Stable Diffusion WebUI\\extensions\\sd-webui-infinite-image-browsing","is_win":true,"home":"C:\\Users\\Cookie","sd_cwd":"C:\\Users\\Cookie\\Documents\\StabilityMatrix\\Packages\\Stable Diffusion WebUI","all_custom_tags":[{"name":"like","score":0,"type":"custom","count":0,"id":1,"display_name":null}],"extra_paths":[{"path":"C:\\Users\\Cookie\\Documents\\StabilityMatrix\\Packages\\Stable Diffusion WebUI\\outputs","type":"scanned"}],"enable_access_control":null,"launch_mode":"sd"}

It seems that this is where the problem lies. When I was gathering your local settings, a lot of information was missing, which prevented me from knowing which folders were preset in sd-webui. However, I can't understand why.

**Comment by coldtoon** [comment]
odd the only diff I can think of is that it don't launch in admin mode

**Comment by zanllp** [comment]
It's also possible that it was hooked by other plugins.

**Comment by coldtoon** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/a3873676-b7a3-4e03-a559-cc9b2bf30ace)

**Comment by coldtoon** [comment]
civitai was being really spamy so I had to disable it and dream artist won't boot so..idk if it's civitai or something else

**Comment by coldtoon** [comment]
also there is some new plug-ins built in

**Comment by zanllp** [comment]
For now, let's leave it at that. I'll continue with the next step once I receive enough feedback from people. I've been busy lately as well.

**Comment by coldtoon** [comment]
Thank you for the help if you need anything else just add to this

**Comment by coldtoon** [comment]
oh I think I found it unless an update you did fixed it
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/7be53ff0-8d1b-4cce-974a-41dc00855002)

**Comment by coldtoon** [comment]
was unchecking forbid url option for trying to fix open out paint and when I went to transfer the img2img to it from your app. you app seems to have the rest of the stuff

**Comment by coldtoon** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12128712/57de07bb-c222-4dcf-b1be-b310a56aa14a)
