### ISSUE TITLE
發送到... 不起作用?

### ISSUE THREAD

**Issue by FrankHGS** [zanllp/sd-webui-infinite-image-browsing#429]
發送到 文生圖 圖生圖 局部重繪...等 不起作用?

**Comment by FrankHGS** [comment]
咦? 我似乎是隱藏頁籤的關係?
一直都是使用分頁啟動 想說隱藏頁籤節省空間...

**Comment by zanllp** [comment]
隐藏掉的话确实不行，发送到xxx依赖于挂载sd-webui前端的按钮进行触发，隐藏掉就没了
