### ISSUE TITLE
Can not generate IIB SECRET_KEY in paperspace environment

### ISSUE THREAD

**Issue by JohjiYamada** [zanllp/sd-webui-infinite-image-browsing#430]
it seems when it installed, .env.example is placed in the root of it's extension folder.
however, in paperspace env, it's not allowed to place no name file..
is there any ways to avoid this situation except turning off the gradio auth?

thanks

**Comment by zanllp** [comment]
``` bash
# in webui-user.sh
export IIB_SECRET_KEY=pw
```

and then
`./.webui-user.sh`


or

`export IIB_SECRET_KEY=pw && ./webui.sh`
