### ISSUE TITLE
希望在浏览大图时候,能有删除当前浏览的图片

### ISSUE THREAD

**Issue by tim9292654** [zanllp/sd-webui-infinite-image-browsing#432]
感觉每次看到有不好的图,要退出浏览大图模式,才能右键删除,感觉太麻烦了,希望能添加该功能

**Comment by zanllp** [comment]
这个会想办法解决。现在其实是在虚拟列表的同时给你实现可以翻页大图查看，这个实现很复杂我使用了很多hack才实现的，但代价是在点开查看后到第一张图片不能直接删除不然会出现预期外的bug，不过后续的第二张第三张可以
