### ISSUE TITLE
圖片搜尋似乎有問題?

### ISSUE THREAD

**Issue by FrankHGS** [zanllp/sd-webui-infinite-image-browsing#434]
兩種搜尋都沒有應該的結果... 請檢查 感謝!

**Comment by zanllp** [comment]
给个复现例子

**Comment by FrankHGS** [comment]
![螢幕擷取畫面 2023-09-26 110821](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/132704944/5e522aa8-219c-4ff7-a427-7c849fbb885c)

比如最簡易的單一尺寸搜尋 這會是甚麼問題?

**Comment by FrankHGS** [comment]
期間曾重新安裝過SD 但在不同的位置安裝 也有歸位 對於搜尋會有影響嗎?

**Comment by FrankHGS** [comment]
看來似乎是搜尋索引的問題 不能重新索引嗎?

**Comment by zanllp** [comment]
支持了 https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Change-log#%E4%B8%AD%E6%96%87

**Comment by FrankHGS** [comment]
> 支持了 https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Change-log#%E4%B8%AD%E6%96%87

棒棒!! 終於復活了~ 3Q~ ^O^

**Comment by zanllp** [comment]
> 咦! 之前自訂的標籤也遺失了?

能提供下如何复现这个问题吗（可以先更新下），重新构建索引是不会对custom类型的有影响的，

**Comment by FrankHGS** [comment]
> > 咦! 之前自訂的標籤也遺失了?
> 
> 能提供下如何复现这个问题吗（可以先更新下），重新构建索引是不会对custom类型的tag有影响的，

嗯嗯! 我的意思是重新安裝前的自訂標籤遺失了...不能在新路徑上復原 QQ
