### ISSUE TITLE
Unable to delete from browser

### ISSUE THREAD

**Issue by Dropbear67** [zanllp/sd-webui-infinite-image-browsing#438]
The "delete" option is greyed out for me.
.env file has 
IIB_ACCESS_CONTROL is set to disable 
IIB_ACCESS_CONTROL_PERMISSIONS is set to read-write and uncommented

**Comment by Dropbear67** [comment]
apologies.. it seems the delete is greyed out only in the context menu, right clicking on an image i can select delete

**Comment by zanllp** [comment]
In the latest version, I have removed this restriction, allowing for direct deletion of the first image even in full-screen preview mode.
