### ISSUE TITLE
Feature request: ignore selected file types

### ISSUE THREAD

**Issue by nightgolfer** [zanllp/sd-webui-infinite-image-browsing#44]
I usually make my setup dump .txt files with prompt info and metadata along with my rendered images. So in my image folders, there will be an [image] followed by a [txt] file, then [img], [txt], etc.

When browsing my folders in Infinite Image Browser, all my TXT files are visible as well. It would be great if there was a way to tell the extension to ignore (not show) certain file types, in my case .txt files. 

As an image browser, I only want it to show me the images.

![Screenshot 2023-04-23 16 29 58](https://user-images.githubusercontent.com/32328229/233845775-fe75b758-754a-4437-bfc1-036a6ce1d0ab.png)

**Comment by zanllp** [comment]
I need to think about how to handle this situation properly.
 In the meantime, you may want to try using an image search instead, which only displays images.

**Comment by zanllp** [comment]
In the latest commit, all files except folders and images will be hidden by default.
