### ISSUE TITLE
Feature request, Select multiple images 

### ISSUE THREAD

**Issue by Tobe2d** [zanllp/sd-webui-infinite-image-browsing#45]
Can you add Select multiple images at once?

It will be useful for cleaning up and deleting many images in one time. as of now I have to right click and delte one by one ;-(

**Comment by zanllp** [comment]
You can delete multiple files simultaneously by holding down Shift, Ctrl, or Cmd.
 It looks like I need to add more information to the document.😂


https://user-images.githubusercontent.com/25872019/234063399-54f1a332-4f38-4511-a38f-0bf6c6a32c72.mp4
