### ISSUE TITLE
DB uses absolute paths, leading to issues when moving sd-webui installation to new drive

### ISSUE THREAD

**Issue by VerstandInvictus** [zanllp/sd-webui-infinite-image-browsing#463]
As part of a computer rebuild/migration, I just moved my entire sd-webui install to a new drive with a new drive letter (on Windows). This caused all custom tags to be lost from my images in IIB.

I was able to fix this by checking `iib.db` with a SQLite editor and observing that in the `folders` and `image` tables, all paths were absolute, meaning that now that my installation was using relative output paths under `S:\` instead of `O:\`, as far as IIB was concerned the images I'd tagged with custom tags no longer existed.

I was able to fix this by running the following update queries, which remapped everything and brought back the custom tags:
```
UPDATE folders
SET path = REPLACE(path, "O:\", "S:\");

UPDATE image
SET path = REPLACE(path, "O:\", "S:\");
```

However, for a less technical user, this might seriously bite them and they wouldn't be able to fix it. It's not just drive letters, this would also happen with root folders above `webui`, for example if someone moved their sd-webui installation into a subfolder.

Is it possible to convert IIB to always use relative paths, at least for folders under `webui` or those inferred from the sd-webui configuration?

**Comment by zanllp** [comment]
please refer to https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Proper-Folder-Migration-to-Avoid-Data-Loss---%E6%AD%A3%E7%A1%AE%E7%9A%84%E8%BF%81%E7%A7%BB%E6%96%87%E4%BB%B6%E5%A4%B9%E9%81%BF%E5%85%8D%E6%95%B0%E6%8D%AE%E4%B8%A2%E5%A4%B1
