### ISSUE TITLE
权限控制可以做的更加精细一些？

### ISSUE THREAD

**Issue by yinjiahuidada** [zanllp/sd-webui-infinite-image-browsing#464]
希望支持，权限控制的力度能增加，以下可能是比较理想的模式

1. 权限控制参数 `IIB_ACCESS_CONTROL_PERMISSION` 可以修改为：
    [1] read: 只读
    [2] download: 读 + 下载
    [3] wirte: 读 + 下载 + 删除/修改
2. 除 `IIB_SECRET_KEY` 控制进入图片浏览外，可以新增download 和 write 权限的密码，
    比如: 在权限控制为`donwload` 时, 在下载或删除的时候需要密码

**Comment by zanllp** [comment]
密码读写分离我可以理解，但是下载为什么也要单独的，既然能看到图片直接右键保存不就行了
