### ISSUE TITLE
Can the extension function without the web UI?

### ISSUE THREAD

**Issue by Linaqruf** [zanllp/sd-webui-infinite-image-browsing#47]
Hi, great job on the extension! I just wanted to know if this extension can run separately and independently from the web UI, like ImJoy_Elfinder or FiftyOne? Thanks!

**Comment by zanllp** [comment]
Of course it is supported, and almost all functions can be used normally.

```bash
git clone https://github.com/zanllp/sd-webui-infinite-image-browsing.git
cd sd-webui-infinite-image-browsing
pip install -r requirements.txt
python app.py --port=7888 --sd_webui_config="your sd_webui config path"
```

## sd_webui_config
`sd_webui_conf` is optional and is used to help the plugin know which folders to scan. 

You can pass the `config.json` file located in the sd-webui root directory directly. 

You can also pass partial parameters, like this:

```json
{
    "outdir_txt2img_samples": "C:\\Users\\zanllp\\Desktop\\sd-remote-save\\txt2img-images",
    "outdir_img2img_samples": "C:\\Users\\zanllp\\Desktop\\sd-remote-save\\img2img-images",
    "outdir_extras_samples": "C:\\Users\\zanllp\\Desktop\\sd-remote-save\\extras-images",
}
```

Also, you can choose not to pass this parameter, but then you will need to manually open each folder, and the image search feature will not be available to you

## The plugin will scan the values corresponding to these keys in the configuration file.
```
 "outdir_txt2img_samples",
 "outdir_img2img_samples", 
 "outdir_save",
 "outdir_extras_samples",
 "outdir_grids",
 "outdir_img2img_grids",
 "outdir_samples",
 "outdir_txt2img_grids",
```

**Comment by Linaqruf** [comment]
Awesome, thankyou! It works.
![image](https://user-images.githubusercontent.com/50163983/234517754-3e64ff7d-73fa-49cb-9787-54bf82bf6d43.png)

**Comment by k0ala991** [comment]
Standalone mode is very cool! Love being able to specify a custom json.

In addition to the instructions above, I also needed to pip install pillow

**Comment by zanllp** [comment]
> Standalone mode is very cool! Love being able to specify a custom json.
> 
> In addition to the instructions above, I also needed to pip install pillow

What does 'specify a custom json' mean? I didn't quite understand it, so if there is indeed a need for it, you can submit a feature request. The issue indeed exists if Pillow is not installed, but since it is widely used, I did not include it in requirements.txt. I will add it later.

**Comment by Loli-Kyn** [comment]
How did you do it?
![Скриншот 18-06-2023 224246](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/52761837/5b6bd52d-5526-4b1e-beba-1ce9c165cfe5)

> Awesome, thankyou! It works. ![image](https://user-images.githubusercontent.com/50163983/234517754-3e64ff7d-73fa-49cb-9787-54bf82bf6d43.png)

**Comment by WSH032** [comment]
> How did you do it? ![Скриншот 18-06-2023 224246](https://user-images.githubusercontent.com/52761837/246688090-5b6bd52d-5526-4b1e-beba-1ce9c165cfe5.jpg)

@Loli-Kyn 
First, if you want to use shell in Jupyter, use `!git` instead of `git`

So, the code is
```
!git clone https://github.com/zanllp/sd-webui-infinite-image-browsing.git
%cd sd-webui-infinite-image-browsing
!pip install -r requirements.txt
!python app.py --port=7888 --sd_webui_config="your sd_webui config path"
```

Second, when using on Colab, you need `output.serve_kernel_port_as_iframe(7888)` to show the content, like what linaqruf do

**Comment by Loli-Kyn** [comment]
@WSH032 

how do I start the diffusion itself then. After all, in colab the commands are executed sequentially, not all at once 
![Скриншот 19-06-2023 211506](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/52761837/faa61c78-7cb5-4427-99c2-108fccac65f6)

**Comment by WSH032** [comment]
> @WSH032
> 
> how do I start the diffusion itself then. After all, in colab the commands are executed sequentially, not all at once ![Скриншот 19-06-2023 211506](https://user-images.githubusercontent.com/52761837/246906676-faa61c78-7cb5-4427-99c2-108fccac65f6.jpg)

refer to https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/250#issuecomment-1597513330

You can use multi-thread
```python
from google.colab.output import serve_kernel_port_as_iframe, serve_kernel_port_as_window
from threading import Thread

!git clone https://github.com/zanllp/sd-webui-infinite-image-browsing.git
%cd sd-webui-infinite-image-browsing
!pip install -r requirements.txt

port = 7888  # your port
config_file = "your sd_webui config path"

def run_app():
    !python app.py --port={port} --sd_webui_config={config_file}

thread = Thread(target=run_app)
thread.start()
serve_kernel_port_as_iframe(port)

# thread.join()  # if you want execute synchronously
```

**Comment by Loli-Kyn** [comment]
@WSH032 
Multithreading doesn't work
Yes, I saw comment #250.
I tried running it, but it doesn't show my pictures. It needs to be set up, but I don't know how. I tried connecting to google drive, but there are no folders in colab, so I don't know why...
I think it would be easier for me to figure out how multithreading works.
![Скриншот 20-06-2023 021857](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/52761837/6520dbf8-cb90-4363-9320-96fa468e4776)

**Comment by WSH032** [comment]
@Loli-Kyn 
The issus we are discussing now is about jupyter notebook using.
I guess it is not appropriate to discuss it here, because here is about `Standalone Operation` issue

I will continue to discuss in https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/250

**Comment by pto2k** [comment]
Hello,
I followed these steps to setup the standalone version.

> git clone https://github.com/zanllp/sd-webui-infinite-image-browsing.git
> cd sd-webui-infinite-image-browsing
> pip install -r requirements.txt

but I met the black page when open it in browser

> It seems to have failed to load. You can try refreshing the page.
> If that doesn't work, click on [FAQ](https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/90) for help

My CMD output:

> d:\Repo\sd-webui-infinite-image-browsing>python app.py --port=7888 --extra_paths d:\Repo\stable-diffusion-webui\extensions\OneButtonPrompt\automated_outputs\txt2img\
> ←[32mINFO←[0m:     Started server process [←[36m3604←[0m]
> ←[32mINFO←[0m:     Waiting for application startup.
> ←[32mINFO←[0m:     Application startup complete.
> ←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:7888←[0m (Press CTRL+C to quit)
> ←[32mINFO←[0m:     127.0.0.1:8609 - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
> ←[32mINFO←[0m:     127.0.0.1:8609 - "←[1mGET /assets/index-77d97794.js HTTP/1.1←[0m" ←[32m200 OK←[0m
> ←[32mINFO←[0m:     127.0.0.1:8610 - "←[1mGET /assets/index-618900f2.css HTTP/1.1←[0m" ←[32m200 mK←[0
> ←[32mINFO←[0m:     127.0.0.1:8609 - "←[1mGET /favicon.ico HTTP/1.1←[0m" ←[31m404 Not Found←[0m

The log.log file in the app folder stays empty so nothing is there.
I did try some suggestions from the FAQ page but had no luck with them.

Any suggestions?

Thank you!

**Comment by zanllp** [comment]
> Hello, I followed these steps to setup the standalone version.
> 
> > git clone https://github.com/zanllp/sd-webui-infinite-image-browsing.git
> > cd sd-webui-infinite-image-browsing
> > pip install -r requirements.txt
> 
> but I met the black page when open it in browser
> 
> > It seems to have failed to load. You can try refreshing the page.
> > If that doesn't work, click on [FAQ](https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/90) for help
> 
> My CMD output:
> 
> > d:\Repo\sd-webui-infinite-image-browsing>python app.py --port=7888 --extra_paths d:\Repo\stable-diffusion-webui\extensions\OneButtonPrompt\automated_outputs\txt2img
> > ←[32mINFO←[0m:     Started server process [←[36m3604←[0m]
> > ←[32mINFO←[0m:     Waiting for application startup.
> > ←[32mINFO←[0m:     Application startup complete.
> > ←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:7888←[0m (Press CTRL+C to quit)
> > ←[32mINFO←[0m:     127.0.0.1:8609 - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
> > ←[32mINFO←[0m:     127.0.0.1:8609 - "←[1mGET /assets/index-77d97794.js HTTP/1.1←[0m" ←[32m200 OK←[0m
> > ←[32mINFO←[0m:     127.0.0.1:8610 - "←[1mGET /assets/index-618900f2.css HTTP/1.1←[0m" ←[32m200 mK←[0
> > ←[32mINFO←[0m:     127.0.0.1:8609 - "←[1mGET /favicon.ico HTTP/1.1←[0m" ←[31m404 Not Found←[0m
> 
> The log.log file in the app folder stays empty so nothing is there. I did try some suggestions from the FAQ page but had no luck with them.
> 
> Any suggestions?
> 
> Thank you!

Can you please refer to the image below and open the browser's console to see if there are any error messages?

<img width="1266" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/db61974f-6545-4692-8e89-84220531e42d">

**Comment by pto2k** [comment]
Hello~
I found 2 errors in the console... Does it help to locate the cause? Thanks!

<img width="1496" alt="Snipaste_2023-07-17_20-15-21" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/4364117/23e433d5-f69c-4f6f-a468-24997329d315">

**Comment by zanllp** [comment]
> Hello~ I found 2 errors in the console... Does it help to locate the cause? Thanks!
> 
> <img alt="Snipaste_2023-07-17_20-15-21" width="1496" src="https://user-images.githubusercontent.com/4364117/253937090-23e433d5-f69c-4f6f-a468-24997329d315.png">

<img width="1153" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/24d041f0-6250-4c7d-ad22-f2a8a8fd5acf">
Can you try click 'disable cache', then refreshing the page and see if the problem still occurs?
<img width="161" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/d4697d7f-d450-4a12-856c-68fdbb4ef531">

**Comment by pto2k** [comment]
Hi, 
I tried disable that but it did not help.
I also tried loading it in another fresh browser Firefox and had same issue.

IIB inside A1111 web ui works fine.

**Comment by zanllp** [comment]
@pto2k 

A strange error, perhaps due to dependency version issue. You could try using venv to see if it helps.
```bash
git clone https://github.com/zanllp/sd-webui-infinite-image-browsing.git
cd sd-webui-infinite-image-browsing
python -m venv venv
venv\Scripts\activate.bat # or venv/bin/Activate.ps1 , source venv/bin/activate ...  
pip install -r requirements.txt
python app.py --port=7888 --sd_webui_config="your sd_webui config path"
```

If all else fails, you can try using the desktop app version of IIB. https://github.com/zanllp/sd-webui-infinite-image-browsing/releases/tag/v0.2.0

**Comment by ore-** [comment]
@pto2k I had the same issue. worked for me after updating windows registry per - https://stackoverflow.com/questions/64013643/failed-to-load-module-script-the-server-responded-with-a-non-javascript-mime-ty

**Comment by pto2k** [comment]
@ore-  Thank you very much! That works.

**Comment by kernel55** [comment]
where is the --listen,I learned to call the server all the way.

**Comment by Fone520** [comment]
> Awesome, thankyou! It works. ![image](https://user-images.githubusercontent.com/50163983/234517754-3e64ff7d-73fa-49cb-9787-54bf82bf6d43.png)

Can jupyter lab do this?
