### ISSUE TITLE
是否可以增加独立模式下的移动端适配？

### ISSUE THREAD

**Issue by hmwz009** [zanllp/sd-webui-infinite-image-browsing#470]
无边图像浏览的独立模式非常赞，我经常在微信内使用来管理我的SD。如果可以稍微调增一下CSS，就更完美了。

我自己尝试修改我本地的IIB的vue代码，但是无法生效。
如果作者方便的话，希望可以考虑一下这个请求。

这是我自己写的stackView页面的css修改部分。

@media screen and (max-width: 768px) {
    .location-bar{
      display: block;
      padding: 4px;
      height: 70px;
    }
    .location-bar .action{
        justify-content: space-between;
    }
    .view{
        height: calc(100vh - 110px)
    }
  }
  
目前不适配情况下，页面有些许错误。

![微信图片_20231123005752](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/3301806/5513c076-1426-45a6-90e8-216de11d8518)

修改后

![微信图片_20231123011700](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/3301806/954fc26e-0f14-4564-9ac4-4049adcb2d49)

**Comment by zanllp** [comment]
我会专门找个时间优化
