### ISSUE TITLE
Language selection in settings / 在設定中選擇語言

### ISSUE THREAD

**Issue by ManHinnn0509** [zanllp/sd-webui-infinite-image-browsing#473]
首先感謝大大寫了這個插件，老實說很好用，方便也省時間，執行速度也快。
不過我其實想用英文版的，我看了一下代碼，似乎是會抓瀏覽器的語言來判斷用什麼語言。（我的瀏覽器是用中文的）
希望能新增設定自行選擇用什麼語言。
謝謝！

Hello, thanks for creating this extension. It's fast and convenience, saved some time from browsing the image files.
However, I would like to use the extension in English, but my browser is set to Traditional Chinese and the extension is loaded with Chinese language.
Could you please add option so that we can select what language to use in the extension?
Thanks!

**Comment by zanllp** [comment]
<img width="607" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/f66175cc-c1b1-49e0-bea1-7e9e9a827a33">

**Comment by ManHinnn0509** [comment]
遠在天邊，近在眼前，我沒想到我一直也沒看到全域設定 orz

感謝大大幫忙，剛剛設定好了，不過想問一下，tab那邊的名字也有機會可以變成英文嗎?

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/79153615/b4ac304a-f2dd-4525-84af-87d43025643b)

**Comment by zanllp** [comment]
这个得创建个.env文件，然后重启下sd-webui
<img width="890" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/9182707a-a01f-44ec-af8b-0a2c5df82dc7">

**Comment by ManHinnn0509** [comment]
有了，感謝大大的幫忙，很有效率！
