### ISSUE TITLE
[Feature Request] Web Service

### ISSUE THREAD

**Issue by ThesiiNCey** [zanllp/sd-webui-infinite-image-browsing#475]
is it Possible to make this Standalone app as Linux Application to run it as Website behind a Reverse proxy ? like Nginx

Needed Features:
1. Installable as Web Service with Flask ?
2. Add a Login Feature with an API for Stable Diffusion to Push Images to the Web Service
3. Login Feature for Users

Your Gallery will be great as Web Gallery overall with this Features

**Comment by zanllp** [comment]
Have you read issue #47？

**Comment by zanllp** [comment]
At the moment, we do not have any plans to add a login system to IIB. However, we do plan to implement support for configuring multiple keys simultaneously in the future, along with assigning different permissions to these keys. If you are familiar with coding, you can also implement your own login authentication service and gateway forwarding to fulfill your requirements.
