### ISSUE TITLE
Feature request: Fullscreen View button in WebUI

### ISSUE THREAD

**Issue by ilcane87** [zanllp/sd-webui-infinite-image-browsing#479]
I was surprised to find out that in the WebUI extension you can't go full screen when viewing images, you are restricted to the area below the extensions bar.
I know you can open an image in a new window, but from there you can't proceed to the next or previous image like you do when viewing within the extension.

However, you can get full screen while comparing images, using this button on the right:

![2023-12-10 12_19_23-Stable Diffusion](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/34897042/f834b96c-1f3b-48bc-889a-51868240f450)

So I think it would be convenient to have that button available even when normally viewing images.

**Comment by BrickMissle** [comment]
is this going to be added?

**Comment by zanllp** [comment]
@BrickMissle @ilcane87 
Already added.
<img width="1070" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/b416bed1-81ac-446e-8d8a-5de9154d141d">
