### ISSUE TITLE
[功能建议]优化多选操作及prompt显示

### ISSUE THREAD

**Issue by yuganxia** [zanllp/sd-webui-infinite-image-browsing#48]
非常非常好用 但是有两个小问题
第一个是 按住shift和ctrl多选的时候 如果发现最后的时候选多了不能取消选中 那就要整个重新选了
第二个是 希望点开浏览大图的时候在上面增加一个文本框 来显示图片的prompt等信息 这样能进行更加方便直观的对比

**Comment by zanllp** [comment]
我都实现了，你可以看readme里添加的演示视频来了解更多

**Comment by yuganxia** [comment]
十分感谢!!!
