### ISSUE TITLE
Feature request: Move folders, subfolders and files

### ISSUE THREAD

**Issue by otorre1** [zanllp/sd-webui-infinite-image-browsing#485]
I believe it would be very useful

**Comment by zanllp** [comment]
These are existing features, but they can only transfer files between different tab panes.

**Comment by zanllp** [comment]
https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/e631e3c3-1cbf-49bc-8577-f2963a6c9e4d

**Comment by otorre1** [comment]
I didnt know lol
Sorry
And thx for the example
