### ISSUE TITLE
Question: Remove Secret Key Popup

### ISSUE THREAD

**Issue by lunar-studio** [zanllp/sd-webui-infinite-image-browsing#486]
Hi. I love your extension as it's a great time-saver.
I work on multiple computers over my local network only. 
Is there any way to disable the secret key popup when using A1111 as set to "listen?" 
Perhaps we can have a checkbox option to remember device?

**Comment by zanllp** [comment]
Please read this link first： https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/.env.example

<img width="799" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/f7d36134-e841-4374-97a6-94ff43aa37cd">

**Comment by lunar-studio** [comment]
Okay thank you. It wasn’t clear if this simply disabled  network access all together or if it was only for the popup window.
