### ISSUE TITLE
Feature Request: NovelAI Support

### ISSUE THREAD

**Issue by Currenmoe** [zanllp/sd-webui-infinite-image-browsing#494]
Can you please add support for NovelAI? Here is a sample image.

![sample](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/156497210/ba31c8bf-e886-46e2-b3c9-db1308264ec5)

You can check metadata at https://novelai.net/inspect

Thank you for making this excellent work.

**Comment by zanllp** [comment]
Already Supported
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/04720dc0-2b8a-4656-8c8b-18e3548b8284)
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/77c3842f-6c58-4920-b075-beb4d5ff0859)
