### ISSUE TITLE
How to make it listen on 0.0.0.0 for Windows Standalone?

### ISSUE THREAD

**Issue by ItsNoted** [zanllp/sd-webui-infinite-image-browsing#499]
For some reason when I click the "Copy source file preview link" if gives me a url "https://tauri.localhosthttp://127.0.0.1:55025/infinite_image_browsing/file?xxxxxxxx"

First, why is it adding "https://tauri.local" to the beginning?

Second, how can I change the 127.0.0.1 to use 0.0.0.0? Where is the app.py file located on tthe standalone Windows version?

Ultimately I want to browse my images from my phone over the network.

Thank you

**Comment by ZhianLin** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25313785/f61f0b73-f3a7-4836-a839-3d2ade83536d)


> For some reason when I click the "Copy source file preview link" if gives me a url "https://tauri.localhosthttp://127.0.0.1:55025/infinite_image_browsing/file?xxxxxxxx"
> 
> First, why is it adding "https://tauri.local" to the beginning?
> 
> Second, how can I change the 127.0.0.1 to use 0.0.0.0? Where is the app.py file located on tthe standalone Windows version?
> 
> Ultimately I want to browse my images from my phone over the network.
> 
> Thank you

**Comment by ItsNoted** [comment]
This does not tell me where the file is located on windows standalone.

**Comment by ThesiiNCey** [comment]
Can WE now use it with to bind ip and Port ?

Bc i want to Run this on my Homeserver and want acces via Browser from an other PC?

**Comment by zanllp** [comment]
> Can we now use it with to bind ip and Port ?
> 
> Bc i want to Run this on my Homeserver and want acces via Browser from an other PC?

https://github.com/zanllp/sd-webui-infinite-image-browsing/discussions/594
