### ISSUE TITLE
Feature Request: Show number of images/items in folder

### ISSUE THREAD

**Issue by ItsNoted** [zanllp/sd-webui-infinite-image-browsing#500]
This is more of a request. I would love to see the number of items in the folder we are currently browsing. Here is an example.

![chrome_McdVZcCsIU](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/57927413/2697d6ba-e321-41b1-a38a-84d9eb822d12)

**Comment by zanllp** [comment]
update to the latest version

<img width="460" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/c1f5be52-d271-4c7e-92ea-0b9c1c1cdc55">
