### ISSUE TITLE
Can't read text on floating info window.

### ISSUE THREAD

**Issue by jipsita** [zanllp/sd-webui-infinite-image-browsing#504]
Because of the dark background and the black font I can't read the text in the "structured data" tab of the info window, I'm using the a1111 extension.

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/43711182/79f9c8b1-1c9d-4d3a-babe-1e5bfcfeb96f)

**Comment by zanllp** [comment]
Already fixed.
