### ISSUE TITLE
Prompt text not readable in dark mode

### ISSUE THREAD

**Issue by tddschn** [zanllp/sd-webui-infinite-image-browsing#507]
![CleanShot-2024-01-25T08-28-54@2x](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/45612704/db606695-1622-4050-9633-2719dec79c4b)

Prompt text in the Structured Data tab isn't readable in dark mode, while the Source Text is fine.

**Comment by younyokel** [comment]
+1 same on MS Edge

**Comment by zanllp** [comment]
update to the latest version.

**Comment by younyokel** [comment]
confirming fixed
