### ISSUE TITLE
Generate Index button doesn't seem to work when running without the Web UI

### ISSUE THREAD

**Issue by tddschn** [zanllp/sd-webui-infinite-image-browsing#508]
I'm running the app with `python app.py --port=7888` without the web UI, when the Generate Index button is clicked, I see these 2 requests (`Search Scope` is set to a valid dir containing images):

```
INFO:     my_ip:0 - "POST /infinite_image_browsing/db/update_image_data HTTP/1.1" 200 OK
INFO:     my_ip:0 - "GET /infinite_image_browsing/db/basic_info HTTP/1.1" 200 OK
```
The responses:

![CleanShot-2024-01-25T08-39-10@2x](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/45612704/2012da97-d67e-4e97-adf3-d37a81267a77)

![CleanShot-2024-01-25T08-39-16@2x](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/45612704/73358161-5fca-4b95-8de6-508d60e50e47)

The index doesn't seem to be built, and I can't toggle the Like tag on images:
![CleanShot-2024-01-25T08-40-37@2x](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/45612704/f7285949-9b6e-46fb-b30f-24e31e1f3242)

**Comment by zanllp** [comment]
Add the folder to the scanning path, and then regenerate the index on the search page.
<img width="1529" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/5a1241fa-d8a0-417a-8e62-b443de3b6497">

**Comment by zanllp** [comment]
Or provide the configuration related to sd-webui. Note: The configuration must include the folder where the images are located.

<img width="1420" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/413585d2-82f2-424f-8dcb-bff30221b905">
