### ISSUE TITLE
Use static config file instead of local storage

### ISSUE THREAD

**Issue by aaaaalexis** [zanllp/sd-webui-infinite-image-browsing#509]
**Problem**
Current implementation saves configuration in local storage, which causes inconvenience when using dynamic Gradio or ngrok link, as the settings would reset everytime a new instance opens. Furhermore, local storage takes up space that won't be cleared automatically.

**Solution**
Adding a new file for config only OR merge configuration with .env

The static file is prioritized and be the default state. An option to re-enable saving to local storage should be included.

**Comment by molegris** [comment]
hmmm, interesting.  Is this why Global settings are never saved?
I have to set "Default Grid Cell Width (px)" and "Toggle Selection of Tag like" every time I restart the WebUI.

**Comment by zanllp** [comment]
> hmmm, interesting. Is this why Global settings are never saved?
> I have to set "Default Grid Cell Width (px)" and "Toggle Selection of Tag like" every time I restart the WebUI.

Normally, you shouldn't need to set it every time, unless you are accessing it through different [origin](https://developer.mozilla.org/en-US/docs/Glossary/Origin) each time (i.e., protocols, domains, ports).

**Comment by zanllp** [comment]
@aaaaalexis @molegris This feature has been implemented in the latest version.
