### ISSUE TITLE
Fix needed on the new save image feature

### ISSUE THREAD

**Issue by dexyel** [zanllp/sd-webui-infinite-image-browsing#51]
Thanks for implementing that Save button as quickly as you did ! Exactly what I was looking for :) 
But I noticed a small issue, you can only save one image at the time, no matter how many you've selected and it'll always be the image clicked on, not even the last selected!

Also, is there an option somewhere to set a custom folder for the saved pictures?

**Comment by zanllp** [comment]
Yes, currently only sending file that trigger the right-click menu is allowed, and I haven't implemented the logic for multi-selection yet. 

This function's priority is not very high and may be implemented later. 

The saved folder is determined by reading the configuration of sd-webui (outdir_save). You can change this to achieve the desired result.
