### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by broli** [zanllp/sd-webui-infinite-image-browsing#514]
Be able to rename these. Give them a fantasy name so it fits the list better
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/152314/01533c2f-02df-4c22-950f-cf0782467acb)

**Comment by zanllp** [comment]
Already supported. See https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Change-log#add-support-for-adding-aliases-to-paths for more information.
