### ISSUE TITLE
[Feature Request] Docked/sidebar info pane

### ISSUE THREAD

**Issue by StylusEcho** [zanllp/sd-webui-infinite-image-browsing#516]
Hi, I have mixed feelings about the floating info pane. I usually have it open to view my prompt information, but because it is floating, it obscures the image.

I suggest having an option to dock the info pane on the left or right side to solve this issue.

**Comment by FrankHGS** [comment]
https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/531#issue-2166495518
像是這樣?

**Comment by StylusEcho** [comment]
> [#531 (comment)](https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/531#issue-2166495518) 像是這樣?

No. not exactly. Option for the sidebar to be permanently on the side, instead of over (covering) the image.

What you showed was still an improvement though.

**Comment by StylusEcho** [comment]
#671 Is almost exactly what I wanted! Just need an option to make the background black.

**Comment by zanllp** [comment]
Already supported. See https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Change-log#added-experimental-side-by-side-layout-for-fullscreen-image-browsing for more information

**Comment by zanllp** [comment]
Wow, I'm genuinely surprised and impressed that you've already seen my PR! I was in the midst of preparing the changelog and honestly thought your message was from a few months back until I checked my email just now. 😅

By the way, regarding your comment on making the background black, are you referring to the overlay layer during image previews,as indicated by the red circle in the image below?

<img width="1662" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/27865d82-e0d4-4035-98ad-7128379b1fb7">

**Comment by zanllp** [comment]
By the way, there was a slight issue with PR #671, but it's been fixed now. If you've already checked out #671, please make sure to pull the latest version to get those updates.

**Comment by StylusEcho** [comment]
I run a pull on all my A1111 extensions every time I run it, so that's how I caught your update so quick!

Thank you for the addition, and yes, the overlay layer circled.

Perhaps when this feature is finalised, being able to change whether it's on the left or the right would be nice.

**Comment by zanllp** [comment]
Adjust this option

<img width="952" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/4bdf90f1-d604-43d0-bfd3-c28dcdc47774">

**Comment by StylusEcho** [comment]
Incredible, thank you so much!
