### ISSUE TITLE
Does not honor sd-webui's --subpath parameter

### ISSUE THREAD

**Issue by levvayner** [zanllp/sd-webui-infinite-image-browsing#528]
📦 SD Wbui Version or Commit
cf2772fab0af5573da775e7437e6acdca424f26e

🐛 Bug Description
--subpath argument of webui is not implemented.

e.g. site is accessible through https://site.com/vision, using --subpath vision

🚦 Expected Behavior
Resources should be loading with base path https://site.com/vision instead of https://site.com

📷 Recurrence Steps
launch sd-webui with --subpath=somepath/

📝 Additional Information
workaround: use nginx proxy to redirect requests from https://site.com/infinite_image_browsing to https://site.com/vision/infinite_image_browsing

**Comment by zanllp** [comment]
This feature will be supported as soon as possible.

**Comment by zanllp** [comment]
Already supported
<img width="841" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/4023560a-aaf5-4739-a271-8df2f262d242">
