### ISSUE TITLE
使用桌面程式一片空白?

### ISSUE THREAD

**Issue by FrankHGS** [zanllp/sd-webui-infinite-image-browsing#530]
啟動時導入為 stable-diffusion-webui 發現一片空白? 並跳出發生了問題警訊

這裡我不知道是否是我自訂輸出資料夾的緣故還是...?

若是自訂引起我該如何讓他正常啟動?

在擴充裡自訂路徑是能夠讀取 圖生圖 文生圖...的

**Comment by zanllp** [comment]
可能是因为你选择的stable-diffusion-webui文件夹下没安装这个拓展

<img width="345" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/8c9feb71-57ba-410f-b70c-11cabc4778ef">
<img width="884" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/3fab1b90-50f3-46dc-81e7-1c62e66df36a">

**Comment by FrankHGS** [comment]
> 可能是因为你选择的stable-diffusion-webui文件夹下没安装这个拓展

當然有呀! 我是愛用者捏~ XD 

還有甚麼可能?

**Comment by zanllp** [comment]
能提供下log文件吗？或者你自己打开看看里面有什么错误
<img width="719" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/06be1b29-8d9f-4c4a-9198-dcfe066b392a">

通过右键打开文件夹
<img width="231" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/8b1bf8eb-eb33-444f-8ff6-4c9cc22771e6">

**Comment by FrankHGS** [comment]
> 能提供下log文件吗？或者你自己打开看看里面有什么错误

嗯... 裡面是空的...

**Comment by zanllp** [comment]
这就很尴尬了，你可以看下你的操作是否和视频中的一致https://github.com/zanllp/sd-webui-infinite-image-browsing/discussions/293#discussioncomment-6380081


你也可以初始化启动配置，然后把显示的错误截图给我看看
<img width="645" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/569d1c83-7800-4762-9fac-21edf4528bb3">

**Comment by FrankHGS** [comment]
這我操作好幾次 都一樣耶

Microsoft Defender ? 安裝時曾封鎖!

**Comment by FrankHGS** [comment]
![擷取](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/132704944/b8ffe966-c27f-4396-89c1-0b890b657f4f)

**Comment by FrankHGS** [comment]
> 我主要是想看下有没有这种提示，exe版本debug起来要难不少，信息太少 

可惜沒有...

只是跳出 "發生了個問題" ...

**Comment by FrankHGS** [comment]
![擷取2](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/132704944/a99e422f-0091-4e90-bf4b-44e6743aba87)
長這樣...

**Comment by FrankHGS** [comment]
我將之前曾備份預設路徑的 config.json 載入 竟然成功讀取!!

所以真的是自訂輸出資料夾(圖生圖 文生圖...)惹的禍? (我猜!? 沒仔細查證...

**Comment by zanllp** [comment]
能发下你的目前的config.json吗？，我输出的文件夹也是自定义的没事

**Comment by FrankHGS** [comment]
> 能發下你的config.json嗎？，我輸出的資料夾也是自定義的沒事

[config.json](https://github.com/zanllp/sd-webui-infinite-image-browsing/files/14503076/config.json)

我這裡也試試看哪裡出現問題....?

**Comment by FrankHGS** [comment]
我找到了...刪除這段成功讀取

    "animatoranon_film_folder": "D:\\frank\\Desktop\\AI暫存\\0.outputs\\Animator Extension\\frame_interpolation\\film.bat",
    "animatoranon_prop_folder": "D:\\frank\\Desktop\\AI暫存\\0.outputs\\Animator Extension\\props",
    "animatoranon_output_folder": "D:\\frank\\Desktop\\AI暫存\\0.outputs\\Animator Extension\\output",
 
但是因為是舊有的擴充殘留 還是中文路徑的關係?

**Comment by zanllp** [comment]
复现了，周末我看看怎么修这个问题

**Comment by FrankHGS** [comment]
所以他們各有各自的 iib.db ?
有差異的介紹嗎?

**Comment by zanllp** [comment]
试下这个，应该应该修复好了
[Infinite.Image.Browsing_0.8.1_x64-setup.zip](https://github.com/zanllp/sd-webui-infinite-image-browsing/files/14547868/Infinite.Image.Browsing_0.8.1_x64-setup.zip)

**Comment by zanllp** [comment]
> 所以他們各有各自的 iib.db ? 有差異的介紹嗎?

如果选择了数据共享，exe版本的IIB将会使用sd-webui内的iib.db，虽然exe版本的IIB也生成了iib.db文件但实际上是不使用的
<img width="950" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/a947957c-9d17-421d-819f-687e8b6f93a5">

如果不选择共享，则二者独立互不干扰,各用各的iib.db

**Comment by FrankHGS** [comment]
> 试下这个，应该应该修复好了 [Infinite.Image.Browsing_0.8.1_x64-setup.zip](https://github.com/zanllp/sd-webui-infinite-image-browsing/files/14547868/Infinite.Image.Browsing_0.8.1_x64-setup.zip)

糟糕! 這 ZIP 我下不來... 系統擋得很徹底 @@

**Comment by zanllp** [comment]
是github不让你下，还是window不让你下

**Comment by FrankHGS** [comment]
> 是github不让你下，还是window不让你下
window 之前是下 exe 允許威脅即可

**Comment by zanllp** [comment]
从这里下试试 https://github.com/zanllp/sd-webui-infinite-image-browsing/releases/tag/v0.8.1

**Comment by FrankHGS** [comment]
> 从这里下试试 https://github.com/zanllp/sd-webui-infinite-image-browsing/releases/tag/v0.8.1

嗯嗯! 下好安裝並成功讀取 感謝了!!
