### ISSUE TITLE
Weird issue - interface is messed up

### ISSUE THREAD

**Issue by tddschn** [zanllp/sd-webui-infinite-image-browsing#534]
![CleanShot-2024-03-05T12-16-40@2x](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/45612704/c85869a5-e620-454a-a5a2-d522f5833c91)

I just cloned the extention's master branch into the extensions directory, and this is what I see.

Is there anything I can do to help debug the issue?

**Comment by zanllp** [comment]
Could you please check if there are any error messages printed in the console?
