### ISSUE TITLE
是不是不支持forge

### ISSUE THREAD

**Issue by yincangshiwei** [zanllp/sd-webui-infinite-image-browsing#536]
我想使用stable diffusion forge了，但安装完插件后无法使用。
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/8185843/4f0381d7-e273-430a-b692-7cebc14143b6)

**Comment by zanllp** [comment]
很抱歉太忙了没管，我之前也没用过这个插件。
我刚才试了下是没问题的，考虑是不是其他问题，这个看起来像是完整不完整被删除了
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/1a9920da-60ff-443e-9fb6-73d34a6fa22a)
