### ISSUE TITLE
Feature Request: Tagging, multiple, and NOT deselect after placing tags

### ISSUE THREAD

**Issue by Manniala** [zanllp/sd-webui-infinite-image-browsing#540]
Hey.
I find my self ofthan, generating a good amount of images, before i go and places tags.

With CTRL + Click, and than tag, it works great, BUT there are ofthan a large amount that needs the same tags, and once i place 1 tag on a image set, everything is deselected.

Would really like if there were an option to keep/remember, the selection so that one could add more tags to the same set.

Or a Popup with all the tags, and you than go and CTRL + Click, press the popup and adds tags to the selected, instead of having the pull-down window.

**Comment by nealpaze** [comment]
I would appreciate this feature as well. I run into the same issue and tags are possibly the most valuable search function that I use all the time. When images are all in a row, it's not too hard to handle to go reselect but if you are clicking items not in order, it can be far more time consuming. While not a necessity, I would like the ability to retain the chosen items after adding tags. Having a modal options would be great.

**Comment by zanllp** [comment]
I have also noticed this issue, and I will try to find a solution soon. However, I don't want to disrupt the existing interaction logic.

**Comment by zanllp** [comment]
https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Change-log#support-keep-multi-selected

I have implemented a "Keep Multi-selected" feature. You can take a look and see if it meets your expectations.

**Comment by Manniala** [comment]
Thank you, i now have tested it a few days now, it works really well 👍
