### ISSUE TITLE
Can't delete the first picture in browse mode

### ISSUE THREAD

**Issue by 1manfactory** [zanllp/sd-webui-infinite-image-browsing#542]
The first picture in browse mode can never be deleted.
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/232674/1126f698-6aec-42f5-9c0d-3689be95f412)

**Comment by zanllp** [comment]
This is a relatively serious technical issue that cannot be resolved temporarily. If you want to delete this file, you can right-click on it in the grid view and select "Delete" from the menu.
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/2fbe5dbf-bc7a-42b6-9968-07ce3c6f21d4)

**Comment by zanllp** [comment]
I found a workaround, and in the latest version, this restriction has been removed. You can now delete it directly.

**Comment by 1manfactory** [comment]
GREAT
Thank you so much. That makes my life a bit easier.
