### ISSUE TITLE
第一次加载目录非常慢

### ISSUE THREAD

**Issue by koaqiu** [zanllp/sd-webui-infinite-image-browsing#545]
最新版的SD和插件（今天刚刚安装的）
WebUI 版本：1.6.0•  Python 版本：3.10.6  •  torch: 2.1.0
2024-3-15
Windows 11 专业版 22631.3296
安装在d盘
-----------------

点击 顶部的Tab进入，然后在”空白启动页“点击”文生图“，第一次加载会非常慢（几十秒），慢到我以为这个插件不能用。。。。。
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/542287/233a4130-8775-4247-a4e7-b503f8a9bf9a)

**Comment by zanllp** [comment]
参考这个自己排查下  ![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/74255967-073b-4f49-937d-f11ff7842900)

**Comment by zanllp** [comment]
https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/282

**Comment by koaqiu** [comment]
解决了，我自己小修改了一下
https://github.com/koaqiu/sd-webui-infinite-image-browsing/commit/99bd530dbf5d868c75d59150e7ed796a6d54c7ac

**Comment by zanllp** [comment]
合并了，感谢你的贡献
