### ISSUE TITLE
搜索功能中部分图片的tag并未被识别

### ISSUE THREAD

**Issue by zyd232** [zanllp/sd-webui-infinite-image-browsing#55]
首先，非常感谢加入了搜索功能。这个浏览器真的非常好用！

使用搜索功能时，部分图片的某些tag并未被识别，因此无法通过其包含的tag搜索到该图片。
我并不清楚为何某些tag没有被识别，但经过观察，我怀疑是由于以下情况引起的：

目前，对tag的识别是把逗号作为唯一的分隔符在处理的。当一个tag字符串前面不是以逗号分隔，而是以其他符号分隔时，该tag就不会被识别。例如：

有两张图片，
图片A的prompt为：
`realistic, still life, flower`
图片B的prompt为：
`realistic. still life, flower`

那么输入`still life`进行搜索，就只能搜到图片A，无法搜到图片B.

建议加入更完善的规则以区分tag，将`.` `|` `<>` `()` `[]` `{}` `:`等符号纳入其中。

P.S. 考虑到有些prompt可能是自然语言，或许换种搜索方式更好？

**Comment by zanllp** [comment]
后面应该会加入其他搜索作为辅助，例如包含子串, 就是现在另外一个更加流行的浏览器那种。
但肯定是目前这种tag多对多索引的方式为主，好处很多，速度可以做的很快，能知道使用过哪些作为prompt，能够按使用频率给你们排序，支持翻译，自动完成...。
这几个符号，我还得再看看，随便改很容易误伤，例如
```
 wildlife photography, photograph, high quality, wildlife, f 1.8, soft focus, 8k,
 national geographic, award - winning photograph by nick nichols
```
