### ISSUE TITLE
outputs迁移，导致自定义tag全部清除

### ISSUE THREAD

**Issue by samen168** [zanllp/sd-webui-infinite-image-browsing#552]
迁移outputs目录，到数据库更新路径，然后发现原路径下Image的自定义Tag全都从image_tag表删除了，包括Like！
这是有找不到就清除的机制吧

**Comment by zanllp** [comment]
对的，这个目前没写道什么好办法，除非移动操作都在IIB里面执行

**Comment by zanllp** [comment]
我加个自动备份数据库文件的机制，这个是真不好搞

**Comment by samen168** [comment]
刚从历史备份里找一份塞回来了 :)

**Comment by zanllp** [comment]
我写了个脚本来完成迁移

https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Proper-Folder-Migration-to-Avoid-Data-Loss---%E6%AD%A3%E7%A1%AE%E7%9A%84%E8%BF%81%E7%A7%BB%E6%96%87%E4%BB%B6%E5%A4%B9%E9%81%BF%E5%85%8D%E6%95%B0%E6%8D%AE%E4%B8%A2%E5%A4%B1
