### ISSUE TITLE
Security Vulnerability: Unauthenticated Local File Inclusion

### ISSUE THREAD

**Issue by TU-SJ** [zanllp/sd-webui-infinite-image-browsing#556]
# Issue
The extension exposes the Web UI instance to an unauthenticated Local File Inclusion vulnerability.
Example request:
```
POST /infinite_image_browsing/zip HTTP/1.1
Host: example
Content-Length: 45
accept: application/json
Content-Type: application/json
Connection: close

{
  "paths": [
    "/etc/"
  ]
}
```

Attackers can package and download any path they want to view.

An attacker could read the /etc/passwd file for example, /etc/hosts, /etc/resolv.conf to gain more information about the system.

An attacker could also read the /proc/self/environ variable to read the command line arguments used to execute Web UI and extract the username and password to login to the server.

# Fix
* Limit the paths where files can be packaged.

**Comment by zanllp** [comment]
The fix has already been submitted in PR #557
