### ISSUE TITLE
Paperspace - no paths

### ISSUE THREAD

**Issue by sixpt** [zanllp/sd-webui-infinite-image-browsing#558]
I'm running A1111 on Paperspace and no paths (including txt2img etc.) show up on the IIB tab in A1111. I cannot create the .env file in Jupyterlab, it gives me an error when I try to rename the example file and if I try to upload a '.env' file from my PC it seems to upload but does not appear in the folder in Jupyterlab. So I can't try changing the access control settings to see if it helps. Any suggestions?

**Comment by zanllp** [comment]
Does the terminal output any error messages? 

Regarding the issue with the .env file, you can check the following link (https://github.com/zanllp/sd-webui-infinite-image-browsing/discussions/236#discussioncomment-6181626), but I don't think that's the problem. Even if access control is enabled, it shouldn't affect normal access to the "output" directory.

**Comment by sixpt** [comment]
No errors;

No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 1.13.1+cu116. You might want to consider upgrading.
[-] ADetailer initialized. version: 24.3.2, num models: 10
CivitAI Browser+: Aria2 RPC restarted
CivitAI Browser+: Aria2 RPC restarted
ControlNet preprocessor location: /notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-03-25 04:00:57,857 - ControlNet - INFO - ControlNet v1.1.441
2024-03-25 04:00:58,134 - ControlNet - INFO - ControlNet v1.1.441
No module named 'dotenv'
Loading weights [None] from /notebooks/sd/stable-diffusion-webui/models/Stable-diffusion/ponyDiffusionV6XL_v6StartWithThisOne.safetensors
2024-03-25 04:01:08,001 - ControlNet - INFO - ControlNet UI callback registered.
Creating model from config: /notebooks/sd/stablediffusion/generative-models/configs/inference/sd_xl_base.yaml
Loaded ViT-bigG-14 model config.
Running on local URL: 
✔ Connected
IIB Database file has been successfully backed up to the backup folder.
Startup time: 70.0s (import torch: 7.8s, import gradio: 0.9s, setup paths: 1.3s, initialize shared: 0.2s, other imports: 1.3s, list SD models: 0.5s, load scripts: 6.5s, reload hypernetworks: 0.2s, initialize extra networks: 2.2s, scripts before_ui_callback: 0.2s, create ui: 47.4s, gradio launch: 0.4s, add APIs: 0.9s).
Applying attention optimization: xformers... done.
Model loaded in 69.5s (load weights from disk: 45.7s, create model: 1.1s, apply weights to model: 20.8s, hijack: 0.2s, calculate empty prompt: 1.5s).

**Comment by sixpt** [comment]
Weirdly, I restarted the machine and it works perfectly now. It hadn't worked the past couple of times I started a new machine, but whatever was happening was fixed.
