### ISSUE TITLE
Image comparison resize the image when the slider is moved

### ISSUE THREAD

**Issue by kirinobestgirl** [zanllp/sd-webui-infinite-image-browsing#573]
First of all, this extension was perfect when this function was working

Normally the frame should stay the same as you move the slider across but now which ever image has a larger portion of the frame gets resized and zoomed

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/166127461/513fdf3d-7f21-47f8-a74e-b2a8f06a6911)
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/166127461/dd6e8c6d-c8f5-404a-8b2d-c504546f86ba)

**Comment by kirinobestgirl** [comment]
Also thanks first of all, this extension was perfect when this function was working

**Comment by zanllp** [comment]
Could you send me these pictures? It would be helpful to reproduce the issue

**Comment by kirinobestgirl** [comment]
It doesnt matter which pictures are used, any two photos when placed in the image comparison (in the current tab or in the new tab) produce this issue even after deleting and re-installing the extension.

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/166127461/15c3ba34-facc-4d5c-ba08-474f714b35c8)

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/166127461/bd07a0b3-b22c-4a31-8f06-6bd27dcb74d2)

**Comment by zanllp** [comment]
I can't reproduce this issue on my end. It could also be related to your browser. It's best to use the latest version of Chrome.


https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/b762e5c0-b3a9-437d-83b2-d4749634ec4f

**Comment by kirinobestgirl** [comment]
Thanks for looking into it, confirmed it is working fine in Edge. FYI im using Brave browser (chrome based), not sure why it only started happening recently was working fine before

Please close this ticket

**Comment by kirinobestgirl** [comment]
I was able to reproduce the issue and determine that it is not browser specific. I have one monitor horizontal at 1920 x 1080 and another vertical same but 1080p x 1920

the horizontal monitor is fine but if you do the same on the vertical monitor is where the issue appears

**Comment by zanllp** [comment]
Is your IIB the latest version?

**Comment by kirinobestgirl** [comment]
nice one, works perfectly in the latest version thanks
