### ISSUE TITLE
Feature Request - Add compare image to the context menu

### ISSUE THREAD

**Issue by kirinobestgirl** [zanllp/sd-webui-infinite-image-browsing#576]
Would it be possible to please add the option to compare an image when rightclicking an image in the image browser?

Ideally the image that is selected will be the image that will show up on the left side of the image comparison popup window

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/166127461/37ea8e7f-6dff-4e3f-801c-3d06b3d6af33)

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/166127461/8b42b9b7-45c9-4bae-895b-a4fc3069e011)

**Comment by zanllp** [comment]
Have you ever used the following interaction method?


https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/0eb26af4-39a7-40b8-8e8b-bb1747c9870f


<img width="608" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/e7486146-f2a5-42cc-9aa8-1db2d8b43224">

**Comment by kirinobestgirl** [comment]
haha thats awesome, thanks

**Comment by kirinobestgirl** [comment]
im a dummy
