### ISSUE TITLE
每次打开webui都会在iib_db_backup目录下备份一次

### ISSUE THREAD

**Issue by IQ-Director** [zanllp/sd-webui-infinite-image-browsing#581]
每备份一次就是800多MB，手动删太麻烦，除了回退版本以外有没有什么手动关闭的方法。

**Comment by zanllp** [comment]
这个值改成0就不会备份了
<img width="1210" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/7d9cb436-f3a0-404c-9cfb-e52ed54fe2e2">

**Comment by IQ-Director** [comment]
是修改.env.example这个文件吗，修改后好像还是会备份。

**Comment by zanllp** [comment]
复制.env.example然后重命名为.env, 修改.env里面的值。只要能把这个环境变量传进去就行，其他方式也行


<img width="353" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/b2c0818e-eb93-4211-978e-c000554b6992">

**Comment by IQ-Director** [comment]
成功了，谢谢你
