### ISSUE TITLE
云端是不是不能用

### ISSUE THREAD

**Issue by feifei-000** [zanllp/sd-webui-infinite-image-browsing#588]
当我指定路径时，提示移动失败，检查你的路径输入year 0 is out of range

**Comment by feifei-000** [comment]
看了下报错FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open'
不过这个似乎要sudo权限，没有的话就用不了

**Comment by feifei-000** [comment]
使用walk模式进不去，但是我可以在图像搜索中的搜索范围里指定路径，然后在搜索结果里看图片

**Comment by feifei-000** [comment]
对我来说只要能用影响就不大，所以我就提一嘴

**Comment by zanllp** [comment]
云端当然可以用，这个插件最早就是为了解决云端速度慢才写的。
你这个问题应该是因为输出的文件夹在类似SMB协议或者云盘之类的地方上，不是在运行机器本地的硬盘上，python的api无法直接获取所在文件夹列表，我会看下如何解决或者是绕开这个问题

**Comment by zanllp** [comment]
新版本拥有更高兼容，后续如果有人遇到类似的问题可以看下这个 https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Change-log#2024-6-11-1
