### ISSUE TITLE
Panel covering navigation buttons

### ISSUE THREAD

**Issue by Enashka** [zanllp/sd-webui-infinite-image-browsing#591]
Very often, after browsing images from the extension tab, the panel so big that it covers the standard navigation buttons of the UI (text2img, img2img etc..). We can't navigate away from infinite-image and have no choice but to relaunch everything. See attached. (I'm on firefox on a mac)
![2024-04-16_23-00-52](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/19220062/6eca431d-53e3-45b1-ab01-097f4a5d0ef3)

**Comment by zanllp** [comment]
We need you to provide more information. What version of sd-webui are you using, what version of IIB (we recommend ensuring it's the latest version), and please include a screenshot of the error (capturing the entire browser) when it occurs.

**Comment by Enashka** [comment]
Thanks for replying. It is the latest version (I updated all my extensions a couple days ago). I would double check but I am stuck again on IIB not able to navigate anywhere and waiting for my current batch to complete. I checked for available updates yesterday so I'm likely all caught up.
![Uploading 2024-04-17_13-00-52.jpg…]()

**Comment by zanllp** [comment]
I couldn't reproduce this issue in the environment of latest A1111  and Firefox. Could you try using a different browser to see if the problem still occurs?

**Comment by Enashka** [comment]
I'm on that branch now. So far so good. I will let you know if it occurs again (as it was not systematic, maybe 75% of the time), but it seems to be fixed. Thanks for the reactivity, and of course the great extension.
