### ISSUE TITLE
Load extension error

### ISSUE THREAD

**Issue by leeyoshinari** [zanllp/sd-webui-infinite-image-browsing#597]
I use docker deploy stable-diffusion, and python version is 3.8.10. when i start stable-diffusion, it reports error:

> {"log":"*** error loading script: iib_setup.py\n","stream":"stderr","time":"2024-04-20t03:22:21.416409137z"}
{"log":"    traceback (most recent call last):\n","stream":"stderr","time":"2024-04-20t03:22:21.416505754z"}
{"log":"      file \"/opt/stable-diffusion-webui/modules/scripts.py\", line 382, in load_scripts\n","stream":"stderr","time":"2024-04-20t03:22:21.416515675z"}
{"log":"        script_module = script_loading.load_module(scriptfile.path)\n","stream":"stderr","time":"2024-04-20t03:22:21.416520571z"}
{"log":"      file \"/opt/stable-diffusion-webui/modules/script_loading.py\", line 10, in load_module\n","stream":"stderr","time":"2024-04-20t03:22:21.416525404z"}
{"log":"        module_spec.loader.exec_module(module)\n","stream":"stderr","time":"2024-04-20t03:22:21.416530076z"}
{"log":"      file \"<frozen importlib._bootstrap_external>\", line 848, in exec_module\n","stream":"stderr","time":"2024-04-20t03:22:21.416534012z"}
{"log":"      file \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n","stream":"stderr","time":"2024-04-20t03:22:21.416538717z"}
{"log":"      file \"/data/models/stable-diffusion/extensions/sd-webui-infinite-image-browsing/scripts/iib_setup.py\", line 1, in <module>\n","stream":"stderr","time":"2024-04-20t03:22:21.416542621z"}
{"log":"        from scripts.iib.api import infinite_image_browsing_api, send_img_path\n","stream":"stderr","time":"2024-04-20t03:22:21.416546558z"}
{"log":"      file \"/data/models/stable-diffusion/extensions/sd-webui-infinite-image-browsing/scripts/iib/api.py\", line 41, in <module>\n","stream":"stderr","time":"2024-04-20t03:22:21.416549918z"}
{"log":"        from scripts.iib.db.datamodel import (\n","stream":"stderr","time":"2024-04-20t03:22:21.416554686z"}
{"log":"      file \"/data/models/stable-diffusion/extensions/sd-webui-infinite-image-browsing/scripts/iib/db/datamodel.py\", line 86, in <module>\n","stream":"stderr","time":"2024-04-20t03:22:21.416559071z"}
{"log":"        class image:\n","stream":"stderr","time":"2024-04-20t03:22:21.416563359z"}
{"log":"      file \"/data/models/stable-diffusion/extensions/sd-webui-infinite-image-browsing/scripts/iib/db/datamodel.py\", line 209, in image\n","stream":"stderr","time":"2024-04-20t03:22:21.416569856z"}
{"log":"        ) -> tuple[list[\"image\"], cursor]:\n","stream":"stderr","time":"2024-04-20t03:22:21.416573504z"}
{"log":"    typeerror: 'type' object is not subscriptable\n","stream":"stderr","time":"2024-04-20t03:22:21.41657696z"}
{"log":"\n","stream":"stderr","time":"2024-04-20t03:22:21.416580321z"}
{"log":"---\n","stream":"stderr","time":"2024-04-20t03:22:21.416583585z"}

how to solve it? pls

**Comment by zanllp** [comment]
Please provide the versions of your stable-diffusion-webui and IIB first.

**Comment by zanllp** [comment]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/e4468acd-997c-4160-ae51-609b4f9938bd)

**Comment by leeyoshinari** [comment]
i find problem.  In python 3.8, it doesnot support  `list("Image")` or `tuple[]` and  etc...  it must use `List` and `Tuple` from `typing` package. 
thank you~
