### ISSUE TITLE
Creation date sorting... (st_ctime vs getctime)

### ISSUE THREAD

**Issue by rcarlier** [zanllp/sd-webui-infinite-image-browsing#601]
I have a small issue... (I am on MacOs)

By default, filenames are sorted by creation dates.

I just renamed a file, and curiously it comes in first position ; But renaming a file shouldn't change its creation date......

I investigated your code:

```py
# scripts/iib/api.py
created_time = get_formatted_date(item.stat().st_ctime)
```

`stat.ST_CTIME` does not react the same depending on the os (The “ctime” as reported by the operating system. On some systems - Unix, Mac - is the time of the last metadata change, and, on others - like Windows -, is the creation time)

It would probably be more robust to use `os.path.getctime(file_path)` ?

Apart from this small detail, very nice tool!

**Comment by zanllp** [comment]
I'll take another look at how to handle this issue in a few weeks; I'm currently traveling

**Comment by zanllp** [comment]
Update to the latest version to see if it has been fixed.
