### ISSUE TITLE
Load failed. / 加载失败

### ISSUE THREAD

**Issue by ananosleep** [zanllp/sd-webui-infinite-image-browsing#603]
Newly installed webui V1.9.3, and the extension cannot launch properly. / 新安装的webui 1.9.3版本，扩展无法正常加载。
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/126318157/7d89256d-7de8-4e83-aeca-67e5ce14acd0)

And there wasn't any error in the console. / 控制台没有输出任何报错。

**Comment by ananosleep** [comment]
Work properly after I deleted WebUI and did a completely clean install. Maybe there was some file broken before.

**Comment by zanllp** [comment]
If there are still issues, you can try running IIB directly using Python
