### ISSUE TITLE
Feature Request - AVIF Support

### ISSUE THREAD

**Issue by JunJi-JiaYue** [zanllp/sd-webui-infinite-image-browsing#606]
Since A1111 v1.9.1 supports output in the AVIF format, I kindly request that sd-webui-infinite-image-browsing also adds support for the AVIF image format.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15582

**Comment by zanllp** [comment]
I'll implement this feature in a few weeks; I'm currently traveling. Alternatively, you can implement it yourself and submit a pull request; the change is straightforward

**Comment by zanllp** [comment]
Already supported

<img width="1096" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/fd0f61a0-c60d-4f5d-a59e-2022cf2d1e3a">
