### ISSUE TITLE
[Feature request] Automatically put multiple checkpoints into Match Any

### ISSUE THREAD

**Issue by younyokel** [zanllp/sd-webui-infinite-image-browsing#609]
Image Search has always been a bit of a pain for me to use.
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/53343081/533ab50e-7763-4efb-a86d-c9169c5810e0)

When you select checkpoints, they go into Exact Match, so nothing is showing because there is usually only one model per image.

Maybe you can automatically put them in the Match Any if there is more than 1 checkpoint chosen?

You could also remember the previously interacted field so every button/tag simply goes into that field and not Exact Match.

**Comment by zanllp** [comment]
You could perhaps directly input "model" under "match any" and then add the corresponding options as prompted.
![Screenshot_2024-04-30-17-04-50-38_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/c322b33c-1996-4b62-9139-d70d9f55b67f)

**Comment by younyokel** [comment]
But when I press the tag it removes the 'model' from that field so I need to write it again. Or is it not expected behaviour?

> You could perhaps directly input "model" under "match any" and then add the corresponding options as prompted.

**Comment by zanllp** [comment]
This input box is a selector; you just need to click on the option you want directly
![Uploading IMG_20240430_193932.jpg…]()

**Comment by zanllp** [comment]
I came up with a new solution that won't cause behavioral differences when clicking tags under different types.

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/8a01cb31-9c8a-4878-8ddc-8fda0fb5b497)

**Comment by younyokel** [comment]
That's awesome, exactly what was needed!
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/53343081/193fbe3e-cc7a-40d4-a240-f13b3079af73)
Althought the dark theme is not corrected but that's a small issue.

**Comment by zanllp** [comment]
Already fixed.
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/150fa756-3664-429b-8660-5795492cb68d)
