### ISSUE TITLE
Regarding the backup files created by iib_db_backup

### ISSUE THREAD

**Issue by vivalavida1977** [zanllp/sd-webui-infinite-image-browsing#610]
Please let me know how to specify the number of generations to create.
I checked today and found 16 files, totaling 13GB. I would like to keep around 3 generations.

**Comment by zanllp** [comment]
see https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/.env.example


IIB_DB_FILE_BACKUP_MAX=3

**Comment by vivalavida1977** [comment]
Thank you for the quick response!
