### ISSUE TITLE
Delete custom tag issue

### ISSUE THREAD

**Issue by ChrisTello** [zanllp/sd-webui-infinite-image-browsing#614]
is there any way to manually delete custom tags that dont show the delete X next to them? I misspelled some tags but i dont get the X next to the tag to delete them.

**Comment by zanllp** [comment]
Please provide a screenshot of the page below. If this is a custom tag, it must have an 'X' button (except for 'like').

**Comment by ChrisTello** [comment]
> Please provide a screenshot of the page below. If this is a custom tag, it must have an 'X' button (except for 'like').

sorry was busy. i recreated the issue because i had to do a reinstall.
![Screenshot 2024-07-06 215411](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/40412807/8a724609-a03d-4372-8aec-eae685d8a477)
as you can see there is no X to delete the tag. The last time this happened i accidentally pasted a whole generation tag set.

**Comment by zanllp** [comment]
Do you not have a 'like' tag? Or did you manually modify the iib.db file before?
<img width="833" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/e6a369b8-c562-496f-af4b-314eab920a77">

**Comment by ChrisTello** [comment]
> Do you not have a 'like' tag? Or did you manually modify the iib.db file before? <img alt="image" width="833" src="https://private-user-images.githubusercontent.com/25872019/346311123-e6a369b8-c562-496f-af4b-314eab920a77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMjY2MDQsIm5iZiI6MTcyMDMyNjMwNCwicGF0aCI6Ii8yNTg3MjAxOS8zNDYzMTExMjMtZTZhMzY5YjgtYzU2Mi00OTZmLWFmNGItMzE0ZWFiOTIwYTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDA0MjUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYzA2MmJhMDM0OThhZGRmMzNkMTQ5YjY4YzQ0MmJmYzNiZTI2MjMyYjQ0MzdlYjE2ZDk1MGRiODUyYmQxY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KVOOYwXTD6CQuF42KJlWWfE0CxhMTJOCchEi-1vMmUs">

the like tag is there and its fine. i know that one isnt removable

**Comment by zanllp** [comment]
The reason this occurred is because the tag name is too long. I'll handle it.

**Comment by ChrisTello** [comment]
> The reason this occurred is because the tag name is too long. I'll handle it.

sounds good. love using this either way, appreciate your work!!

**Comment by zanllp** [comment]
This issue has been resolved.
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/95dab0fa-5aba-4540-813c-0f61cba64aee)

**Comment by ChrisTello** [comment]
> This issue has been resolved. ![image](https://private-user-images.githubusercontent.com/25872019/346322459-95dab0fa-5aba-4540-813c-0f61cba64aee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzI3NDUsIm5iZiI6MTcyMDM3MjQ0NSwicGF0aCI6Ii8yNTg3MjAxOS8zNDYzMjI0NTktOTVkYWIwZmEtNWFiYS00NTQwLTgxM2MtMGY2MWNiYTY0YWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3MTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYjYxZjE1ODI2MDNmYjgxZmY3Nzk5NmVkM2M1ZjQ0NWYyZDFhNTVmY2MxNjJlZjQxMGQ3MzA5M2U2MTMyNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.31rOo2nmWnG0zM__6yy20rrhgoHFf0hLJ89TskyjjO8)

nice its working, thank you so much.
