### ISSUE TITLE
關於 iib_db_backup 驚人的容量...

### ISSUE THREAD

**Issue by FrankHGS** [zanllp/sd-webui-infinite-image-browsing#616]
五月開始發覺備份容量已經來到了驚人的 25G !! 我不知還要在備份多少....趕緊刪除 0.0

可以在沒有更改路徑的情況下只做一個覆蓋備份 若有變更路徑再另行備份嗎?

真的太可怕了!! 哈哈~ 感謝喔!!

**Comment by zanllp** [comment]
https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/610


https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/581

**Comment by zanllp** [comment]
不是，为什么你们的iib.db会这么大，我三四万张图片 iib.db也才一百多mb

**Comment by zanllp** [comment]
我打算把默认备份数量改成4或者8

**Comment by FrankHGS** [comment]
> 不是，为什么你们的iib.db会这么大，我三四万张图片 iib.db也才一百多mb

> 我打算把默认备份数量改成4或者8

我的 iib.db 每個有 1.6G ... 20個加起來很恐怖的... O.O"

我再試試上面提供的方法 感謝~! XD
