### ISSUE TITLE
webui1.9.4版更新后排版变这样了，用的是chrome浏览器

### ISSUE THREAD

**Issue by feifei-000** [zanllp/sd-webui-infinite-image-browsing#644]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/56151016/c57aa653-da6f-4fce-bcf1-4f89f76d90dc)

**Comment by zanllp** [comment]
css没加载出来，多刷新几下看看

**Comment by zanllp** [comment]
记得先更新IIB到最新版

**Comment by feifei-000** [comment]
试过了还是这样，想退到1.9.3版本去了，之前还是可以加载的，能不能告诉我怎么退到原来的webui版本？

**Comment by zanllp** [comment]
在sdwebui的目录下`git checkout v1.9.3`切换到1.9.3

但我感觉应该不是1.9.4的原因，我在1.9.4试了下是没问题.

可以换个浏览器看看是不是也会，还可以看下终端和控制台是否有错误打印出来的。

下面这种是没报错的。
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/dacb8425-63f7-4f48-a471-b43826f7d1cb)

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/07bc6f60-7427-4f22-a52d-2990e45eb7f4)

**Comment by feifei-000** [comment]
我用的是云端，换了种内穿正常了，
