### ISSUE TITLE
[Feature request] Add hires. fix and refiner related tags to Image Search

### ISSUE THREAD

**Issue by younyokel** [zanllp/sd-webui-infinite-image-browsing#645]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/53343081/358521f8-dbe2-435f-a138-7ff3107d6967)

I also would like if you added Hires. fix and Refiner as "switch" tags, so you can easily sort upscaled and refined generations without using Fuzzy search's regex.
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/53343081/b97f5843-8d3c-4a18-9c33-2c43b23e5ee9)

**Comment by zanllp** [comment]
Already supported.
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/9d9377d6-fd6c-42d0-bfce-9f24cc976045)
<img width="536" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/2cd986b9-6682-4e7a-b82b-8cca1e2a8929">
