### ISSUE TITLE
資料夾存在但無法瀏覽

### ISSUE THREAD

**Issue by bluelovers** [zanllp/sd-webui-infinite-image-browsing#647]
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/167966/241d9018-1645-4838-b489-5935f619aba6)

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/167966/59e47078-a73c-40c0-b1dc-0804261674d6)

**Comment by zanllp** [comment]
确认下IIB是不是开启了访问控制模式，启用的话IIB会将不受信任的文件夹排除掉
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/175e7d92-1192-4b2c-a57d-745612140c2f)


具体参考  https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/518#issuecomment-2062029327
