### ISSUE TITLE
Refresh doesn't work

### ISSUE THREAD

**Issue by Mozoloa** [zanllp/sd-webui-infinite-image-browsing#65]
When I click refresh on my output folder and it doesn't refresh, I have to close the tab, or open another and browse back to the folder, only then it's updated

No error in the console, it's been like that on multiple commits

**Comment by zanllp** [comment]
This issue was also reported by several other people a few days ago. However, I have been busy developing other new features recently and haven't had enough time to fix it yet. It may take a few more days before I can start working on it.

**Comment by zanllp** [comment]
"I tried to refactor the 'refresh' function and it should work fine now. After the refresh is complete, there will be a message to notify you."

**Comment by zanllp** [comment]
Based on feedback from others, it seems that there are no issues at the moment, so I have closed this issue. If you have any further problems or requests, please create a new issue.
