### ISSUE TITLE
迁移文件夹后搜索功能报错

### ISSUE THREAD

**Issue by YD-River** [zanllp/sd-webui-infinite-image-browsing#650]
图片存在移动硬盘里，在连接移动硬盘的情况下打开了软件进行读取并建立索引，现在我在没有硬盘连接的情况下打开搜索功能就提示报错，无法搜索目前电脑上已有的文件，求解决方案

**Comment by zanllp** [comment]
如果需要在迁移后保留自定义tag参考。 https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Proper-Folder-Migration-to-Avoid-Data-Loss---%E6%AD%A3%E7%A1%AE%E7%9A%84%E8%BF%81%E7%A7%BB%E6%96%87%E4%BB%B6%E5%A4%B9%E9%81%BF%E5%85%8D%E6%95%B0%E6%8D%AE%E4%B8%A2%E5%A4%B1

**Comment by YD-River** [comment]
> 粘贴下错误信息

我使用的是桌面版，只显示“发生了个错误”，请问报错信息log文件通常在哪个路径？

**Comment by zanllp** [comment]
<img width="441" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/6572bd04-8522-4e46-bd2a-041ee078eda7">

这两个文件都是
<img width="689" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/69448e22-f430-464e-ba6f-2c4c4c0dff90">

**Comment by YD-River** [comment]
> <img alt="image" width="441" src="https://private-user-images.githubusercontent.com/25872019/337860317-6572bd04-8522-4e46-bd2a-041ee078eda7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MzM4NzUsIm5iZiI6MTcxNzgzMzU3NSwicGF0aCI6Ii8yNTg3MjAxOS8zMzc4NjAzMTctNjU3MmJkMDQtODUyMi00ZTQ2LWJkMmEtMDQxZWUwNzhlZGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA3NTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4Y2Y2NzQ2YTllODQxYTdiMzQ5ZTQ4M2ZlNzYwY2JmMGIyNzJkODI4ZWIxMzA5ZmEzM2I3Yjc3YmFkYzc3NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LZGyF8Mu6Ydcrw38NE3nIwXU1iexzv4c-Dvx4yJzNWo">
> 这两个文件都是 <img alt="image" width="689" src="https://private-user-images.githubusercontent.com/25872019/337860294-69448e22-f430-464e-ba6f-2c4c4c0dff90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MzM4NzUsIm5iZiI6MTcxNzgzMzU3NSwicGF0aCI6Ii8yNTg3MjAxOS8zMzc4NjAyOTQtNjk0NDhlMjItZjQzMC00NjRlLWJhNmYtMmM0YzRjMGRmZjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA3NTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlM2FjN2ExOWU1ZDFmZTAzYzkyMGEyOWY0NDdlNTliMDYxOGFlNTNhMzgyZjZjYmNiODljZDIwOWQzY2NmZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QoJBl_mpKtI-6x6bzf0d6mCRc7ClarzSJ-dRAJA0UvU">

对不起，不知道什么原因我的电脑上并没有这两个文件，我再找一下原因。

**Comment by zanllp** [comment]
不应该啊，难道你是很早之前的版本？要不先升级到0.14.0看看

**Comment by YD-River** [comment]
> 不应该啊，难道你是很早之前的版本？要不先升级到0.14.0看看

啊，原来如此，我是去年早期版本刚出的时候就下载了，一直没更新，您提醒我了……
更新之后问题解决了，谢谢您
