### ISSUE TITLE
Is it possible to save Fuzzy Search parameters?

### ISSUE THREAD

**Issue by Shyryp** [zanllp/sd-webui-infinite-image-browsing#658]
Is it possible to save Fuzzy Search parameters?

My pictures are generated and distributed into different folders (for example, [Account]/[Category]/[Quality]).
I often use Fuzzy Search to find folders with a certain quality for "walk" mode, for example by specifying "\RAW_images\".

But now I have to re-open Walk mode every time, then switch to Fuzzy search mode and re-enter “\RAW_images\” there, which takes me some time.

Is it possible to save Fuzzy Search search parameters so that they can be used even after restarting the program?
If not, can you add them in the future?

Thank you!

**Comment by zanllp** [comment]
Currently, this feature is not supported. However, I had a similar idea before, and I will implement this feature soon.

**Comment by zanllp** [comment]
Already Supported. See https://github.com/zanllp/sd-webui-infinite-image-browsing/wiki/Change-log#added-support-for-pinnable-search-history-records for more information
