### ISSUE TITLE
[Bug] Incorrect Dynamic Prompts template parsing

### ISSUE THREAD

**Issue by aaaaalexis** [zanllp/sd-webui-infinite-image-browsing#662]
'Structured Data' in image info panel cannot parse metadate generated with [sd-dynamic-prompts](https://github.com/adieyal/sd-dynamic-prompts) correctly. 

**Source text example**
```
Silhouette Art, hyperrealistic art, __lighting__, __composition__, __time__
Negative prompt: low quality
Steps: 25, CFG scale: 7, Seed: 387840411, Template: "Silhouette Art, hyperrealistic art, __lighting__, __composition__, __time__", Negative Template: "low quality"
```

**Parsed structured data**
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/65268477/d0153fb0-815e-462e-81c6-c24492dcb17e)

**Expected behavior**
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/65268477/b4c6a5a5-f75d-4a83-b827-0a722473e390)

**Additional**
Would be good if there's an option to copy template instead of actual prompt.

**Comment by zanllp** [comment]
> Additional
Would be good if there's an option to copy template instead of actual prompt.

Why can't you directly use "copy positive prompt"?

**Comment by zanllp** [comment]
Already fixed
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/b34075bb-ac7f-4ea9-975d-79ffafd3fe4e)

**Comment by zanllp** [comment]
Double-click to copy
<img width="779" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/974e95ab-9b3a-4a97-93a0-6c8036db0a56">
