### ISSUE TITLE
[问题反馈] 完全无法使用

### ISSUE THREAD

**Issue by lihaoyun6** [zanllp/sd-webui-infinite-image-browsing#68]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/16348097/235724359-ff3f8784-8ea4-4524-8467-1c6145da0bc6.png">
无论点击什么快速启动, 都显示这个错误提示, 并展示一个文件浏览界面, 但是什么文件夹也打不开

**Comment by zanllp** [comment]
更新下试试，我用mac试下没什么问题，linux我租了台机器还在还原镜像等下也试试

**Comment by lihaoyun6** [comment]
> 更新下试试，我用mac试下没什么问题，linux我租了台机器还在还原镜像等下也试试

刚刚更新了一下, 目前已经可以正常使用了. 十分感谢

**Comment by zanllp** [comment]
🎉 还有其他bug或需求欢迎继续提issue
