### ISSUE TITLE
False positive trojan?

### ISSUE THREAD

**Issue by maw-out** [zanllp/sd-webui-infinite-image-browsing#680]
Hi, I downloaded the executable for Windows version Infinite.Image.Browsing_0.16.0_x64-setup.exe and ESET antivirus flagged this: Python/PSW.Agent_AGen.R trojan horse.

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/122094708/3a9b3201-e334-4cff-931b-cc1b24a96678)

**Comment by zanllp** [comment]
<img width="737" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/0a7e84a3-d317-494b-b525-21c1d3dc219b">

https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/490

https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/397

**Comment by F370N** [comment]
I love the extension, and I'd really use the standalone version as my system image viewer, but man...

![Screenshot 2024-07-02 220924](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/140914256/4f59abee-f057-46ec-bd32-883844a66cb3)

This must be how potential employers feel about me when they run a background check, but really want to hire me.
I'm SICK of FastStone Image Viewer, but IDK if I'm _that_ sick of it.

Do the devs plan to rectify this at some point?

**Comment by zanllp** [comment]
> I love the extension, and I'd really use the standalone version as my system image viewer, but man...
> 
> I say this as respectfully as possible, but with the amount of work and effort that went into writing Infinite Image Browser, I just assume you guys (devs) could come up with a better solution than, **"Don't sweat the dang DEFCON 1 alert when you install the standalone, homie."**, for such an alarming problem.
> 
> I'm aware of the alternative **"compile it yourself"** suggestion, but at the risk of sounding like a complete layman, I think a lot of people forget that not everyone who uses the various SD frontends are _that_ capable, so to speak.
> 
> It's like a car mechanic patronizing you for not wanting the recalled component they included in their installation by saying, "Bro... It's totally safe. If you can't understand that, **_you can always just pull it out and throw it all back together yourself_**.
> 
> Do the devs plan to rectify this at some point?

Looks like there are way more folks using the standalone exe version than I expected. I kinda thought it was just a handful of people.

I'll try to put out an experimental build with a different compilation approach in the next release, but I can't guarantee it will happen - the dev effort isn't trivial and there are a lot of other feature requests still in the queue. Plus, I'm not working on IIB full-time.

I appreciate you taking the time to share this feedback. It's helpful to know these pain points are out there, even if I can't promise a perfect solution right away. Just wanted to let you know I heard ya and I'll see what I can do.

**Comment by zanllp** [comment]
In the latest release, a PyInstaller-compiled version has been added, significantly reducing the likelihood of false positive virus detections. https://github.com/zanllp/sd-webui-infinite-image-browsing/releases/tag/v0.17.0

@maw-out @F370N

**Comment by FrankHGS** [comment]
其實是真的想裝 EXE 版本 但這新版依然報毒... 唉...又刪了 TT

另外似乎不能更改 iib.db 的備份次數?

**Comment by zanllp** [comment]
> 其實是真的想裝 EXE 版本 但這新版依然報毒... 唉...又刪了 TT
> 
> 另外似乎不能更改 iib.db 的備份次數?

你杀毒软件用的Avast吗？


这个PyInstaller编译的版本感觉还明显比以前慢不少

### 更改 iib.db 的備份次數也是通过环境变量就行 

```
IIB_DB_FILE_BACKUP_MAX=0
```

直接把你以前的.env文件复制进去
<img width="350" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/6a73285b-9cf2-4d75-8dfb-8e9000470f5a">


<img width="896" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/c6a65ea6-95d4-485a-83d7-50e94a9e07d4">

**Comment by FrankHGS** [comment]
> 你杀毒软件用的Avast吗？

沒 就微軟內建的 會隔一段時間將程式隔離 就有點煩 @@"


> ### 更改 iib.db 的備份次數也是通过环境变量就行
> 直接把你以前的.env文件复制进去

嗯嗯! 好的 ^^"
