### ISSUE TITLE
不影响使用,但是每次启动都弹出这个错误提示

### ISSUE THREAD

**Issue by study520x** [zanllp/sd-webui-infinite-image-browsing#686]
是什么原因呢？
![7f0f57bb-01b6-4ca1-8acf-656358a3d324](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/38103451/78304233-2734-4046-a0af-df7d86124ad9)

**Comment by zanllp** [comment]
没找到git吧，catch漏了，觉得烦你可以先安装下git试试

**Comment by zanllp** [comment]
升级到0.17.1应该可以了

**Comment by study520x** [comment]
更新到0.17.1解决了，感谢勤快的作者
