### ISSUE TITLE
Keeping tabs after closing webui

### ISSUE THREAD

**Issue by RoyalXXX** [zanllp/sd-webui-infinite-image-browsing#692]
After restarting webui you have to reopen all the tabs you need, which is not very rational.
I suggest adding the feature to keep tabs open so you don't have to re-open them.

**Comment by zanllp** [comment]
<img width="797" alt="image" src="https://github.com/user-attachments/assets/fc24968b-a8a4-4ece-97ee-f8160d023242">

**Comment by zanllp** [comment]
This feature was implemented very early on, but now it seems that the name chosen might not be very appropriate.

**Comment by RoyalXXX** [comment]
I don't have that link

![Capture d'écran 2024-07-14 145002](https://github.com/user-attachments/assets/c38f90fe-52bb-45d3-9440-6303fb483c84)

Also, it would still be handy if tabs were restored automatically

**Comment by zanllp** [comment]
Are you running IIB on different origin each time? IIB's history is saved in the browser, unlike settings which are saved on the backend. The history is not shared between different origin.

![image](https://github.com/user-attachments/assets/6a63a2a0-829a-47b8-a61b-ffeb8045c450)

**Comment by RoyalXXX** [comment]
My browser deletes cache, cookies and all other data after closing. Apparently, because of this, I can't restore tabs from a previous session. For this very reason, it would be nice if the history was stored in the extension folder (`sd.webui\webui\extensions\sd-webui-infinite-image-browsing`) instead of in the browser. Also, could you please add an option in global settings to automatically restore tabs from a previous session?

**Comment by zanllp** [comment]
IIB will not store the history on the server for the time being, as this is a long-standing design that will not be changed lightly. However, I will introduce a "workspace snapshot" feature, which you can use to capture snapshots of your commonly used workspace combinations, and then specify which snapshot to restore at startup.

**Comment by zanllp** [comment]
![image](https://github.com/user-attachments/assets/f03e37f2-e9d9-41d1-9b86-7d6e74a099bd)

**Comment by RoyalXXX** [comment]
It didn't solve the problem in my case. Webui itself, as well as all other extensions, store their settings in the program folder and the extensions folder, respectively. And only your extension stores data about open tabs in the browser for some reason. 
Many people use the webui in incognito/private mode, which does not allow such data to be saved in the browser.
