### ISSUE TITLE
Split tags on `BREAK` when parsing prompt

### ISSUE THREAD

**Issue by astralarya** [zanllp/sd-webui-infinite-image-browsing#697]
When parsing the prompt for tags, in addition to splitting tags on `,` tags should be split when encountering a `BREAK` token.  `BREAK` causes a1111 to fill the current chunk with padding tokens and starts a new chunk.

**Comment by zanllp** [comment]
I have never used this feature before, could you provide the source file of the image for me to test?

**Comment by astralarya** [comment]
Documentation:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#break-keyword

**Comment by astralarya** [comment]
![00316-2776216102](https://github.com/user-attachments/assets/8b547e1b-87ca-4c99-80de-ff5644298068)
Example output

**Comment by zanllp** [comment]
![image](https://github.com/user-attachments/assets/06402cc1-cc01-48d9-9dd7-79a0f57ee495)

![image](https://github.com/user-attachments/assets/43d71369-94d9-4bc7-b12a-b6b1e71cf263)



You can "Rebuild image index" to process existing data.
<img width="515" alt="image" src="https://github.com/user-attachments/assets/0bf8da62-d768-494c-be41-325c10998c6c">
