### ISSUE TITLE
[Feature Request] Batch editing tags

### ISSUE THREAD

**Issue by astralarya** [zanllp/sd-webui-infinite-image-browsing#698]
Would it be possible to add batch tag editing functionality?  For example, performing a search and then on all matching images: remove a tag, add a tag.

**Comment by zanllp** [comment]
<img width="859" alt="image" src="https://github.com/user-attachments/assets/fec41ba4-8d6c-42df-b6a7-2a7f5a8ebbc2">

**Comment by zanllp** [comment]
Ctrl + A or Shift + A  -> Right click 

![image](https://github.com/user-attachments/assets/c2453523-0b96-48c8-a4b6-2be4a414b365)

**Comment by astralarya** [comment]
Oh thank you!
