### ISSUE TITLE
[Bug] Navigating search result image previews with arrow keys runs out of results

### ISSUE THREAD

**Issue by astralarya** [zanllp/sd-webui-infinite-image-browsing#699]
Repro:
* Image Search, perform search with large number of results
* Click image to open preview
* Use arrow keys to move through results
* Eventually the results end and cannot continue moving with arrow keys, but if you close the preview it jumps to the current page and there are more results

Seems like the loading of additional pages of results fails when navigating from inside the image preview.  Occurs in both the default layout and the "Experimental Side-by-Side Layout".

**Comment by zanllp** [comment]
This issue has been fixed.
