### ISSUE TITLE
[Feature request] Option to turn off automatic refresh in walk mode

### ISSUE THREAD

**Issue by younyokel** [zanllp/sd-webui-infinite-image-browsing#703]
One problem is that an image can shift as you view. Another is that when browsing the page, refreshing can cause the feed to freeze, start loading, or make you look at nothing. Once processing is complete, the screen/scroll position is different from before.

**Comment by zanllp** [comment]
![image](https://github.com/user-attachments/assets/8287762d-d1d1-449f-b59f-88e04e6c707e)
