### ISSUE TITLE
Send to... dialogue does not set schedule type

### ISSUE THREAD

**Issue by mining-away** [zanllp/sd-webui-infinite-image-browsing#718]
When selecting e.g. "send to text2img" or "send to img2img," schedule type is set to automatic rather than the schedule type from the sent image.

Is this intended? Am I missing a setting that would cause this?

Thank you so much for this extension. It's absolutely incredible. I still can't believe someone made one this complicated for sd webui. Seriously thanks! :)

**Comment by zanllp** [comment]
Sorry, I don't know why either. The "Send To" feature of IIB is actually simulated through several hidden Gradio components. This part of the code hasn't been touched for a long time. 



sd-webui-infinite-image-browsing: 
https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/6488c51f70da9dc205da903029454c65bf897ed5/scripts/iib_setup.py#L51-L64

When I implemented it, I referred to the source code of sd-webui: 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/feee37d75f1b168768014e4634dcb156ee649c05/modules/ui.py#L875-L879



<img width="1275" alt="image" src="https://github.com/user-attachments/assets/ac63c28f-9e52-4576-ba9d-2ba97971d2d8">

**Comment by mining-away** [comment]
Thanks for the info! I'll check upstream.
