### ISSUE TITLE
[Feature Request] Choose color for tags

### ISSUE THREAD

**Issue by Vik71it** [zanllp/sd-webui-infinite-image-browsing#730]
Hello, it would be a nice feature (for me, at least) to be able to choose the color of the custom tags, created in the Image Search tab. This way, it would be possible to associate colors to macro categories, which would be visibile at a first glance, even without reading the tag details.

**Comment by Vik71it** [comment]
Thanks a lot, it will be featured also in the next desktop standalone version ?

**Comment by zanllp** [comment]
The desktop application version will also have this feature. The desktop version might not be released as quickly. I usually wait until there are enough new features added or major issues fixed before releasing a new version
