### ISSUE TITLE
Full path of images missing in search results 

### ISSUE THREAD

**Issue by fbauer-kunbus** [zanllp/sd-webui-infinite-image-browsing#733]
Since IIB can be configured to walk over arbitrary directories, the full path of every found image should be shown somewhere in the results matrix. Should be there as a mouse over at least. 
I use IIB to scan six different GUI's output folders - and I need to see which GUI created an image at first glance. To my opinion it doesn't make sense to omitt this information.

**Comment by zanllp** [comment]
<img width="535" alt="image" src="https://github.com/user-attachments/assets/3f6176d3-92c2-4e9d-8a84-ae1b6cf3c3ba">


Do you want to display the full path here?

**Comment by fbauer-kunbus** [comment]
> Do you want to display the full path here?

I don't have any preferences where to display the full path - as I said it might as well be shown with a mouse-over event on 'File Name' only, since full paths obviously can become quite long. It would be convenient if one could copy it to the clipboard, of course, maybe with a right mouse button click or such.

**Comment by zanllp** [comment]
![image](https://github.com/user-attachments/assets/eab5c64d-87f6-422b-9b4e-8f393efb3c45)
You can also get the full path information through these two buttons

**Comment by fbauer-kunbus** [comment]
> You can also get the full path information through these two buttons

I don't understand ... my use-case is very simple: the IIB search function can find images in 6 different output directories on my system, since I currently use 6 different Stable Diffusion GUI for special purposes. If I find images that e.g. have a certain word in their prompts, I want to navigate to the different directories where they are stored with the least possible effort, since I need to work with those images in other programs, like Photoshop, IrfanView, external Upscalers and such ...  
It would be best if I simply could trigger the opening of the image directory in the explorer.

**Comment by zanllp** [comment]
I understand your point. This is just a temporary solution for you until I implement the full functionality.

![image](https://github.com/user-attachments/assets/6e91612f-d897-4118-a35e-346289e23274)

**Comment by fbauer-kunbus** [comment]
Thank you, this is a very good improvement of the already great IIB

**Comment by zanllp** [comment]
click here

<img width="322" alt="image" src="https://github.com/user-attachments/assets/b7369918-c4a7-49bf-8baf-a562bac17296">

![image](https://github.com/user-attachments/assets/735582ea-e01b-4c0f-96d0-bb7910d366a4)

**Comment by fbauer-kunbus** [comment]
Just updated and tested - works perfectly; many thanks, and I am sure other users will also appreciate!
