### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mschmid42** [zanllp/sd-webui-infinite-image-browsing#739]
Keyboard Shortcut for 'Send to Save' would be awesome... maybe pretty easy to add?

**Comment by zanllp** [comment]
I will look into how to implement this feature over the weekend.

**Comment by lordyami** [comment]
Hi, is it possible that you could add support for stealth metadata, please?

**Comment by zanllp** [comment]
> Hi, is it possible that you could add support for stealth metadata, please?

What is 'stealth metadata'?

**Comment by alienzed** [comment]
> Hi, is it possible that you could add support for stealth metadata, please?

Do you think you could create a separate issue for this? Seems unrelated...

**Comment by alienzed** [comment]
> I will look into how to implement this feature over the weekend.

no rush, but any progress? ^_^

**Comment by zanllp** [comment]
> > I will look into how to implement this feature over the weekend.
> 
> no rush, but any progress? ^_^

I've been quite busy with work, but should be able to get to it in a few days.

**Comment by alienzed** [comment]
thanks a million for all of your hard work :)

**Comment by zanllp** [comment]
The feature is now available.

<img width="777" alt="image" src="https://github.com/user-attachments/assets/751f8458-19e6-4a2a-b113-4c71781d1f72">


<img width="701" alt="image" src="https://github.com/user-attachments/assets/66030245-1530-4f34-9349-223818065618">

**Comment by alienzed** [comment]
Amazing! Thank you :D <3
