### ISSUE TITLE
无论点击哪个都会提示这个，不能跳转到文件夹里。

### ISSUE THREAD

**Issue by ilikeulinux** [zanllp/sd-webui-infinite-image-browsing#74]
![QQ截图20230503170543](https://user-images.githubusercontent.com/41497656/235875359-67cf0129-abfc-4fb3-8bcf-ae1852a7d629.jpg)
点击“无边图像浏览”里的“文生图”“图生图”等按钮，均出现如图提示，不能进入相应的文件夹里。

**Comment by zanllp** [comment]
是最新的版本吗？config.json 能不能发出来看下。 
前端的控制台能不能截图下看于上面报错
<img width="746" alt="image" src="https://user-images.githubusercontent.com/25872019/235877465-952ecbc3-743d-4f37-b62b-79c009eb2aae.png">

**Comment by ilikeulinux** [comment]
> 是最新的版本吗？sd-webui的 config.json 能不能发出来看下。 （包含 "outdir_txt2img_samples", "outdir_img2img_samples", "outdir_save", "outdir_extras_samples", "outdir_grids", "outdir_samples",）这些字段就行
> 
> 前端的控制台能不能截图下看下上面的报错 <img alt="image" width="746" src="https://user-images.githubusercontent.com/25872019/235877465-952ecbc3-743d-4f37-b62b-79c009eb2aae.png">
![QQ截图20230503175142](https://user-images.githubusercontent.com/41497656/235885118-7ae7c914-920c-44c4-a77d-61248c59900b.jpg)
扩展是最新版的，用的是秋叶的V4整合包。

**Comment by ilikeulinux** [comment]
以前是可以正常使用的，好像是前天就出问题了。

**Comment by zanllp** [comment]
能不能再检查下控制台，有提示“移动失败”那肯定会给你把错误打印出来
<img width="433" alt="image" src="https://user-images.githubusercontent.com/25872019/235888064-faaac324-206e-44ef-aaac-ae7e8770a360.png">


我这边死活复现不出来，我下载个他的整合包看看

**Comment by ilikeulinux** [comment]
![QQ截图20230503182301](https://user-images.githubusercontent.com/41497656/235891337-b5fafc4d-1eab-4deb-87a1-4ef612719912.jpg)

**Comment by zanllp** [comment]
哦不是，是前端的控制台，你按右键或者f12打开
https://user-images.githubusercontent.com/25872019/235892041-19880d08-02df-427b-9285-d2ad7dd5b34d.mp4

**Comment by ilikeulinux** [comment]
![QQ截图20230503183307](https://user-images.githubusercontent.com/41497656/235893067-9b95f810-b883-4415-ae0c-5db208d59683.jpg)

**Comment by ilikeulinux** [comment]
![QQ截图20230503183635](https://user-images.githubusercontent.com/41497656/235893681-532103ad-f7f1-4a96-a202-96dfc8e1de9b.jpg)

**Comment by ilikeulinux** [comment]
我找到问题原因了。
sd-webui-aki-v4这个文件夹，以前都是小写的。后来我同事把文件夹名改成了“SD-webui-aki-v4”，就出问题了。
我把SD改回到小写，问题就消失了。

**Comment by zanllp** [comment]
🎉 window对大小写不敏感，但是插件必须匹配上。
