### ISSUE TITLE
Recognizing prompt in preview node generated images

### ISSUE THREAD

**Issue by ermanitu** [zanllp/sd-webui-infinite-image-browsing#743]
IIB is perfect recognizing the images generated by Stable Diffusion 3.5 in CompfyUI, but not the images generated by flux.1

I think the problem can be the ClipTextEncodeFlux node (see examples)

It would be possible considering that IIB will recognize the prompts of that kind of file? I have a lot of them.

I attached some images.

![ComfyUI_temp_ylzay_00019_](https://github.com/user-attachments/assets/f523c83d-8d70-4e3a-8ddd-b8cf840df130)
![ComfyUI_temp_ylzay_00042_](https://github.com/user-attachments/assets/3f0c0128-e8ab-4c55-93f6-fb51c6a9eae3)
![ComfyUI_temp_ylzay_00103_](https://github.com/user-attachments/assets/38fe7f57-1c20-4e8b-af9c-50c695fae95a)

**Comment by ermanitu** [comment]
Ok, definitely  the problem is not the preview node, but the ClipTextEncodeFlux node. I tried with Stable Diffusion 3.5 and all is ok.

**Comment by zanllp** [comment]
Maybe it's a format that can't be directly parsed right now; I'll take a look at how to handle it later.

**Comment by ermanitu** [comment]
Hi, zanllp, I have some additional info:

When inspecting the workflow data attached to the png, I found that the text encoder for flux.1 has the prompt (supposing the toplevel node has label 6) in

workflow["6"]["inputs"]["t5xxl"] 

Not in

workflow["6"]["inputs"]["text"]

i.e., the problem is the "t5xxl" node label.

I gess you can try get date in "text" node and if it's no data you could try "t5xxl".

Thanks.

**Comment by zanllp** [comment]
try latest version

**Comment by ermanitu** [comment]
Now it’s all ok.

Thanks; wonderful app.
