### ISSUE TITLE
Recent update removed a feature? (open with local file browser)

### ISSUE THREAD

**Issue by MINIGI-mini** [zanllp/sd-webui-infinite-image-browsing#746]
![image](https://github.com/user-attachments/assets/2d708f5c-030b-4679-b927-1ae77101820f)
I am liking the update
but what was so bad about **Open file with Local browser?** or the feature that allows it to open the direct output file.
Is their anyway to get it back? Was it causing horrible glitches? I think this feature is very useful to me, becuase it allows me to find the file easily, so I can have the raw file, and I can do anything I want with it. If you can, may you re-add this feature?

the copy to bath is fine and all, but I would like to be able to effect the image file rather than just view it

**Comment by zanllp** [comment]
This feature has not been removed, but it only exists in the right-click menu.


![image](https://github.com/user-attachments/assets/352ce276-194a-4942-b638-63235b71f134)

**Comment by MINIGI-mini** [comment]
yes, Apologize, I was quick to act rather than just go and look for it, I am going to change the title and close

I also found it in the 3 dots on the image before you open it, thank you for this wonderous plugin!
