### ISSUE TITLE
为批量下载/归档增加“只打包不压缩”选项？

### ISSUE THREAD

**Issue by SpecterHi** [zanllp/sd-webui-infinite-image-browsing#755]
首先感谢这么好的工具，对于ComfyUI用户方便多了。

鉴于绝大多数时候都是PNG或者其他有损压缩格式的图片或者视频，实际上压缩一般并不会节约多少空间却浪费了大量的时间。

我测试了直接修改
scripts/iib/tool.py
将
create_zip_file
函数的
zipfile.ZIP_DEFLATED 
直接换成
zipfile.ZIP_STORED

实测等待弹出下载zip文件的时间明显减少啦，是否考虑加个开关选项或者默认只打包不压缩呢~

**Comment by zanllp** [comment]
过两天加下

**Comment by zanllp** [comment]
加上了
