### ISSUE TITLE
[Feature Request] Enable Image Deletion in Inspection Mode via "Delete" Key

### ISSUE THREAD

**Issue by 5teven** [zanllp/sd-webui-infinite-image-browsing#759]
Hi, I would like to request a new feature for the inspection mode. It would be incredibly convenient to have the option to delete the currently viewed image by simply pressing the "Delete" key on the keyboard.

Additionally, it would be helpful to include a "Delete" option in the menu near the existing "Copy prompt" button.

**Comment by zanllp** [comment]
What is Inspection Mode?

**Comment by 5teven** [comment]
> What is Inspection Mode?

I would like to clarify my previous feature request since there seems to have been some misunderstanding.

By "Inspection Mode," I mean the fullscreen image viewer that allows you to browse images in detail. In this mode, it would be very convenient to have the ability to delete the currently viewed image by pressing the "Delete" key on the keyboard.

Additionally, it would be great to have a "Delete" option in the dropdown menu that appears near the "Copy Prompt" button in this same viewing mode.

This feature would streamline the workflow significantly by allowing users to quickly manage their images without leaving fullscreen mode.

**Comment by 5teven** [comment]
Yes, that's right. But I can't figure out how to open it with the settings tab. I'm using

version: [v1.10.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/82a973c04367123ae98bd9abdf80d9eda9b910e2)

sd-webui-infinite-image-browsing | https://github.com/zanllp/sd-webui-infinite-image-browsing.git | main | 1a0f0712 | 2024-11-24 18:07:18 | unknown

**Comment by zanllp** [comment]
<img width="725" alt="image" src="https://github.com/user-attachments/assets/61df15fa-41d9-4ac6-adcd-c115a489a9cb">，
and then  scroll into bottom

**Comment by 5teven** [comment]
Thanks
