### ISSUE TITLE
Searching for filenames and filename parts only?

### ISSUE THREAD

**Issue by fbauer-kunbus** [zanllp/sd-webui-infinite-image-browsing#762]
When I use the 'fuzzy' search and give e.g. the search text '123' it gets me images where '123' is in the filename - or everywhere else in the image info, e.g. a seed like 23426123575

But what if I want to restrict the search to ONLY the filename?

I tried to use the normal search - but is there a way to search for filenames there? I didn't find it ...

Of course I could use an external search for this (even the Win explorer) but it would be convenient to stay in IIB for this also ...

**Comment by zanllp** [comment]
Currently, this feature is not supported.

**Comment by fbauer-kunbus** [comment]
> Currently, this feature is not supported.

ok, but you may admit, that it is not to far fetched ...
 There are many reasons why one could search for a part of the filename, or even the filepath without getting the results mixed with text from the prompt etc.

**Comment by zanllp** [comment]
I appreciate your input and will consider what you've said. However, even if I decide to add it, it won't be very soon as I'm currently very busy with work.

**Comment by zanllp** [comment]
Already supported
<img width="277" alt="image" src="https://github.com/user-attachments/assets/6b4bcb37-5e46-45d5-b4fd-06f9d6eb086a" />
