### ISSUE TITLE
other tabs obscured on occasion in ForgeUi

### ISSUE THREAD

**Issue by Mofo24** [zanllp/sd-webui-infinite-image-browsing#763]
sometimes when using infinite image tab, the other tabs become obscured and not visible in ForgeUi, not always but when it does happen the only way to get back to another tab like text2image, or whatever, is to close and reopen the browser, (happened in firefox and opera gtx)
![screen2024-12-24_22-17-40](https://github.com/user-attachments/assets/0add9af9-7337-4384-a867-f517d22f671a)

**Comment by zanllp** [comment]
Update to the latest IIB, and then open this option

 <img width="1088" alt="image" src="https://github.com/user-attachments/assets/0337f674-c111-4ddc-919d-5f12be9bcb83" />
