### ISSUE TITLE
This is the log content before using git pull.

### ISSUE THREAD

**Issue by bluenyx** [zanllp/sd-webui-infinite-image-browsing#78]
This is the log content before using git pull.
After using git pull, there is no log left.

2023-04-27 10:32:19,083 - scripts.logger - ERROR - [WinError 3] ������ ��θ� ã�� �� �����ϴ�: 'C:/Users/bluen/Documents/AI/stable-diffusion-webui-ux/stable-diffusion-webui-ux/outputs'
2023-04-27 10:32:22,759 - scripts.logger - ERROR - [WinError 3] ������ ��θ� ã�� �� �����ϴ�: 'C:/Users/bluen/Documents/AI/stable-diffusion-webui-ux/stable-diffusion-webui-ux/outputs'

_Originally posted by @bluenyx in https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/52#issuecomment-1530913279_

**Comment by zanllp** [comment]
Under Windows, the information recorded by the logger is not encoded in UTF-8. You can switch the encoding of your editor to view it (for example, in VS Code, use "Reopen with Encoding" and select the corresponding encoding).

<img width="112" alt="image" src="https://user-images.githubusercontent.com/25872019/236111571-f8cde6b7-d75f-4166-a767-7992dbe56a01.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/25872019/236111659-581897c3-20f4-4ed9-8369-ab18d74cd8f4.png">

However, if you are using the latest version of the extension without any problems, I think you can ignore this issue.   In the recent commits, I have strengthened the robustness of the database.

**Comment by bluenyx** [comment]
![image](https://user-images.githubusercontent.com/96876/236112586-7b401bf4-c48d-4df3-880b-fe6bacafbac1.png)

It's working very well on Webui. The problem is occurring only in Standalone. I don't know if I can't retrieve the value of config.json or if I can't recognize the value of the directory location.

**Comment by zanllp** [comment]
I just suddenly remembered that it's possible because the paths in the config.json file may not be absolute paths.

> !!! Note that if these paths are relative paths, they will be expanded to absolute paths relative to the current working directory, and once the expanded paths are not correct, they will be ignored. You can solve this problem by changing these paths to absolute paths.


![Uploading image.png…]()

**Comment by bluenyx** [comment]
I tried to recreate the config.json file, but it's the same.

config.json file : 

{
    "outdir_txt2img_samples": " C:\Users\bluen\Documents\AI\stable-diffusion-webui-ux\outputs\txt2img-images",
    "outdir_img2img_samples": "C:\Users\bluen\Documents\AI\stable-diffusion-webui-ux\outputs\img2img-images",
    "outdir_extras_samples": "C:\Users\bluen\Documents\AI\stable-diffusion-webui-ux\outputs\extras-images",
    "outdir_grids": "",
    "outdir_txt2img_grids": ":C\Users\bluen\Documents\AI\stable-diffusion-webui-ux\outputs\txt2img-grids",
    "outdir_img2img_grids": "C:\Users\bluen\Documents\AI\stable-diffusion-webui-ux\outputs\img2img-grids"
}

**Comment by zanllp** [comment]
Can you show me what the log file looks like when reopened with UTF-8 encoding?

**Comment by zanllp** [comment]
Your path seems to have some problem.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/25872019/236115651-8bfb1d26-f338-4d49-b3d6-429847cc6d1f.png">

**Comment by zanllp** [comment]
I'll add more checks and warnings for Standalone Operation. Debugging like this is too cumbersome.

**Comment by bluenyx** [comment]
> Can you show me what the log file looks like when reopened with the correct encoding? Or you can upload the log file for me to inspect

![image](https://user-images.githubusercontent.com/96876/236119453-67c53093-c980-42ec-99e0-4f6e116521c4.png)

No logs are left.

**Comment by bluenyx** [comment]
> Your path seems to have some problem. <img alt="image" width="800" src="https://user-images.githubusercontent.com/25872019/236115651-8bfb1d26-f338-4d49-b3d6-429847cc6d1f.png">
> 
> use “/” or “\\” replace all "\"。 and `"outdir_txt2img_grids": ":C\Users\bluen\Documents\AI\stable-diffusion-webui-ux\outputs\txt2img-grids",`. this conon is not correct. the path is not allowed start with conon

this is my mistake.

and fixed:

![image](https://user-images.githubusercontent.com/96876/236119872-355b3bba-b378-4372-984b-aace20053ac7.png)

**Comment by bluenyx** [comment]
> > Your path seems to have some problem. <img alt="image" width="800" src="https://user-images.githubusercontent.com/25872019/236115651-8bfb1d26-f338-4d49-b3d6-429847cc6d1f.png">
> > use “/” or “\” replace all ""。 and `"outdir_txt2img_grids": ":C\Users\bluen\Documents\AI\stable-diffusion-webui-ux\outputs\txt2img-grids",`. this conon is not correct. the path is not allowed start with conon
> 
> this is my mistake.
> 
> and fixed:
> 
> ![image](https://user-images.githubusercontent.com/96876/236119872-355b3bba-b378-4372-984b-aace20053ac7.png)

In Korea locale, "\" is automatically converted. No problem.

**Comment by zanllp** [comment]
I have added more checks, and you can verify by performing a similar operation as shown below.
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/25872019/236256510-d1081e19-bcc4-4a20-9cee-9f54fa7457ec.png">

**Comment by bluenyx** [comment]
> I have added more checks, and you can verify by performing a similar operation as shown below. <img alt="image" width="1262" src="https://user-images.githubusercontent.com/25872019/236256510-d1081e19-bcc4-4a20-9cee-9f54fa7457ec.png">

maybe UAC?

**Comment by bluenyx** [comment]
![image](https://user-images.githubusercontent.com/96876/236988810-2802c040-f173-405b-9274-1e9bbefb05d5.png)
![image](https://user-images.githubusercontent.com/96876/236988933-40dfb1a5-3706-4a6c-b9f7-d2fd615fb765.png)
![image](https://user-images.githubusercontent.com/96876/236988998-bb8a5392-e996-4e06-86bf-78b0625c176f.png)

**Comment by bluenyx** [comment]
In the case of reverse slash, whether in Korean or Japanese, it comes in each country's currency symbol, but it is automatically converted to the English-speaking "\". There is no problem if you do not specify it as a 949 code. Also, the "\" that divides directories is used as a slash "/" on Linux. I don't think this is the problem.

I think the location of the output folder in config.json is relative PATH. It's not relative PATH. Therefore, Addon within the SD-WebUI is PATH from the folder that ran SD-WebUI, so it is relative, and when running as Stand-Alone, it must be recognized as an absolute path. I think it's probably an error here.

**Comment by zanllp** [comment]
I know the reason why your error occurred. Try using this as your config.json. When your input is a relative position, the path you input is based on the folder of sd-webui, not the current working folder. And when the input is an absolute position, the parsing error occurred because a slash or two backslashes were not used.

```
{
  "outdir_txt2img_samples": "C:/Users/bluen/Documents/AI/stable-diffusion-webui-ux/outputs/txt2img-images",
  "outdir_img2img_samples": "C:/Users/bluen/Documents/AI/stable-diffusion-webui-ux/outputs/img2img-images",
  "outdir_extras_samples": "C:/Users/bluen/Documents/AI/stable-diffusion-webui-ux/outputs/extras-images",
  "outdir_txt2img_grids": "C:/Users/bluen/Documents/AI/stable-diffusion-webui-ux/outputs/txt2img-grids",
  "outdir_img2img_grids": "C:/Users/bluen/Documents/AI/stable-diffusion-webui-ux/outputs/img2img-grids",
  "outdir_save": "C:/Users/bluen/Documents/AI/stable-diffusion-webui-ux/log/images"
}
```

**Comment by zanllp** [comment]
I recommend using VS Code as your editor.

**Comment by bluenyx** [comment]
> I recommend using VS Code as your editor.

lol i'm using VSCode
