### ISSUE TITLE
一片黑暗QQ

### ISSUE THREAD

**Issue by geniusshiun** [zanllp/sd-webui-infinite-image-browsing#79]
![image](https://user-images.githubusercontent.com/10183057/236130137-7871c720-f29c-4264-9885-f7131c09ffb5.png)
![image](https://user-images.githubusercontent.com/10183057/236130283-61218491-43b1-4392-92be-2792f325c294.png)
![image](https://user-images.githubusercontent.com/10183057/236130459-434a4aa8-ea91-489f-8d06-60402482d778.png)
![image](https://user-images.githubusercontent.com/10183057/236130618-1c096bd6-69d2-4453-a673-57a0b0b51beb.png)

**Comment by zanllp** [comment]
重启下stable-diffusion-webui试试

不行把这个停用缓存勾上
<img width="482" alt="image" src="https://user-images.githubusercontent.com/25872019/236135015-08e67a46-07a4-4bc4-9e0a-56ec2f33b105.png">

**Comment by geniusshiun** [comment]
重啟跟停用，還有用無痕都沒用
我的web-ui是在 Running on local URL:  http://0.0.0.0:5000，我改了app.py的host為0.0.0.0，依舊是404
看了一下其他extension，他們的css取得的位置是：http://[url]/file=extensions/stable-diffusion-webui-images-browser/style.css?1682997656.429202
是不是檔案路徑的關係?

**Comment by zanllp** [comment]
app.py 是给独立运行用的，如果你使用sd-webui那么将不会执行这个文件。为了独立运行我们很多东西都是自己实现的，包括静态资源获取，所以url不太一样

监听0.0.0.0:5000我没试过。 我下班后再试试

**Comment by geniusshiun** [comment]
我執行web-ui的時候，是有使用 "--server-name '0.0.0.0' --enable-insecure-extension-access --port 5000 "

**Comment by geniusshiun** [comment]
我使用ngork就解決這個問題了=口=，可能是因為我是用GPU container mapping port，加上 --listen 與 --port，影響。
感謝你開發這個好用的extension，讚，回復也真的快！讚

**Comment by zanllp** [comment]
好的，那我先关闭这个 issue。如果您在后续使用过程中还有任何问题或需求，欢迎随时提issue 。
我已经在我的 Windows PC 和 Mac 上进行了测试，没有发现什么问题。
