### ISSUE TITLE
Dosen't work in sd webui

### ISSUE THREAD

**Issue by BursonHandsom** [zanllp/sd-webui-infinite-image-browsing#84]
I have installed the extension,but it dosen't work when I click the tab “inifinite image browsing”，just blank area like below
![image](https://user-images.githubusercontent.com/36667664/236384181-7c4dc664-1741-4698-8376-a3ae62025bfb.png)

**Comment by zanllp** [comment]
"Is the version of sd-webui being used up-to-date? Here are some steps you can take to troubleshoot:

1. Try restarting the stable diffusion webui.
2. Alternatively, right-click and select 'inspect' (or press F12) and click on 'disable cache' before refreshing the page.

If there are any errors with Python or the browser console, please send a screenshot."

**Comment by BursonHandsom** [comment]
THX，I have found the solution. just change the running URL of web UI.
It didn't work when I chose the local url(http).
now it work when I choose the  public(https).
![image](https://user-images.githubusercontent.com/36667664/236392564-61df1430-f0a9-4b24-aa17-89ccd2657c32.png)

**Comment by zanllp** [comment]
I have closed this issue. If you have any further problems or requests, please create a new issue.

**Comment by Ulf3000** [comment]
change url to 

localhost:7860 

instead of 

127.0.0.1:7860
