### ISSUE TITLE
Feature request: Closing with one pane left should bring you back to Empty start page

### ISSUE THREAD

**Issue by NutchapolSal** [zanllp/sd-webui-infinite-image-browsing#85]
Currently, when trying to close the last pane, it shows "Deletion is not allowed with only one pane left!!!". I think it would be better if it brings you back to the start page instead of doing nothing.

**Comment by zanllp** [comment]
This feature is now available

**Comment by zanllp** [comment]
I have closed this issue. If you have any further problems or requests, please create a new issue.
