### ISSUE TITLE
如何指定目录创建索引 搜索？

### ISSUE THREAD

**Issue by Intorain** [zanllp/sd-webui-infinite-image-browsing#86]
如何指定目录创建索引 搜索？

**Comment by zanllp** [comment]
目前不支持自定义，文件夹都是从sd-webui的配置中读取的。

但是你使用独立运行的话，可以自己传入指定的文件夹，他会递归处理，对下面的所有文件夹都创建索引

https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/47

**Comment by Intorain** [comment]
> 目前不支持自定义，文件夹都是从sd-webui的配置中读取的。
> 
> 但是你使用独立运行的话，可以自己传入指定的文件夹，他会递归处理，对下面的所有文件夹都创建索引
> 
> #47

好的。谢谢你。

**Comment by zanllp** [comment]
新加了这个 
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/9e4f7fff-853e-4c56-8dcb-c6b3277c9d82)
