### ISSUE TITLE
发送到保存文件夹和切换标签选中时出错

### ISSUE THREAD

**Issue by DaojuRen** [zanllp/sd-webui-infinite-image-browsing#87]
如题，例如在stable-diffusion-webui/outputs/txt2img-images/2023-05-05的文件夹下的图片，想发送到指定文件夹或指定标签时会出现以下错误：
1. 非 Stable Diffusion webui 文件夹下不支持切换 tag，如果有需要请提 Issue
2. 移动文件 C:\Projects\stable-diffusion-webui\outputs\txt2img-images\2023-05-05\00268-4098422362.png 到 C:/Projects/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/log/images 时出错：[Errno 2] No such file or directory: 'C:/Projects/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/log/images'

**Comment by zanllp** [comment]
拓展版本是最新的吗？更新下

**Comment by DaojuRen** [comment]
是最新的，9179a931 (Thu May 4 17:47:03 2023)
尝试了关闭后台重启和删除重新安装都不行

**Comment by zanllp** [comment]
2修好了，1我复现不出来，你先更新下看看

**Comment by DaojuRen** [comment]
谢谢大佬，2已经修复了，但是1还是不行

**Comment by zanllp** [comment]
应该可以了，你试下

**Comment by zanllp** [comment]
那行，我先关了，有其他问题或者需求，重新开一个issue
