### ISSUE TITLE
无法给多个选中的图像添加like收藏标签

### ISSUE THREAD

**Issue by sMallFAt6** [zanllp/sd-webui-infinite-image-browsing#98]
大佬您好！

如标题所言，用shift或者ctrl选中多个图片然后右键->切换标签选中(收藏)，只能给右键时鼠标所指的图片添加收藏标签。

我以为表现会和右键->删除选中一样可以作用多个图片，结果发现不符合预期，还请大佬抽空排查一下，谢谢大佬🙏

**Comment by zanllp** [comment]
这个暂时还不支持，目前多选只能移动/删除/发送到保存文件夹，有需要的话我后面再加上
